### PR TITLE
#8247: login banner button doesnt show error on failure to show web auth flow

### LINKED ISSUE #8247: Login banner button doesn't show error on failure to show web auth flow
## Describe the bug

- Login banner button doesn't show error on failure to show flow
- Mike would not have access to the flow, because it's behind a VPN: https://pixiebrix.slack.com/archives/C0436P48QHY/p1712778512171219

## To Reproduce

1. Create a PKCE integration that links to an inaccessible URL
2. Run a mod that uses it
3. Click the login button in the banner

## Actual behavior

Nothing happens

## Expected behavior

An informative error is shown the to user

## Screenshots/Loom

- See Slack message: https://pixiebrix.slack.com/archives/C0436P48QHY/p1712778512171219

### PR DESCRIPTION
**Pull request by grahamlangford**
## What does this PR do?

- Fixes #8247

## Demo

https://www.loom.com/share/1ffe1b795faa48d5928d3b653f804b07

## Checklist

- [x] Add jest or playwright tests and/or storybook stories
- [x] Designate a primary reviewer @fungairino

### CODE REVIEW

File: src/background/auth/authHelpers.ts [hunk 1]
```diff
@@ -49,6 +49,12 @@ export async function launchWebAuthFlow(
     ) {
       throw new InteractiveLoginRequiredError(message, { cause: error });
     }
+
+    if (message === "Authorization page could not be loaded.") {
```
Comment (fungairino) [inline src/background/auth/authHelpers.ts:53]: It would be more ideal to check a unique error code rather than the message which could be likely to change for copy reasons.

**Review by fungairino — APPROVED** [review]

File: src/background/auth/authHelpers.ts (hunk 1 above)
Comment (twschiller) [reply src/background/auth/authHelpers.ts:53]: I think we should be passing the error cause along here?

File: src/background/auth/authHelpers.ts [hunk 2]
```diff
@@ -49,6 +49,12 @@ export async function launchWebAuthFlow(
...
+      throw new InteractiveLoginRequiredError(
+        "Unable to load the page. Try again later or contact support for more assistance.",
```
Comment (twschiller) [inline src/background/auth/authHelpers.ts:55]: I think we should be passing the error cause along here

Comment (twschiller) [inline src/background/auth/authHelpers.ts:55]: @BrandonPxBx can you support on the message? I think it should be along the lines of "Unable to load the login page. Try again, or contact your team admin if the problem persists"

**Comment by BrandonPxBx** [comment]
> @BrandonPxBx can you support on the message? I think it should be along the lines of "Unable to load the login page. Try again, or contact your team admin if the problem persists"

The message @grahamlangford used was what I wrote, we can't use "login page" because my understanding was this error could occur for other scenarios.
