### PR TITLE
#7673: Avoid CORS issues in ImageReader

### LINKED ISSUE #7673: Image Reader: Failed to execute 'toDataURL' on 'HTMLCanvasElement': Tainted canvases may not be exported.
## Describe the bug

I want to right click to copy an image to the clipboard. When it reaches the first brick (Image reader) is shows an error notification.

## To Reproduce

1. Add Context Menu for images
2. Add Image reader brick
3. Set Element as the `Target Root Mode`
4. Set `@input.element.ref` as the target element
3. Use the context menu on the "Your extension factory" image in https://www.pixiebrix.com/

## Actual behavior

Screenshot

## Expected behavior

The Data URL is passed to the next brick

## Screenshots/Loom

https://github.com/pixiebrix/pixiebrix-extension/assets/1402241/2e972bd5-2679-4fe8-93d9-52a6fc0bcb72

## Desktop (please complete the following information):

- OS: macOS
- Extension Version:
1.8.10-alpha.1-local+2024-02-20T07:23:25.116Z

## Related

I was testing:

- https://github.com/pixiebrix/pixiebrix-extension/issues/6812
- https://github.com/pixiebrix/pixiebrix-extension/pull/7635

### PR DESCRIPTION
**Pull request by fregante**
## What does this PR do?

- Fixes #7673
- Clarifies the expectations of the affected functions
- Reuses existing code
- Distinguishes "image" data (via canvas) from "binary" data (via fetch)

## Demo

Repro available on the original issue

https://github.com/pixiebrix/pixiebrix-extension/assets/1402241/20895b02-17ce-4e7c-8a7b-d0646c29a3bd

## Future Work

- [ ] Maybe further reorganize related functions after https://github.com/pixiebrix/pixiebrix-extension/pull/7925

## Checklist

- [ ] Add tests
- [x] Designate a primary reviewer: @grahamlangford

### CODE REVIEW

File: src/utils/imageUtils.ts [hunk 1]
```diff
@@ -0,0 +1,105 @@
...
+
+// SVG images don't have any EXIF data
+const dataUrlBase64Image = /^data:image\/(png|jpg);base64,/;
+
+/**
+ * Load an image URL into an ArrayBuffer, preserving its original binary data (required for EXIF for example)
+ *
+ * This supports all URLs, including data: and blob: (neither one of which would trigger an HTTP request)
+ */
+export async function loadImageBinaryData(
```
Comment (fregante) [inline src/utils/imageUtils.ts:30]: Original implementation:

https://github.com/pixiebrix/pixiebrix-extension/blob/117b5a38fd28b85a87a6d48c9a07af6ef91f43de/src/bricks/readers/ImageExifReader.ts#L25-L47


Changes:

- accept a string instead of `` since `img` is not strictly required (can't read binary from it)
- throw proper error on SVG images
- drop redundant axios-based fetch
- drop TODO

File: src/utils/imageUtils.ts [hunk 2]
```diff
@@ -0,0 +1,105 @@
...
+  return parsed!.encodedBody;
+}
+
+/**
+ * Returns base64 encoding of the image from an <img> tag.
+ *
+ * @warning The base64 encoding is not guaranteed to match the original image binary. For that, use `loadImageBinaryData`
+ * @warning If the loaded image is not CORS-safe, a new HTTP request will be made.
+ */
+export async function loadImageAsBase64(
```
Comment (fregante) [inline src/utils/imageUtils.ts:79]: Previous implementation:

https://github.com/pixiebrix/pixiebrix-extension/blob/117b5a38fd28b85a87a6d48c9a07af6ef91f43de/src/bricks/readers/ImageReader.ts#L21-L41

Changes:

- clarify expectations of function, add warnings
- if already a base64, skip conversion
- use natural image size instead of the authored ``
- detect CORS issues and re-load image anonymously

File: src/utils/imageUtils.ts [hunk 3]
```diff
@@ -0,0 +1,105 @@
...
+async function getBase64FromImageViaCanvas(
+  image: HTMLImageElement,
+): Promise<string> {
+  // Ensure it's loaded
+  await image.decode();
+  const canvas = paintImageOntoNewCanvas(image);
+  const dataURL = canvas.toDataURL("image/png");
+  const parsed = parseDataUrl(dataURL);
+  // eslint-disable-next-line @typescript-eslint/no-non-null-assertion, @typescript-eslint/no-unnecessary-type-assertion -- The browser just generated it, it's safe. If it fails, then it's likely a bug in `parseDataUrl` and it should be fixed.
+  return parsed!.encodedBody;
```
Comment (grahamlangford) [inline src/utils/imageUtils.ts:70]: If `parseDataUrl` _does_ fail, it would be good to report the dataURL to DataDog to make it easier to debug. I don't think it's very likely though.

**Review by grahamlangford — APPROVED** [review]

File: src/utils/imageUtils.ts (hunk 3 above)
Comment (fregante) [reply src/utils/imageUtils.ts:70]: Let's wait until that error shows up in the logs before we spend time on it
