### PR TITLE
#8587: Fix bad logging MessageContext

### LINKED ISSUE #8587: Live Editing - Mod logs stuck in infinite spinner
## Steps to Reproduce

- https://pixiebrix.slack.com/archives/C0436P48QHY/p1722543196533479

Side note: How long has this been broken, and why did we not notice this earlier? Error reporting working for this case?

## Use cases to verify in end to end test
- Logs
    - Debug / warn / info / error logs after runs
    - Notification shown on Logs tab if error ocurred
    - User cancelling action for temporary modal or sidebar form
    - Appropriate brick is flagged as a check mark on success or exclamation mark if error.

### PR DESCRIPTION
**Pull request by mnholtz**
## What does this PR do?

- Closes #8587 
- Fixes a bad MessageContext state pushed to the store in EditorPane
- [x] TODO: add `isError` and `error` to `logSlice` to stop swallowing errors when polling logs
- [x] TODO: add and e2e test for viewing the Logs tab in the Page Editor
- [x] TODO: why isn't Typescript checking the shape passed to `logActions.setContext`?

## Demo

https://www.loom.com/share/018fd74069ef4e6298124ab912983cf8

### CODE REVIEW

File: src/components/logViewer/logSlice.ts [hunk 1]
```diff
@@ -67,24 +71,38 @@ const pollLogs = createAsyncThunk<
...
+    },
+  );
+};
+
+export const logSlice = createSlice({
   name: "logs",
   initialState: initialLogState,
   reducers: {
-    setContext(state, { payload: context }: PayloadAction<MessageContext>) {
+    setContext(state, action: PayloadAction<MessageContext>) {
```
Comment (mnholtz) [inline src/components/logViewer/logSlice.ts:104]: We're explicitly setting `MessageContext` as the type here. So why didn't Typescript catch the bad keys passed to `setContext` in EditorPane? 

Something weird is going on with the optional types on `MessageContext`. If I replace `MessageContext` with non-optional keys on the type, the type-checking works as expected.

File: src/pageEditor/panes/EditorPane.tsx [hunk 2]
```diff
@@ -56,9 +57,10 @@ const EditorPaneContent: React.VoidFunctionComponent<{
   );
 
   useEffect(() => {
-    const messageContext = {
-      extensionId: modComponentFormState.uuid,
-      blueprintId: modComponentFormState.modMetadata
+    // TODO: Why wasn't this throwing a type error?
+    const messageContext: MessageContext = {
+      modComponentId: modComponentFormState.uuid,
+      modId: modComponentFormState.modMetadata
```
Comment (mnholtz) [inline src/pageEditor/panes/EditorPane.tsx:63]: This is the fix. I want to be able to ensure this doesn't happen again by getting type-checking to work properly.

File: src/components/logViewer/logSlice.ts (hunk 1 above)
Comment (mnholtz) [reply src/components/logViewer/logSlice.ts:104]: Discussion here: https://pixiebrix.slack.com/archives/C023KL47XV4/p1722892873076509

I'm implementing an improvement that should prevent us from passing completely wrong objects in the future

File: src/components/logViewer/LogCard.tsx [hunk 3]
```diff
@@ -38,13 +39,21 @@ const LogCard: React.FunctionComponent<OwnProps> = ({
...
   const dispatch = useDispatch();
   const refreshEntries = () => dispatch(logActions.refreshEntries());
   const clearAvailableEntries = () => dispatch(logActions.clear());
 
   const logs = useLogEntriesView({ level, page, perPage });
 
+  if (isError) {
+    return (
+      <Card.Body>
+        <ErrorDisplay error={error} />
```
Comment (mnholtz) [inline src/components/logViewer/LogCard.tsx:52]: Returning ErrorDisplay instead of throwing & catching in an ErrorBoundary because LogsCard is dynamically rendered via an array, so throwing an error will not isolate the error view to just the logs tab, which is what we want

File: src/components/logViewer/logSlice.ts [hunk 4]
```diff
@@ -67,25 +69,51 @@ const pollLogs = createAsyncThunk<
...
+        state.entries = castDraft(availableEntries);
+      }
+    },
+  );
+  builder.addCase(pollLogs.rejected, (state, { error }) => {
+    state.isError = true;
+    state.error = error;
+    state.isLoading = false;
+  });
+};
```
Comment (mnholtz) [inline src/components/logViewer/logSlice.ts:101]: Logic here is unchanged - extracted from logSlice

File: end-to-end-tests/pageObjects/pageEditor/modEditorPane.ts [hunk 5]
```diff
@@ -50,6 +68,15 @@ export class ModEditorPane extends BasePageObject {
     }),
   );
 
+  logsTab = this.getByRole("tab", { name: "Logs" });
+  async getLogsTabPanel() {
+    const logsTabPanel = this.getByRole("tabpanel").filter({
+      hasText: "Message/Error",
+    });
+    await expect(logsTabPanel).toBeVisible();
```
Comment (fungairino) [inline end-to-end-tests/pageObjects/pageEditor/modEditorPane.ts:76]: We don't need to add this expect here, it should just fail the next time we actually assert or do an action on this locator. You can just declare the new panel similar to the other ones in this class.

File: src/types/loggerTypes.ts [hunk 6]
```diff
@@ -20,7 +20,7 @@ import { type RegistryId, type SemVerString } from "@/types/registryTypes";
 import { type ContextName } from "webext-detect";
 
 /**
- * Log event metadata for the extensions internal logging infrastructure.
+ * Log event metadata for the mod component's internal logging infrastructure.
```
Comment (twschiller) [inline src/types/loggerTypes.ts:23]: I think this should be extension. It's referring to the browser extensions internal logging infrastructure

File: src/components/logViewer/logViewerTypes.ts
Comment (twschiller) [inline src/components/logViewer/logViewerTypes.ts:1]: Not necessarily for this PR, but would probably be good to rewrite this as a AsyncState in the future especially now that we've added isError and error to it

File: src/types/loggerTypes.ts (hunk 6 above)
Comment (mnholtz) [reply src/types/loggerTypes.ts:23]: Oh, I see

File: src/components/logViewer/logSlice.ts [hunk 7]
```diff
@@ -67,25 +69,51 @@ const pollLogs = createAsyncThunk<
...
+
+export const logSlice = createSlice({
   name: "logs",
   initialState: initialLogState,
   reducers: {
-    setContext(state, { payload: context }: PayloadAction<MessageContext>) {
-      state.activeContext = context;
+    setContext(
+      state,
+      // Add messageContext as a required object property to get better type checking for MessageContext, which
```
Comment (twschiller) [inline src/components/logViewer/logSlice.ts:109]: ❤️

**Review by twschiller — APPROVED** [review]

File: src/components/logViewer/logSlice.ts (hunk 4 above)
Comment (BLoe) [reply src/components/logViewer/logSlice.ts:101]: Do we really need the `isError` flag in state? Does this ever diverge from the `error` field? It could just be dynamically created in the selector with `Boolean(error)` also.

Comment (BLoe) [reply src/components/logViewer/logSlice.ts:101]: I guess it's fine to leave it for now if you don't want to refactor it as part of this PR 🤷‍♂️

Comment (mnholtz) [reply src/components/logViewer/logSlice.ts:101]: Haha, realized that logic was changed here on lines 96-100

**Review by BLoe — APPROVED** [review]

File: src/components/logViewer/logSlice.ts (hunk 4 above)
Comment (twschiller) [reply src/components/logViewer/logSlice.ts:101]: > Do we really need the isError flag in state? Does this ever diverge from the error field? It could just be dynamically created in the selector with Boolean(error) also.

IIRC, technically something can throw undefined: https://stackoverflow.com/questions/30049093/javascript-is-it-safe-to-throw-undefined. So you need to be explicit on whether or not it's in an error state

Comment (mnholtz) [reply src/components/logViewer/logSlice.ts:101]: I added it for consistency with our other hooks, e.g. useAsyncState, but it doesn't have to be that way

**Review by fungairino — APPROVED** [review]

File: end-to-end-tests/pageObjects/pageEditor/modEditorPane.ts (hunk 5 above)
Comment (mnholtz) [reply end-to-end-tests/pageObjects/pageEditor/modEditorPane.ts:76]: I had declared it similar to the other ones before - the logs pane takes a few seconds to load compared to the configuration panels
