### PR TITLE
#6139: fix multiple activation permissions check; always show options during reactivation

### LINKED ISSUE #6139: Add Support for Multi-Mod Activation Links over any Page
https://www.notion.so/pixiebrix/Customer-Support-Mod-Pack-Activation-376e2b3bf301432bbd831f8b66e2c914?pvs=4#b3abafde6fb24dec93d419a92021a270

### PR DESCRIPTION
**Pull request by twschiller**
## What does this PR do?

- Closes #6139 
- Ignores permissions during multiple mod activation
- Always shows mod options during reactivation in sidebar. (Because reactivation is used for reconfiguration)
- NOTE: for multiple mod activation, mods that are already active are ignored

## Checklist

- [x] Add tests: the are getting covered in Rainforest QA: https://app.rainforestqa.com/tests/395899
- [x] Designate a primary reviewer: @BLoe

### CODE REVIEW

**Comment by mnholtz** [comment]
> Ignores permissions during multiple mod activation

I don't understand the impact this has on the user experience? What happens if one of the mods in the multi-activation requires permissions the user hasn't granted?

**Comment by twschiller** [comment]
> What happens if one of the mods in the multi-activation requires permissions the user hasn't granted?

See comment in the code here: https://github.com/pixiebrix/pixiebrix-extension/pull/6171/files#diff-44ac72c561693606dde2941bca1ba80c25d894db5227cac094e36862d0c19147R77

Does that answer your question?

**Review by BLoe — APPROVED** [review]

File: src/sidebar/activateRecipe/ActivateModPanel.tsx [hunk 1]
```diff
@@ -293,14 +294,16 @@ const ActivateRecipePanelContent: React.FC<
...
+  // Additionally, always show the options if this is a reactivation.  (Reactivation, in practice, is used to
+  // reconfigure mod options)
   useEffect(() => {
     if (
       state.needsPermissions != null &&
       !state.needsPermissions &&
       !requiresConfiguration &&
-      !state.activationError
+      !state.activationError &&
+      !isActive
```
Comment (mnholtz) [inline src/sidebar/activateRecipe/ActivateModPanel.tsx:306]: 👍

File: src/activation/useActivateRecipe.ts [hunk 2]
```diff
@@ -102,25 +104,29 @@ function useActivateRecipe(
...
-              reactivate: isReactivate,
-            });
-          }
 
-          return {
-            success: false,
-            error: "You must accept browser permissions to activate.",
-          };
+        if (checkPermissions) {
+          const isPermissionsAcceptedByUser =
```
Comment (mnholtz) [inline src/activation/useActivateRecipe.ts:109]: I'm not confident about this suggestion, but the original var name isn't grammatically correct 🤷‍♀️
```suggestion
          const hasUserAcceptedPermissions =
```
