### PR TITLE
#9313: fix delete draft mod component

### LINKED ISSUE #9313: Don't delete component from activated mod when removing in Page Editor
Context
---
- When a user deletes a mod component in the Page Editor, it also removes the mod component from the activated mod instance
- Otherwise, there was no way for the Page Editor to keep the activated mod component off the page, because the Page Editor only replaces mod component on selection (and there's no way to select a draft mod component)
- https://github.com/pixiebrix/pixiebrix-extension/pull/9298 changes the Page Editor behavior to run the whole draft mod instance
- Therefore, it's now possible to correct the deletion logic to only remove the component in the draft that's injected by the Page Editor

Discussion
---
- 🐛  There might be a bug in https://github.com/pixiebrix/pixiebrix-extension/blob/238eb4b2d45df6e45aa7e61f544d4ce91955f15c/src/pageEditor/store/editor/editorSliceHelpers.ts#L127-L127 where it doesn't mark the form state as a deleted form state (called from useRemoveModComponentFromStorage)

Related Code
---
- https://github.com/pixiebrix/pixiebrix-extension/blob/e707e43b515440882eaa9a75a3a06ef575dbea9b/src/pageEditor/hooks/useRemoveModComponentFromStorage.tsx#L43-L43

### LINKED ISSUE #9315: Deleting a mod component from a mod does not mark the mod as dirty
Extension Extension Version: 2.1.5

Steps to Reproduce:
GIVEN I am viewing the Page Editor
AND I expand a mod with multiple mod components
WHEN I delete one of the mod components
AND make no other changes
Actual
THEN the save mod button is disabled
AND I am unable to save the mod
Expected
THEN the save mod button is enabled
AND I am able to save the mod

[Slack Thread](https://pixiebrix.slack.com/archives/C0436P48QHY/p1729185382535679)

### PR DESCRIPTION
**Pull request by twschiller**
## What does this PR do?

- Closes #9313
- Closes #9315
- 🐛 Fixes bug in `useClearModChanges` where deleted form states (which could include changes) where reverted back to form state (which might include changes) instead of a form state corresponding to the activated mod instance
- Approach is to take advantage of changes in https://github.com/pixiebrix/pixiebrix-extension/pull/9298 to keep the Page Editor's copy of the mod more separate
- Refactoring
  - `deactivateUtils.ts` → `deactivateModHelpers.ts`

## Discussion

- [x] Decide whether or not to fix bug where adding a draft mod component and deleting the draft component leaves the mod "dirty". Technically the mod probably shouldn't be considered dirty in that case. But IIRC it also doesn't hurt anything to consider it as dirty

## Remaining Work

- [x] Confirm behavior of #9315
- [x] Verify clearing changes brings back the original mod component form state. The gotcha is that the behavior of `useClearModChanges` is incorrect. It revives the deleted form states instead of reverting back to the activated mod component versions
- [x] Broken Jest tests
- [x] Add Jest integration tests to cover bugs fixed

## Future Work

- Up next: consolidate saving logic
- Consider having the Page Editor have its own copy of the mod as opposed to keeping track of mod components vs. form states

For more information on our expectations for the PR process, see the
[code review principles doc](https://www.notion.so/pixiebrix/Code-Review-Principles-1ce7276b82a84d2a995d55ad85e1310d?pvs=4)

### CODE REVIEW

File: src/store/editorStorage.ts [hunk 1]
```diff
@@ -66,35 +66,10 @@ export async function saveEditorState(
 }
 
 /**
- * Remove a list of mod components by id from persisted redux storage.
+ * Remove all mod components for a given mod from persisted Page Editor Redux storage.
  *
- * Note: this does not trigger a change even in any current redux instances
- * @param modComponentIds the mod components to remove from persisted redux storage
- */
-export async function removeDraftModComponents(
```
Comment (twschiller) [inline src/store/editorStorage.ts:74]: Not used in production code

File: src/store/editorStorage.test.ts [hunk 2]
```diff
@@ -50,127 +48,12 @@ const setReduxStorageMock = jest.mocked(setReduxStorage);
 
 const currentPersistenceVersion = getMaxMigrationsVersion(migrations);
 
-describe("draftModComponentStorage", () => {
+describe("editorStorage", () => {
   beforeEach(() => {
     jest.resetAllMocks();
   });
 
-  test("removes one active form state", async () => {
```
Comment (twschiller) [inline src/store/editorStorage.test.ts:58]: Drop tests for non-production code

File: src/store/deactivateModHelpers.ts [hunk 3]
```diff
@@ -19,47 +19,68 @@ import { type Dispatch } from "react";
...
 ): Promise<void> {
+  forbidContext("pageEditor");
+
   const removedDraftModComponentIds =
     await removeDraftModComponentsForMod(modId);
 
   dispatch(modComponentActions.removeModById(modId));
 
-  removeModComponentsFromAllTabs(
+  await removeModDataAndInterfaceFromAllTabs(
```
Comment (twschiller) [inline src/store/deactivateModHelpers.ts:61]: Cleanly split the Redux vs. non-Redux code so the non-Redux code can be called from extension and Page Editor contexts

File: src/pageEditor/store/editor/editorSliceHelpers.ts [hunk 4]
```diff
@@ -122,34 +123,42 @@ export function setActiveNodeId(state: Draft<EditorState>, nodeId: UUID) {
...
+
+  // Remove from list mod components available on the page, if available
+  remove(state.availableDraftModComponentIds, formStateId);
 
-  const draftIndex = state.availableDraftModComponentIds.indexOf(uuid);
-  if (draftIndex > -1) {
-    // Mod component is available, remove from list of available ids
-    state.availableDraftModComponentIds.splice(draftIndex, 1);
+  if (formState) {
+    // FIXME: should this only mark as deleted if the component corresponds to a component on the activate mod instance?
```
Comment (twschiller) [inline src/pageEditor/store/editor/editorSliceHelpers.ts:155]: - [ ] TODO: verify behavior

**Comment by twschiller** [comment]
@grahamlangford the main logic is in the PR, so you can start reviewing if you want to get a head start

File: src/store/editorStorage.test.ts [hunk 5]
```diff
@@ -50,332 +46,56 @@ const setReduxStorageMock = jest.mocked(setReduxStorage);
...
-    expect(setReduxStorage).toHaveBeenCalledWith(
-      "persist:editor",
-      baseState,
-      currentPersistenceVersion,
+    const actualModComponentIds = await removeDraftModComponentsByModId(
+      modMetadata.id,
     );
-  });
-
-  test("removes inactive recipe", async () => {
```
Comment (twschiller) [inline src/store/editorStorage.test.ts:278]: This test was testing for available vs. unavailable components for the page (i.e., if their host pattern matches). That aspect is not relevant for mod deletion. And, if it was should be tested on the reducer tests instead of the storage test

File: src/store/editorStorage.test.ts [hunk 6]
```diff
@@ -50,332 +46,56 @@ const setReduxStorageMock = jest.mocked(setReduxStorage);
...
-
-    await removeDraftModComponents([formState.uuid]);
+  test("removes mod but keeps other form states", async () => {
+    const otherFormState = formStateFactory();
 
-    expect(setReduxStorage).toHaveBeenCalledWith(
-      "persist:editor",
-      initialState,
-      currentPersistenceVersion,
+    const targetEditorState = editorSlice.reducer(
```
Comment (twschiller) [inline src/store/editorStorage.test.ts:57]: Re-wrote the test to not perform manual Redux state creation

**Comment by grahamlangford** [comment]
> Decide whether or not to fix bug where adding a draft mod component and deleting the draft component leaves the mod "dirty". Technically the mod probably shouldn't be considered dirty in that case. But IIRC it also doesn't hurt anything to consider it as dirty

First impulse is to say not to bother at this time because it's ostensibly harmless. Let's look into this once all of the Page Editor changes are implemented

File: src/pageEditor/hooks/useClearModComponentChanges.ts [hunk 7]
```diff
@@ -84,7 +82,7 @@ function useClearModComponentChanges(): (
         dispatch(actions.adapterError({ uuid: modComponentId, error }));
       }
     },
-    [dispatch, mods, sessionId, activatedModComponents, showConfirmation],
+    [dispatch, sessionId, activatedModComponents, showConfirmation],
```
Comment (grahamlangford) [inline src/pageEditor/hooks/useClearModComponentChanges.ts:85]: It's interesting that there's not an official linting rule for catching unused deps similar to exhaustive-deps

File: src/pageEditor/hooks/useDeleteDraftModComponent.tsx [hunk 8]
```diff
@@ -0,0 +1,107 @@
...
+  shouldShowConfirmation?: boolean;
+};
+
+const DELETE_DRAFT_MOD_COMPONENT_PROPS: ConfirmationModalProps = {
+  title: "Delete starter brick?",
+  message: "This action cannot be undone.",
+  submitCaption: "Delete",
+};
+
+const DELETE_ACTIVATED_MOD_COMPONENT_PROPS: ConfirmationModalProps = {
```
Comment (grahamlangford) [inline src/pageEditor/hooks/useDeleteDraftModComponent.tsx:48]: This is still a draft getting deleted, correct? As-in we're deleting the draft mod component that was created from an activated mod component, we're not actually deleting the activated mod component. The activated mod component wouldn't be deleted unless the developer saves the mod after deleted the draft mod component. 

Maybe better names would be `DELETE_RECOVERABLE_DRAFT_MOD_COMPONENT_PROPS` AND `DELETE_NON_RECOVERABLE_DRAFT_MOD_COMPONENT_PROPS`? I think the existing name is too confusing

File: src/pageEditor/store/editor/editorSliceHelpers.ts [hunk 9]
```diff
@@ -122,34 +123,42 @@ export function setActiveNodeId(state: Draft<EditorState>, nodeId: UUID) {
...
+    const modId = formState?.modMetadata.id;
```
Comment (grahamlangford) [inline src/pageEditor/store/editor/editorSliceHelpers.ts:156]: NIT: Shouldn't need the optional here

File: src/pageEditor/store/editor/editorSliceHelpers.ts (hunk 4 above)
Comment (grahamlangford) [reply src/pageEditor/store/editor/editorSliceHelpers.ts:155]: Logically that makes sense to me. Are you concerned about UX or is there something else you're concerned about? We're already warning that deleting a draft mod component that does not have a backing activated mod component can not be recovered

File: src/store/editorStorage.ts [hunk 10]
```diff
@@ -66,62 +63,37 @@ export async function saveEditorState(
...
-      removeModComponentFormState(draft, id);
-    }
-  });
-
-  await saveEditorState(newState);
-}
-
-/**
- * Remove all mod components for a given mod from persisted redux storage.
+ * NOTE: this does not trigger a change event in any current redux instances because no actions are dispatched.
```
Comment (grahamlangford) [inline src/store/editorStorage.ts:68]: Had to look this up because I thought invoking the reducer directly would be enough, but per the redux source code, only the dispatch function calls the listeners. TIL

File: src/pageEditor/modListingPanel/ModListingPanel.test.tsx [hunk 11]
```diff
@@ -55,14 +87,9 @@ describe("ModListingPanel", () => {
...
 
-    await userEvent.click(
-      screen.getByRole("button", {
-        name: `${modDefinition.metadata.name} - Ellipsis`,
-      }),
-    );
+    await clickEllipsesMenu(modDefinition.metadata.name);
 
     // "Clear Changes" is disabled because there's no dirty state
-    expect(screen.getByText("Clear Changes")).toBeInTheDocument();
```
Comment (grahamlangford) [inline src/pageEditor/modListingPanel/ModListingPanel.test.tsx:65]: NIT: I know it does seem redundant, but checks like this can improve signal-to-noise when the element is missing (better error message on the failing test). If there's a not insignificant chance the option might not be visible, it might be worth leaving in

File: src/pageEditor/hooks/useClearModComponentChanges.ts (hunk 7 above)
Comment (twschiller) [reply src/pageEditor/hooks/useClearModComponentChanges.ts:85]: The same rule covers unnecessary deps. I'd generally be in favor of trying to get to `error` vs. `warning` for that rule:

image

File: src/store/editorStorage.ts (hunk 10 above)
Comment (twschiller) [reply src/store/editorStorage.ts:68]: 👍  IIRC the only magic in the slice is that it will instantiate the initial state if the reducer is passed `undefined`. Otherwise logic is all handled by the store (vs. the slice) because action behavior would be impacted by middleware

File: src/pageEditor/store/editor/editorSliceHelpers.ts [hunk 12]
```diff
@@ -122,34 +123,46 @@ export function setActiveNodeId(state: Draft<EditorState>, nodeId: UUID) {
...
+  // Remove from list mod components available on the page, if available
+  remove(state.availableDraftModComponentIds, formStateId);
 
-  const draftIndex = state.availableDraftModComponentIds.indexOf(uuid);
-  if (draftIndex > -1) {
-    // Mod component is available, remove from list of available ids
-    state.availableDraftModComponentIds.splice(draftIndex, 1);
+  if (formState) {
+    // XXX: ideally this would only mark if the form state corresponds to an activated mod component. However,
+    // there's currently not way to determine if there's an activated mod component solely from the form state.
```
Comment (grahamlangford) [inline src/pageEditor/store/editor/editorSliceHelpers.ts:156]:
```suggestion
    // there's currently no way to determine if there's an activated mod component solely from the form state.
```

Comment (grahamlangford) [reply src/pageEditor/store/editor/editorSliceHelpers.ts:156]: Also, couldn't we write this as a thunk and use getState to compare the formState to the activatedModComponents from the options slice?

Comment (grahamlangford) [reply src/pageEditor/store/editor/editorSliceHelpers.ts:156]: To be clear, I'm not suggesting we need to do that for this PR, just validating whether that comment is accurate

Comment (twschiller) [reply src/pageEditor/store/editor/editorSliceHelpers.ts:156]: > Also, couldn't we write this as a thunk and use getState to compare the formState to the activatedModComponents from the options slice?

The gotcha with createAsync thunk is that the action isn't awaitable. They're designed to have extra cases for fulfilled/rejected/pending in the slice. That's why I wasn't able to rewrite the hook business logic as async thunks
