### PR TITLE
#6362: only return unique services from getUnconfiguredComponentIntegrations

### LINKED ISSUE #6362: Integration configuration selector shows multiple times for integration used by multiple starter bricks
Steps to Reproduce
---
- Activate: `@pixies/test/integration-copies`, which has two different starter bricks with a `serpapi` integration variable
- It shows multiple activation selectors

Discussion
---
- I've shared the mod publicly so we can create a Rainforest QA test for it
- For testing, should verify activation for both extension console activation and sidebar activation (use nextUrl for activate from anywhere functionality)

Screenshot
---
image

### PR DESCRIPTION
**Pull request by grahamlangford**
## What does this PR do?

- Fixes #6362 

## Demo

https://www.loom.com/share/4dae3396a9f641f3a8b3b9738d9fecbc?sid=878bb96f-fb59-4bdf-9e74-a2730a5d5720

## Checklist

- [x] Add tests
- [x] Designate a primary reviewer @mnholtz

### CODE REVIEW

File: src/utils/modDefinitionUtils.ts [hunk 1]
```diff
@@ -75,15 +75,18 @@ function getIntegrationsFromRecord(
 export function getUnconfiguredComponentIntegrations({
   extensionPoints: modComponentDefinitions = [],
 }: Pick<ModDefinition, "extensionPoints">): IntegrationDependency[] {
-  return modComponentDefinitions.flatMap(({ services }) => {
-    if (isEmpty(services)) {
-      return [];
-    }
+  return uniqBy(
+    modComponentDefinitions.flatMap(({ services }) => {
+      if (isEmpty(services)) {
```
Comment (mnholtz) [inline src/utils/modDefinitionUtils.ts:80]: optional nit: could we rename `services` to `integrations` while we're at it?

File: src/utils/modDefinitionUtils.ts [hunk 2]
```diff
@@ -75,15 +75,18 @@ function getIntegrationsFromRecord(
 export function getUnconfiguredComponentIntegrations({
   extensionPoints: modComponentDefinitions = [],
 }: Pick<ModDefinition, "extensionPoints">): IntegrationDependency[] {
-  return modComponentDefinitions.flatMap(({ services }) => {
-    if (isEmpty(services)) {
-      return [];
-    }
+  return uniqBy(
```
Comment (grahamlangford) [inline src/utils/modDefinitionUtils.ts:78]: This solution won't work as a non-required integration that is earlier in the array will be kept instead of a later required version. Rethinking the implmentation.

File: src/utils/modDefinitionUtils.ts (hunk 1 above)
Comment (grahamlangford) [reply src/utils/modDefinitionUtils.ts:80]: It's still referred/saved as services in the schema. That's a larger change than I'm comfortable making now.

File: src/utils/registryUtils.test.ts [hunk 3]
```diff
@@ -16,7 +16,31 @@
  */
 
 import { type RegistryId } from "@/types/registryTypes";
-import { getScopeAndId } from "@/utils/registryUtils";
+import { generatePackageId, getScopeAndId } from "@/utils/registryUtils";
```
Comment (grahamlangford) [inline src/utils/registryUtils.test.ts:19]: relocated test from `modDefinitionUtils.test.ts`

File: src/utils/modDefinitionUtils.test.ts [hunk 4]
```diff
@@ -15,37 +15,169 @@
...
 import { modComponentDefinitionFactory } from "@/testUtils/factories/modDefinitionFactories";
 import extensionPointRegistry from "@/starterBricks/registry";
-import { generatePackageId } from "@/utils/registryUtils";
 import { validateOutputKey } from "@/runtime/runtimeTypes";
 import { validateRegistryId } from "@/types/helpers";
 import { SERVICE_BASE_SCHEMA } from "@/services/serviceUtils";
 
 extensionPointRegistry.lookup = jest.fn();
 
-describe("generateRecipeId", () => {
```
Comment (grahamlangford) [inline src/utils/modDefinitionUtils.test.ts:28]: relocated to `registryUtils.test.ts`

File: src/utils/modDefinitionUtils.ts (hunk 1 above)
Comment (mnholtz) [reply src/utils/modDefinitionUtils.ts:80]: Oops, you're right. Wasn't thinking about the destructuring there 🤦‍♀️

File: src/utils/modDefinitionUtils.ts [hunk 5]
```diff
@@ -75,15 +75,30 @@ function getIntegrationsFromRecord(
...
 
-    return isSchemaServicesFormat(services)
-      ? getIntegrationsFromSchema(services)
-      : getIntegrationsFromRecord(services);
-  });
+  const dedupedIntegrationDependencies = [];
+  for (const group of Object.values(groupBy(integrationDependencies, "id"))) {
+    if (group.some(({ isOptional }) => !isOptional)) {
+      dedupedIntegrationDependencies.push(
+        group.find(({ isOptional }) => !isOptional)
```
Comment (mnholtz) [inline src/utils/modDefinitionUtils.ts:94]: nit: any reason why not just assign the result of `group.find` to a constant above and use it in the if statement?

**Review by mnholtz — APPROVED** [review]
