### PR TITLE
#5603: fix lifecycle navigation bug for SPAs

### LINKED ISSUE #5603: Extension points that we're available on initial page aren't available after navigation
Context
---
- Bug introduced in: https://github.com/pixiebrix/pixiebrix-extension/milestone/92?closed=1

### PR DESCRIPTION
**Pull request by twschiller**
## What does this PR do?

- Closes #5603 
- Fixes lifecycle navigation bug where if an extension point wasn't available on initial page of SPA, then it couldn't be available after navigation

## Checklist

- [ ] Add tests
- [x] Designate a primary reviewer: @BLoe

### CODE REVIEW

File: src/contentScript/lifecycle.ts [hunk 1]
```diff
@@ -363,16 +407,24 @@ async function loadPersistedExtensionsOnce(): Promise<IExtensionPoint[]> {
...
+    // XXX: could also include _editorExtensions to handle case where user activates a mod while the page editor
+    // is open. However, that would require handling corner case where the user reactivating a mod that has dirty
+    // changes. It's not worth the complexity of handling the corner case.
     return loadPersistedExtensions();
   }
 
-  return getActiveExtensionPoints();
+  // NOTE: don't want _activeExtensionPoints, because we also want extension points that weren't active for the
+  // previous page/navigation.
+  return uniq([
```
Comment (twschiller) [inline src/contentScript/lifecycle.ts:418]: This is the bug fix

File: src/contentScript/lifecycle.ts [hunk 2]
```diff
@@ -436,28 +488,25 @@ export async function handleNavigate({
...
 
   if (extensionPoints.length > 0) {
-    _navSequence++;
-
-    const cancel = makeCancelOnNavigate();
+    const abortSignal = createNavigationAbortSignal();
 
-    await waitLoaded(cancel);
+    // Extension Points may need the pageScript to be injected to run
+    await Promise.all([injectPageScriptOnce(), waitDocumentLoad(abortSignal)]);
```
Comment (twschiller) [inline src/contentScript/lifecycle.ts:500]: 🐎
