### PR TITLE
5911 Fix FAB rendering in IFrame bug

### LINKED ISSUE #5911: FAB showing in iframes
Steps to Reproduce
---
- Visit a page that has an iframe. (I saw this on LinkedIn, I got the FAB in an ad)

Screenshot
---
image

Discussions
---
- The contentScript should check what frame it's running in before decided whether or not to render the FAB

### PR DESCRIPTION
**Pull request by turbochef**
## What does this PR do?

- Fixes #5911
- Added `isLoadedInIframe` utility

## Demo

- [Loom](https://www.loom.com/share/f19f99be64824bcfa3dfedfcefd68291?sid=2b4f158c-b7a3-4f3e-a04d-e3ca13235bb4)

## Checklist

- [x] Designate a primary reviewer: @grahamlangford

### CODE REVIEW

File: src/iframeUtils.ts [hunk 1]
```diff
@@ -0,0 +1,30 @@
...
+ * GNU Affero General Public License for more details.
+ *
+ * You should have received a copy of the GNU Affero General Public License
+ * along with this program.  If not, see <http://www.gnu.org/licenses/>.
+ */
+
+/**
+ * Returns true if this function is called within an IFrame
+ */
+
```
Comment (BLoe) [inline src/iframeUtils.ts:21]: Sorry, nit pick, but do you mind changing this to a `/**` JSDoc comment right on the export?

Comment (BLoe) [reply src/iframeUtils.ts:21]: Oh I guess this still works fine? Sorry, I thought the blank space would mess it up I guess.

**Review by BLoe — APPROVED** [review]
