### PR TITLE
#8404: fix variable path regex to not switch to text entry mode during optional chaining

### LINKED ISSUE #8241: Variable popover hides when using optional chaining
## Describe the bug

- PixieBrix supports optional chaining for `@` variables
- But the variable popover closes when you write `?` as part of the variable name

## To Reproduce

1. Create a nested variable
2. Access the nested value, e.g., `@mod.foo?.`

## Screenshots/Loom

image

## Related Issues

- https://github.com/pixiebrix/pixiebrix-extension/issues/8404: likely same root cause. The field is switching to text entry mode

### LINKED ISSUE #8404: Typing `?` for null coalescing in variable field toggles to text entry mode
## Describe the bug

- https://pixiebrix.slack.com/archives/C0436P48QHY/p1714696755028659

## To Reproduce

1. Start writing a variable name
2. Type `?` to handle a possibly undefined value

## Actual behavior

Text field changes to text entry mode

## Expected behavior

Field stays in variable entry mode

## Related Issues

- https://github.com/pixiebrix/pixiebrix-extension/issues/8241

### PR DESCRIPTION
**Pull request by twschiller**
## What does this PR do?

- Closes #8404
- Closes #8241
- Fixes variable detection logic to support optional chaining to prevent auto-switching to text entry mode

## Future Work

- Fix variable popover filtering logic to support optional chaining: https://github.com/pixiebrix/pixiebrix-extension/issues/8636

## Checklist

- [x] Add jest or playwright tests and/or storybook stories
- [x] Designate a primary reviewer: @fungairino

### CODE REVIEW

File: src/components/fields/schemaFields/widgets/TextWidget.tsx [hunk 1]
```diff
@@ -59,12 +59,12 @@ function schemaSupportsTemplates(schema: Schema): boolean {
 //   -@: Check for a @ character at the beginning of the string.
 //   -(?!\d): Ensure the first character of the identifier is not a digit.
 //   -([\w$]+): Capture the initial identifier, which can consist of letters, digits, underscores, or dollar signs.
-//   -((\.[\w$]+)|(\[(\d+|"[^"]+")\]))*: Match any number of properties or array indices, separated by periods or enclosed in square brackets.\.[\w$]+: A property preceded by a period, consisting of letters, digits, underscores, or dollar signs.
+//   -((\??\.[\w$]+)|(\[(\d+|"[^"]+")\]))*: Match any number of properties or array indices, separated by periods or enclosed in square brackets.\.[\w$]+: A property preceded by a period, consisting of letters, digits, underscores, or dollar signs.
```
Comment (BLoe) [inline src/components/fields/schemaFields/widgets/TextWidget.tsx:62]: The second sentence in this comment is referring to the place in the regex where this change was made, can we update the comment to reflect the change and add a bit about "or preceded by a question mark and period" or something like that?

File: src/components/fields/schemaFields/widgets/TextWidget.test.tsx [hunk 2]
```diff
@@ -87,12 +87,15 @@ describe("TextWidget", () => {
...
     expect(isVarValue("@example.property.nestedProperty")).toBe(true);
+    expect(isVarValue("@myObject.optionalProperty?.bar")).toBe(true);
+    expect(isVarValue("@myOptionalObject?.bar")).toBe(true);
 
     // Invalid strings:
     expect(isVarValue("abc")).toBe(false);
     expect(isVarValue("@property extra text")).toBe(false);
     expect(isVarValue("@123")).toBe(false);
     expect(isVarValue("@")).toBe(false);
+    expect(isVarValue("@myObject.optionalProperty?")).toBe(false);
```
Comment (fungairino) [inline src/components/fields/schemaFields/widgets/TextWidget.test.tsx:98]: would recommend adding a check for something like "?" and "?@abc"

**Review by fungairino — APPROVED** [review]
