### PR TITLE
#4028: handle missing service definition

### LINKED ISSUE #4028: `DoesNotExistError` on load for `automation-anywhere/oauth2`
I'm not sure if I'm doing anything wrong, but I'm seeing this error on page load, content script. Will extend the ticket if I know more.

```
Uncaught (in promise) DoesNotExistError: Registry item does not exist: automation-anywhere/oauth2
    at Registry.lookup (chrome-extension://mpjjildhmpddojocokjkgmlkkkfjnepo/background.js:76176:19)
    at async LazyLocatorFactory.locateAllForService (chrome-extension://mpjjildhmpddojocokjkgmlkkkfjnepo/background.js:88115:25)
    at async Promise.all (/index 0)
    at async Object.getPartnerPrincipals (chrome-extension://mpjjildhmpddojocokjkgmlkkkfjnepo/background.js:75165:70)
    at async handleMessage (chrome-extension://mpjjildhmpddojocokjkgmlkkkfjnepo/background.js:118954:22)
```

### PR DESCRIPTION
**Pull request by twschiller**
## What does this PR do?

- Closes #4028 
- Handles missing `automation-anywhere/oauth2` definition which is not publicly available on prod yet

## Discussion
- I didn't need to change useRequiredPartnerAuth because it loops over all services, https://github.com/pixiebrix/pixiebrix-extension/blob/2a808ea401e2a0f8a38f6702489f57488e4a0e31/src/auth/useRequiredPartnerAuth.ts#L100-L100

## Checklist

- 😢  Add tests
- [X] Designate a primary reviewer: @mnholtz

### CODE REVIEW

File: src/background/partnerIntegrations.ts [hunk 1]
```diff
@@ -53,7 +53,15 @@ export async function getPartnerPrincipals(): Promise<PartnerPrincipal[]> {
 
   const auths = flatten(
     await Promise.all(
-      partnerIds.map(async (id) => serviceLocator.locateAllForService(id))
+      partnerIds.map(async (id) => {
+        try {
+          return await serviceLocator.locateAllForService(id);
```
Comment (fregante) [inline src/background/partnerIntegrations.ts:58]: In cases like these if prefer using a .catch instead, it's much shorter, even if the linter complains:

```js 
.map(async (id) => locate(id).catch(() => []))
```
