### PR TITLE
#8494 Fix sidebar mod activation flows that involve user onboarding

### LINKED ISSUE #8494: Installing Extension after activating a marketplace mod - mod never activates
## Describe the bug

If you attempt to activate a mod without the Extension installed, the mod never activates once you've installed the MV3 Extension

## To Reproduce

1. Delete the Extension from your Chrome profile
2. Make sure you're logged into the app
3. Navigate to the marketplace and activate any mod
4. Wait for the Extension listing in CWS to load
5. Navigate to the PixieBrix BETA listing (or load unpacked)
6. Install the MV3 version of the Extension
7. Wait to be redirected to the marketplace listing
8. click `Show Sidebar` on the focusCaptureDialog

## Actual behavior

- Sidebar is stuck in the loading state

## Expected behavior

- The mod activation panel shows the "Well done" message

### Using the BETA list (1.8.14)

https://www.loom.com/share/1e20f39a655b4d759a8a22f9f1c1206c

### Using the BETA list (2.0.0-beta.1)

https://www.loom.com/share/746ca5a1af3841bd959754db61562b8c

### Using `main`

https://www.loom.com/share/c9f1abf24d8849a09325835aba6fa337

## Desktop (please complete the following information):

- Extension Version: 1.8.14-mv3

### PR DESCRIPTION
**Pull request by BLoe**
## What does this PR do?

- Closes #8494 

## Demo

https://www.loom.com/share/bf179871da064172b8d37f73aad7d3e7

## Checklist

- [ ] Add jest or playwright tests and/or storybook stories
- [x] Designate a primary reviewer - @grahamlangford

### CODE REVIEW

**Review by grahamlangford — APPROVED** [review]

**Review by twschiller — APPROVED** [review]

File: src/contentScript/sidebarActivation.ts [hunk 1]
```diff
@@ -101,25 +101,26 @@ function addActivateModsListener(): void {
 export async function initSidebarActivation(): Promise<void> {
   addActivateModsListener();
 
-  if (!(await isLinked())) {
+  if (
+    // Do not attempt sidebar activation if the extension is not linked
+    !(await isLinked()) ||
+    // Do not show sidebar activation on hidden tabs/windows
+    document.hidden ||
```
Comment (twschiller) [inline src/contentScript/sidebarActivation.ts:108]: NIT: you could add that occurs if background injects into existing tabs on startup

**Comment by twschiller** [comment]
For future people reading this PR - this PR prevents showing activation modal on existing inactive tabs that PixieBrix injects the content script into on install/startup
