### PR TITLE
#4441: Stop inspecting after dev tool is closed

### LINKED ISSUE #4441: Selection tool stays open after closing dev tools
Steps to Reproduce
---
- Open selection tool
- Set to multi selection mode
- Select 1 or more elements
- Close the dev tools

Expected Behavior:
- The page is not in selection mode

Actual Behavior
- The selection mode toolbox still shows. And the page is still in selection mode

### PR DESCRIPTION
**Pull request by jcforest**
## What does this PR do?

- Closes #4441 

## Reviewer Tips

- we're using `beforeunload` event listener to catch dev tool closing event.

### CODE REVIEW

File: src/contentScript/nativeEditor/elementPicker.ts [hunk 1]
```diff
@@ -51,6 +52,12 @@ export function hideOverlay(): void {
   }
 }
 
+export function stopInspectingNativeHandler(): void {
+  if (stopInspectingNative) {
+    stopInspectingNative();
+  }
```
Comment (fregante) [inline src/contentScript/nativeEditor/elementPicker.ts:58]:
```suggestion
  stopInspectingNative?.();
```

**Review by fregante — APPROVED** [review]
This works for me. The only exceptions :

- when the page editor crashes: `beforeunload` isn't dispatched
- the extension is reloaded: messaging stops working

The latter I think can be fixed by using `onContextInvalidated` somewhere in the `elementPicker.ts`, but not strictly necessary.
