### PR TITLE
#1458: Fixing required field

### LINKED ISSUE #1458: Fix "required" toggle in Form Builder

### PR DESCRIPTION
**Pull request by BALEHOK**
Fixes #1458 
Updates `required` array on renaming a property.
Unit tests.

### CODE REVIEW

**Comment by BLoe** [comment]
@BALEHOK I mentioned this to you in Slack, but commenting here just in case so we don't forget. The required list needs to be updated on property name change, in the case where a required field name was changed.

File: src/components/formBuilder/FieldEditor.tsx [hunk 1]
```diff
@@ -184,6 +194,30 @@ const FieldEditor: React.FC<{
...
+    const nextRjsfSchema = produce(rjsfSchema, (draft) => {
+      if (!draft.schema.required) {
+        draft.schema.required = [];
+      }
+
+      if (nextIsRequired) {
+        draft.schema.required.push(propertyName);
+        draft.schema.required = uniq(draft.schema.required);
+      } else {
+        draft.schema.required = replaceStringInArray(
```
Comment (twschiller) [inline src/components/formBuilder/FieldEditor.tsx:209]: Mentioned this in a previous PR review, but will mention again. The signature of replaceStringInArray is really not intuitive, that by passing "property" name here and leaving off an argument that it would cause the property to be removed

I had to look at the implementation of the method to see whether or not this was correct usage

**Review by BLoe — APPROVED** [review]
