### PR TITLE
#8962: scope label width CSS to fix visual regression

### LINKED ISSUE #8962: Visual regression on Form Builder Preview label width
## To Reproduce

1. Add a sidebar starter brick
2. Add an embedded form
3. Open the Design Tab

## Actual behavior

image

## Desktop (please complete the following information):

- Extension Version: 2.0.7-alpha.4

### PR DESCRIPTION
**Pull request by twschiller**
## What does this PR do?

- Closes #8962

## Demo

image

image

For more information on our expectations for the PR process, see the
[code review principles doc](https://www.notion.so/pixiebrix/Code-Review-Principles-1ce7276b82a84d2a995d55ad85e1310d?pvs=4)

### CODE REVIEW

File: src/components/jsonTree/JsonTree.tsx [hunk 1]
```diff
@@ -97,6 +97,11 @@ export type JsonTreeProps = JsonTreeOrigProps & {
    * Change listener for the expanded state
    */
   onExpandedStateChange?: (nextExpandedState: TreeExpandedState) => void;
+
```
Comment (twschiller) [inline src/components/jsonTree/JsonTree.tsx:100]: Modify JsonTree to accept className

File: src/pageEditor/tabs/editTab/dataPanel/DataTabJsonTree.tsx [hunk 2]
```diff
@@ -75,6 +80,7 @@ const DataTabJsonTree: React.FunctionComponent<DataTabJsonTreeProps> = ({
   return (
     <JsonTree
       {...jsonTreeProps}
+      className={cx(jsonTreeProps.className, styles.dataTabRoot)}
```
Comment (twschiller) [inline src/pageEditor/tabs/editTab/dataPanel/DataTabJsonTree.tsx:83]: Passed in here

File: src/pageEditor/tabs/editTab/dataPanel/tabs/ViewModeField.module.scss [hunk 3]
```diff
@@ -33,5 +35,13 @@
     align-content: center;
   }
 
+  :global {
```
Comment (twschiller) [inline src/pageEditor/tabs/editTab/dataPanel/tabs/ViewModeField.module.scss:38]: And passed in via the existing style

**Review by grahamlangford — APPROVED** [review]
