### PR TITLE
#3231 Don't save removed extensions in blueprints

### LINKED ISSUE #3231: Bug: Deleted extensions aren't actually removed from a blueprint on save
Some recent changes to how deleted extensions are handled in the redux state wasn't accounted for in the save logic, so removed extensions are still being saved on the blueprints.

Steps to reproduce:
* in page editor, activate or create a blueprint with two extensions
* remove one
* save the blueprint
* reload page editor or check the blueprint in the workshop
Expected:
* the blueprint only has one extension
Actual
* the blueprint still has both extensions

### PR DESCRIPTION
**Pull request by BLoe**
Fixes #3231

### CODE REVIEW

File: src/pageEditor/panes/save/useRecipeSaver.ts [hunk 1]
```diff
@@ -73,14 +73,21 @@ function useRecipeSaver(): RecipeSaver {
...
+    // eslint-disable-next-line security/detect-object-injection -- recipeId
+    const deletedElements = deletedElementsByRecipeId[recipeId] ?? [];
+    const deletedElementIds = new Set(deletedElements.map(({ uuid }) => uuid));
+
     const dirtyRecipeElements = editorFormElements.filter(
       (element) =>
-        element.recipe?.id === recipeId && isDirtyByElementId[element.uuid]
+        element.recipe?.id === recipeId &&
+        isDirtyByElementId[element.uuid] &&
+        !deletedElementIds.has(element.uuid)
```
Comment (twschiller) [inline src/pageEditor/panes/save/useRecipeSaver.ts:84]: @BLoe could you add comments in the code why the the new conditions are necessary?

**Review by twschiller — APPROVED** [review]
