### PR TITLE
#8553: fix mod saving invariant checks in Page Editor

### LINKED ISSUE #8553: Data error saving mod
## Describe the bug

- https://pixiebrix.slack.com/archives/C0436P48QHY/p1717553792057509

## To Reproduce

See Slack thread for diagnostics export

1. Activate: `@pixies/ai/chatgpt-sidebar`
2. Make a change
3. Try to click to save

## Actual behavior

Page Editor shows data error

## Expected behavior

Mod is saved

## Desktop (please complete the following information):

- Extension Version: v2.0.2-beta.1

### PR DESCRIPTION
**Pull request by grahamlangford**
## What does this PR do?

- Fixes #8553 

## Reviewer Tips

- As of #8533, we're deleting excess StarterBricks when we package the mod
- We then compare the built mod to the activatedModComponents in our invariant checks
- This was causing the invariant check to throw because the activatedModComponents still had the excess starter bricks

## Discussion

- ~The current solution doesn't work if you delete/move a mod component out of the mod~
- It might be better to delete the excess starter bricks upstream (potentially when we activate the mod?)
- Likely also an issue with dirtyModComponentFormStates

## Remaining Work

- [x] Clean mod components fix works when deleting/moving a mod component out of the mod
- [x] Validate/fix invariant check for dirtyModComponentFormStates
- [x] Refactor

## Demo

https://www.loom.com/share/5a26efcc24d042b1bc3344012ba4c18d

## Checklist

- [ ] Add jest or playwright tests and/or storybook stories
- [ ] Designate a primary reviewer

### CODE REVIEW

**Comment by grahamlangford** [comment]
> @grahamlangford where is the check failing? Is it in useCheckModStarterBrickInvariants?
> 
> Conceptually, would it also work to add the additional normalization in useCheckModStarterBrickInvariants? Or is there a specific reason to include it in the selector?

It can be moved out of the selector. I was working in the selector because I wasn't sure what I needed from state. Moving it out makes sense to do as part of the selector

> > The current solution doesn't work if you delete/move a mod component out of the mod
> 
> Could you clarify what "current" is referring to? Is it referring to `main`? Or the code in this PR?

That was true before the latest commit. Adding the `removed` state and `selectIsModComponentRemovedById` resolved that problem. I just forgot to update that discussion point

File: src/pageEditor/slices/editorSlice.ts [hunk 1]
```diff
@@ -607,6 +608,7 @@ export const editorSlice = createSlice({
       // eslint-disable-next-line @typescript-eslint/no-non-null-assertion, @typescript-eslint/no-unnecessary-type-assertion -- nullish assignment above
       state.deletedElementsByRecipeId[recipeId]!.push(element);
       state.elements.splice(elementIndex, 1);
+      state.removed[elementId] = true;
       delete state.dirty[elementId];
```
Comment (grahamlangford) [inline src/pageEditor/slices/editorSlice.ts:612]: Added `removed` because we delete `elementId` from `state.dirty` here. We could simplify by removing the `delete`, but I'm not confident that that wouldn't impact code elsewhere

Comment (grahamlangford) [reply src/pageEditor/slices/editorSlice.ts:612]: The contents of `state.dirty` is what's returned by `deletedElementsByRecipeId`

**Review by BLoe — APPROVED** [review]
