### PR TITLE
#5079 Add support for @element and body keys in analysis of subpipelines

### LINKED ISSUE #5079: Add support for `@element` and body keys in analysis of subpipelines
Context
---
- Steps to reproduce: use the for-each brick. Likely also a problem with the try-except brick

image

### PR DESCRIPTION
**Pull request by BALEHOK**
## What does this PR do?

- Fixes #5079 

## Demo
- For-each before run:
Screenshot 2023-01-26 at 11 21 23

- Try-except inside for-each before run:
Screenshot 2023-01-26 at 11 22 29

- After run (with trace):
Screenshot 2023-01-26 at 11 23 45

## Checklist

- [ ] Add tests
- [x] Designate a primary reviewer @twschiller

### CODE REVIEW

File: src/analysis/analysisVisitors/varAnalysis/varAnalysis.ts [hunk 1]
```diff
@@ -415,10 +415,11 @@ class VarAnalysis extends PipelineExpressionVisitor implements Analysis {
     if (subPipelineInput) {
       subPipelineVars = new VarMap();
       subPipelineVars.setOutputKeyExistence({
-        source: position.path,
+        // The source of the element key is the parent block
```
Comment (twschiller) [inline src/analysis/analysisVisitors/varAnalysis/varAnalysis.ts:418]: Could we add a test case for this?

**Review by twschiller — APPROVED** [review]
