### PR TITLE
#7467: Add support for sidebar forms brick in MV3

### LINKED ISSUE #7467: Error showing form in sidebar in MV3
## Describe the bug

Error when showing form in sidebar

> Error getting information for form: This target is not in a frame

## To Reproduce

1. Add Quick Bar Item Starter Brick
2. Add Show Sidebar Brick
3. Add Show a Modal or Sidebar Item brick
   - Target: sidebar

## Actual behavior

An error is shown:

image

## Expected behavior

Form shows

## Desktop (please complete the following information):

Main: f0607dfc0062781e7fbd2035f65cc2197500b9e9

### PR DESCRIPTION
**Pull request by fregante**
## What does this PR do?

- Fixes #7467

## Demo

Not in the demo, but I also verified that the modal still works.

https://github.com/pixiebrix/pixiebrix-extension/assets/1402241/aa5b62a1-b4f7-4407-8763-e95a3b09bb89

## Checklist

- [x] Designate a primary reviewer: @grahamlangford

### CODE REVIEW

File: src/sidebar/sidebar.tsx [hunk 1]
```diff
@@ -22,6 +22,7 @@ import "@/utils/layout.scss";
 import "./sidebar.scss";
 
 import "@/extensionContext";
+import "@/development/darkMode.js";
```
Comment (grahamlangford) [inline src/sidebar/sidebar.tsx:25]: Was this intentional? I wasn't aware we had any darkmode support.

**Review by grahamlangford — APPROVED** [review]

File: src/sidebar/sidebar.tsx (hunk 1 above)
Comment (fregante) [reply src/sidebar/sidebar.tsx:25]: Yes I forgot to mention its addition here. 

We have an opt-in dev-only dark mode enabled in the page editor, options and now the sidebar.

Call this function on the options page's dev tools: `pbToggleDark()` and then set your system color theme to dark too.
