### PR TITLE
#4190: Fix content script readiness race conditions and context invalidation handling

### LINKED ISSUE #4190: Content script remains "ready" even after unloading
My logic might have been incorrect in:

- https://github.com/pixiebrix/pixiebrix-extension/pull/3915

See:

https://github.com/pixiebrix/pixiebrix-extension/blob/e6644547df7a73dca2fe9600b18a2423e0fa2ce2/src/contentScript/ready.ts#L18-L32

## Related

- https://github.com/pixiebrix/pixiebrix-extension/issues/4189

In the situation described by that issue, our logic trips trips on the "ready" attribute  and reports the content script as "ready" even if the new one hasn't been injected.

## Solution

```js
onContextInvalidated().then(() => {
  if body[READY_ATTRIBUTE] === currentUuid
    removeAttribute(body, READY_ATTRIBUTE) 
})
```

### PR DESCRIPTION
**Pull request by fregante**
Still WIP

## What does this PR do?

- Closes #4190

- [x] Mark document as "not ready" when the context is invalidated
- [ ] Unload kbar on invalidation?
- [x] Also ensure that consecutive `ensureContentScript` calls resolve at the same time, potentially via `pMemoize(fn, {cache: false})`

## Checklist

- [ ] Test
- [x] Designate a primary reviewer: @BLoe

### CODE REVIEW

File: src/contentScript/contentScript.ts [hunk 1]
```diff
@@ -49,12 +51,22 @@ async function initContentScript() {
...
+
+  const { init } = await contentScript;
   await init(uuid);
   setReadyInThisDocument(uuid);
+
+  // eslint-disable-next-line promise/prefer-await-to-then -- It's an unrelated event listener
+  void onContextInvalidated().then(() => {
+    unsetReadyInThisDocument(uuid);
+    console.debug("contentScript: invalidated", uuid);
+  });
```
Comment (fregante) [inline src/contentScript/contentScript.ts:69]: Part 1: 

- revert https://github.com/pixiebrix/pixiebrix-extension/pull/4061

File: src/errors/contextInvalidated.ts [hunk 2]
```diff
@@ -30,7 +29,11 @@ const id = "connection-lost";
  * Display a notification when the background page unloads/reloads because at this point
  * all communcation becomes impossible.
  */
-export function notifyContextInvalidated(): void {
+export async function notifyContextInvalidated(): Promise<void> {
+  // `import()` is only needed to avoid execution of its dependencies, not to lazy-load it
+  // https://github.com/pixiebrix/pixiebrix-extension/issues/4058#issuecomment-1217391772
+  // eslint-disable-next-line import/dynamic-import-chunkname
+  const { notify } = await import(/* webpackMode: "eager" */ "@/utils/notify");
```
Comment (fregante) [inline src/errors/contextInvalidated.ts:36]: Part 2:

- fix the issue closer to the cause

Part 3, in the future:

- [ ] https://github.com/pixiebrix/webext-messenger/issues/88

**Review by BLoe — APPROVED** [review]
