### PR TITLE
#1537: fix context menu runtime bugs

### LINKED ISSUE #1537: One-time error when using context menu from page editor
- [ ] Default context to "all" if not provided
- [ ] First time running context menu there's a message about the handler not returning in 1000 second

### PR DESCRIPTION
**Pull request by twschiller**
Closes #1537 

I created https://github.com/pixiebrix/pixiebrix-extension/issues/1542 for cleanup, which will require fixing the webext-messenger dependency

### CODE REVIEW

File: src/background/initContextMenus.ts [hunk 1]
```diff
@@ -21,41 +21,85 @@ import {
...
 } from "@/extensionPoints/contextMenu";
-import { reportError } from "@/telemetry/logging";
 import { loadOptions } from "@/options/loader";
 import { IExtension, ResolvedExtension } from "@/core";
 import { resolveDefinitions } from "@/registry/internal";
 import { allSettledValues } from "@/utils";
+import { expectContext } from "@/utils/expectContext";
+import { isDeploymentActive } from "@/options/deploymentUtils";
+import { compact, uniq } from "lodash";
+// NOTE: Call the method directly, don't go through the messenger API
```
Comment (fregante) [inline src/background/initContextMenus.ts:31]: This comment should not be necessary, `ensureContextMenu` is just a regular function on its own. The messenger API wouldn't work at all: https://github.com/pixiebrix/webext-messenger/issues/26
