### PR TITLE
#2992: fix blueprint update and reactivate

### LINKED ISSUE #2992: Re-activate button not showing for blueprints
Context
- https://pixiebrix.slack.com/archives/C02CN01JXAA/p1647912559656039?thread_ts=1647908111.709559&cid=C02CN01JXAA
- Might be when you're on the latest version of the blueprint, you can't reactivate?

### PR DESCRIPTION
**Pull request by mnholtz**
This fixes #2992, which is actually not a problem of missing reactivate, but missing update:
1. fixes the "update" action not showing on blueprints in the blueprints page
2. hides "reactivate" ellipsis menu action for inactive blueprints

### CODE REVIEW

File: src/options/pages/blueprints/BlueprintActions.tsx [hunk 1]
```diff
@@ -88,7 +88,10 @@ const BlueprintActions: React.FunctionComponent<{
         ),
         action: actions.reinstall,
         // Managed extensions are updated via the deployment banner
-        hide: !actions.reinstall || sharing.source.type === "Deployment",
+        hide:
+          actions.reinstall === null ||
```
Comment (twschiller) [inline src/options/pages/blueprints/BlueprintActions.tsx:92]: Should this be `== null`? In general we never be using `===` for null/undefined

**Review by twschiller — APPROVED** [review]
@mnholtz just had one question on the PR

**Review by twschiller — APPROVED** [review]
