### PR TITLE
#8220 Ensure sandbox iframe is present in DOM

### LINKED ISSUE #8220: RENDER_NUNJUCKS not available within 3 seconds
## Describe the bug

- RENDER_NUNJUCKS not available within 3 seconds

## To Reproduce

The error is intermittent. What @brittanyjoiner15 is seeing is most likely that either: 1) a selection watch trigger is failing, or 2) a page load trigger (e.g., to fetch announcements) is failing on some pages

Likely steps to reproduce:
- Add a page load trigger with no debounce
- Configure the trigger to show an error on failure
- Add a brick that uses a nunjucks template. E.g., the identity brick with `{{ @input.url }}`
- Browse the web and wait for the error to pop up

## Actual behavior

- A mod fails with error "RENDER_NUNJUCKS not available within 3 seconds"
- Behavior depends on what the triggers error handler is set to (i.e., whether or not an error toast will be shown)

## Discussion

- RENDER_NUNJUCKS is handled by the sandbox injected into the page: https://github.com/pixiebrix/pixiebrix-extension/blob/6e2f02e1d6f2c6fa8bf8f96be25278bc4586bbe5/src/sandbox/messenger/api.ts#L62-L62
- In MV3, all nunjucks evaluation is run via the Sandbox. (In MV2, you have to toggle it on. Javascript brick is always run in the sandbox though)
- To diagnose the error, you need to figure out whether that error would be thrown if:
  - Is the sandbox not getting added to the page properly? Or,
  - Is the sandbox added, but then getting removed?
  - Is the sandbox on the page, but it's not responding in time (e.g., b/c it's processing another message)?

## Potential Solution

- Add automatic retries when renderNunjucks fails
- Advice users to refresh the page if renderNunjucks fails 4 times
- Similar to: https://github.com/pixiebrix/pixiebrix-extension/pull/8474

### PR DESCRIPTION
**Pull request by mnholtz**
## What does this PR do?

- Closes #8220
- Ensures the sandbox iframe is re-injected into the DOM before it needs to be used by the runtime if the host page removes it for any reason

## Demo

https://www.loom.com/share/11ab9999039a43d19cb0e5784ade0746

## Checklist

- [x] Added jest or playwright tests and/or storybook stories -- possibly left for future work

For more information on our expectations for the PR process, see the
[code review principles doc](https://www.notion.so/pixiebrix/Code-Review-Principles-1ce7276b82a84d2a995d55ad85e1310d?pvs=4)

### CODE REVIEW

File: src/sandbox/messenger/api.ts [hunk 1]
```diff
@@ -19,16 +19,40 @@
...
+);
+
+const getSandbox = memoizeUntilSettled(async () => {
+  let sandbox = await loadSandbox();
+  const shadowRoot = document.documentElement.querySelector(
+    `#${SANDBOX_SHADOW_ROOT_ID}`,
+  )?.shadowRoot;
+  const isSandboxInDom = shadowRoot?.contains(sandbox);
+
+  if (isSandboxInDom) {
```
Comment (mnholtz) [inline src/sandbox/messenger/api.ts:43]: Need to fix `isSandboxInDom` because it's always false for some reason

**Comment by twschiller** [comment]
@mnholtz - perhaps not for this PR, but if PixieBrix needs to re-inject more than once, would be good to collect telemetry on the problematic sites

File: src/sandbox/messenger/api.ts (hunk 1 above)
Comment (grahamlangford) [reply src/sandbox/messenger/api.ts:43]: Why do we run loadSandbox before checking if it's already injected?

**Comment by mnholtz** [comment]
> not for this PR, but if PixieBrix needs to re-inject more than once (i.e., the site repeatedly removes the sandbox), would be good to collect telemetry on the problematic site

@twschiller definitely was something that came to my mind while working on this!

File: src/sandbox/messenger/api.ts (hunk 1 above)
Comment (mnholtz) [reply src/sandbox/messenger/api.ts:43]: loadSandbox will also return the memoized reference to the iframe (i'm using it to 1) get a reference to the iframe and 2) ensure the iframe is fully loaded before attempting to ping it). I suppose we could try selecting it instead via querySelector? Any thoughts?

Comment (mnholtz) [reply src/sandbox/messenger/api.ts:43]: It's actually a little tricky to select the iframe since the shadow root is closed. That's another reason why it's nice to get a reference to it with `loadSandbox`

File: src/utils/postMessage.ts [hunk 2]
```diff
@@ -37,9 +37,9 @@ import { assertNotNullish } from "./nullishUtils";
 import { type JsonValue } from "type-fest";
 import { type AbortSignalAsOptions } from "./promiseUtils";
 
-const TIMEOUT_MS = 3000;
+const TIMEOUT_MS = 1000;
```
Comment (mnholtz) [inline src/utils/postMessage.ts:40]: Reducing to 1s since we are adding 3 retries to postMessage in api.ts

File: src/sandbox/messenger/api.ts [hunk 3]
```diff
@@ -18,19 +18,77 @@
...
+  } else {
+    console.warn("Sandbox iframe was removed from the DOM. Reinjecting...");
+    pMemoizeClear(loadSandbox);
+    sandbox = await loadSandbox();
+  }
+
+  return sandbox.contentWindow;
 });
 
+async function postSandboxMessage<TReturn extends Payload = Payload>({
```
Comment (mnholtz) [inline src/sandbox/messenger/api.ts:58]: Added retries here to make the approach extra water-tight

**Review by grahamlangford — APPROVED** [review]
