### PR TITLE
#9376: fix options args focus/active subtab resetting

### LINKED ISSUE #7148: Mod Current Inputs fields lose focus while typing
## Describe the bug

- While typing into fields on the Mod Current Inputs form, the fields lose focus
- Seems to be new in 1.8.5
- Seems to only occur with fields that have not been saved

## To Reproduce

1. Add a text mod option
2. On the Mod Current Input form
3. Start typing in the text field

## Actual behavior

Field loses focus while typing

## Expected behavior

Field does not lose focus while typing

## Screenshots/Loom

If applicable, add screenshots/looms to help explain your problem.

## Desktop (please complete the following information):

- 1.8.5
- Bug does not seem to exist in 1.8.4

## Discussion

- The field is most likely being remounted while typing

### LINKED ISSUE #9376: Mod Configuration Sub Tab resetting to Metadata tab on change
Context
---
- https://github.com/pixiebrix/pixiebrix-extension/issues/9374#issuecomment-2442952638

### PR DESCRIPTION
**Pull request by twschiller**
## What does this PR do?

- Closes #9376: the root cause was the mod editor pane including the form sequence number in its key
- Closes #7148: the root cause was the editorSlice selector returning a fresh options definition object

## Remaining Work

- [x] Add Playwright test covering the regression and the fix for keeping field focus

## Future Work

- :bug: Mod Options Args are buggy: https://github.com/pixiebrix/pixiebrix-extension/issues/9378
- Finish making selector naming and calling conventions consistent

For more information on our expectations for the PR process, see the
[code review principles doc](https://www.notion.so/pixiebrix/Code-Review-Principles-1ce7276b82a84d2a995d55ad85e1310d?pvs=4)

### CODE REVIEW

File: src/pageEditor/panes/ModEditorPane.tsx [hunk 1]
```diff
@@ -75,21 +64,14 @@ const ModEditorPane: React.VFC = () => {
...
-      </Centered>
-    );
-  }
-
   return (
+    // Only need to remount on activeModId change because the sub-tabs mount/unmount on selection and there's
+    // no Redux actions that'd update the values while the forms are mounted
     <div className={styles.root} data-testid="modEditorPane">
-      <EditorTabLayout key={layoutKey} tabs={tabItems} />
+      <EditorTabLayout key={activeModId} tabs={tabItems} />
```
Comment (twschiller) [inline src/pageEditor/panes/ModEditorPane.tsx:74]: Part of the regression fix for the selected tab resetting back to the metadata tab

File: src/pageEditor/store/editor/editorSelectors/editorModSelectors.ts [hunk 2]
```diff
@@ -107,26 +107,27 @@ export const selectDirtyMetadataForModId =
...
-const dirtyOptionsDefinitionsForModIdSelector = createSelector(
+const selectGetDirtyOptionsDefinitionsForModId = createSelector(
   selectDirtyModOptionsDefinitions,
-  (_state: EditorRootState, modId: RegistryId) => modId,
-  (dirtyOptionsDefinitionsByModId, modId) => {
-    // eslint-disable-next-line security/detect-object-injection -- RegistryId for mod
-    const options = dirtyOptionsDefinitionsByModId[modId];
+  (dirtyOptionsDefinitionsByModId) =>
+    // Memoize because normalizeModOptionsDefinition returns a fresh object reference
+    memoize((modId: RegistryId) => {
```
Comment (twschiller) [inline src/pageEditor/store/editor/editorSelectors/editorModSelectors.ts:114]: Fix for the options args fields losing focus

File: src/pageEditor/tabs/modOptionsArgs/ModOptionsArgsEditor.tsx [hunk 3]
```diff
@@ -54,55 +62,58 @@ const NoModOptions: React.FC = () => (
   <div>This mod does not require any configuration</div>
 );
 
+function useOptionsFieldGroupQuery(modId: RegistryId) {
```
Comment (twschiller) [inline src/pageEditor/tabs/modOptionsArgs/ModOptionsArgsEditor.tsx:65]: Extract out and use useDeriveAsyncState for clarity

File: src/pageEditor/tabs/modOptionsArgs/ModOptionsArgsEditor.tsx [hunk 4]
```diff
@@ -123,51 +134,51 @@ const ModOptionsArgsContent: React.FC = () => {
...
-        renderBody={renderBody}
-        onSubmit={() => {
-          console.error(
-            "The form's submit should not be called to save mod option values, they are automatically synced with redux",
-          );
-        }}
-        renderSubmit={() => null}
-      />
-    </ErrorBoundary>
+    <AsyncStateGate state={fieldGroupQuery}>
```
Comment (twschiller) [inline src/pageEditor/tabs/modOptionsArgs/ModOptionsArgsEditor.tsx:157]: Use standard AsyncStateGate

File: src/pageEditor/tabs/modOptionsArgs/ModOptionsArgsEditor.tsx [hunk 5]
```diff
@@ -123,51 +134,51 @@ const ModOptionsArgsContent: React.FC = () => {
...
+
+    return renderBody;
+  };
 
   return (
-    <ErrorBoundary>
-      <Form
-        validationSchema={validationSchema}
-        initialValues={initialValues}
-        enableReinitialize
```
Comment (twschiller) [inline src/pageEditor/tabs/modOptionsArgs/ModOptionsArgsEditor.tsx:155]: Removed `enableReinitialize` because the form only needs a 1 way sync because the Page Editor won't/can't update the args via Redux while hte form is open

File: src/components/tabLayout/EditorTabLayout.tsx [hunk 6]
```diff
@@ -64,7 +63,7 @@ const EditorTabLayout: React.FC<{
           className={styles.nav}
         >
           {tabs.map(({ name, badgeCount, badgeVariant }) => (
-            <Nav.Item key={`nav-tab-${name}`} className={styles.navItem}>
+            <Nav.Item key={name} className={styles.navItem}>
```
Comment (twschiller) [inline src/components/tabLayout/EditorTabLayout.tsx:66]: The `nav-tab` prefix has no effect

File: src/components/tabLayout/EditorTabLayout.tsx [hunk 7]
```diff
@@ -109,14 +105,15 @@ const EditorTabLayout: React.FC<{
...
         <Tab.Content className={styles.content}>
-          {tabs.map(({ name, TabContent, mountWhenActive }) => (
+          {tabs.map(({ name, TabContent }) => (
             <Tab.Pane
               key={name}
               eventKey={name}
-              mountOnEnter={mountWhenActive}
-              unmountOnExit={mountWhenActive}
+              // Simplify form state handling by only mounting when active
+              mountOnEnter
```
Comment (twschiller) [inline src/components/tabLayout/EditorTabLayout.tsx:113]: Remount the panes/forms when their tab becomes selected to simplify handling of initial form states

**Review by grahamlangford — APPROVED** [review]
