### PR TITLE
#9355: fix dirty flag on Formik reinitialization regression

### LINKED ISSUE #9355: Mod component shows as unsaved/dirty after clearing changes
## Describe the bug

- Mod component shows as unsaved/dirty after clearing changes
- Discussion: https://pixiebrix.slack.com/archives/C0436P48QHY/p1729879942759189

## To Reproduce

Steps to Reproduce:
1. For an activated mod
1. Change the name of a mod component in the Page Editor
2. Click Clear Changes for the mod component

## Actual behavior

The changes are cleared in the form state, but the component still shows a red disk icon

## Expected behavior

The component does not show a red disk icon

## Discussion

- From the UI it looks like the mod component might be getting correctly set at clean and then getting marked as dirty
  - If you click Clear Changes on the mod and then click into the mod components, they also get marked as dirty. So I suspect for these mods there’s some `useEffect` normalization causing them to become dirty
- If the editor is performing `useEffects` to normalize the state this is potentially the "correct" behavior in that the brick is being modified (although non-functionally) when the user clicks into it

## Desktop (please complete the following information):

- Extension Version: 2.1.6-beta.1

## Related Code

- https://github.com/pixiebrix/pixiebrix-extension/blob/e092de96b6bac94f96724e3a46e1dda306fcd3a8/src/pageEditor/hooks/useClearModComponentChanges.ts#L77-L77

### PR DESCRIPTION
**Pull request by twschiller**
## What does this PR do?

- Fixes #9355
- Regression from https://github.com/pixiebrix/pixiebrix-extension/pull/9351

## Discussion

- Our `redux-logger` middleware has an option for seeing the diff on each action: https://www.npmjs.com/package/redux-logger#options (You can use to quickly see where it's being set back to `dirty: true`

## Remaining Work

- [x] Fix playwright test: for discussion - when a brick configuration `useEffect` updates the Formik values automatically on mount, do we want that to show as unsaved changes? 
  - Long-term the autom-running normalizations should to be moved into the form state adapter
- [x] Add playwright test

## Future Work

- https://github.com/pixiebrix/pixiebrix-extension/issues/9370

For more information on our expectations for the PR process, see the
[code review principles doc](https://www.notion.so/pixiebrix/Code-Review-Principles-1ce7276b82a84d2a995d55ad85e1310d?pvs=4)

### CODE REVIEW

File: src/pageEditor/panes/ModComponentEditorPane.tsx [hunk 1]
```diff
@@ -37,39 +37,72 @@ import IntegrationsSliceModIntegrationsContextAdapter from "@/integrations/store
...
-        editorActions.setModComponentFormState({
-          modComponentFormState: values,
-          includesNonFormikChanges: false,
-          dirty: true,
-        }),
-      );
-      dispatch(actions.checkActiveModComponentAvailability());
+      const currentKey = getFormReinitializationKey();
+
+      // Don't sync on the first call after the reinitialization key changes because the call would cause
```
Comment (twschiller) [inline src/pageEditor/panes/ModComponentEditorPane.tsx:80]: See the failing CI test - one thing we might consider doing is checking for deep equality on the first update after reinitialization

**Comment by twschiller** [comment]
@grahamlangford re-assigning to you for now because I believe this is related to the reinitialization PR: https://github.com/pixiebrix/pixiebrix-extension/pull/9351 and I'll be partially OOO tomorrow

File: src/pageEditor/modListingPanel/ModComponentIcons.tsx [hunk 2]
```diff
@@ -34,7 +34,7 @@ export const NotAvailableIcon: React.FunctionComponent = () => (
 );
 
 export const UnsavedChangesIcon: React.FunctionComponent = () => (
-  <Icon library="custom" icon="ic-unsaved" />
+  <Icon library="custom" icon="ic-unsaved" title="Unsaved changes" />
```
Comment (twschiller) [inline src/pageEditor/modListingPanel/ModComponentIcons.tsx:37]: These should probably have `role="status"`, but Playwright `getByRole` didn't seem to be working for that

File: src/pageEditor/panes/ModComponentEditorPane.tsx [hunk 3]
```diff
@@ -37,39 +36,76 @@ import IntegrationsSliceModIntegrationsContextAdapter from "@/integrations/store
...
 
 const EditorPaneContent: React.VoidFunctionComponent<{
   modComponentFormState: ModComponentFormState;
 }> = ({ modComponentFormState }) => {
   const dispatch = useDispatch();
+  const getFormReinitializationKey = useGetFormReinitializationKey();
+  const previousKey = useRef<string | null>(getFormReinitializationKey());
 
-  // XXX: anti-pattern: callback to update the redux store based on the formik state
-  const syncReduxState = useDebouncedCallback(
```
Comment (twschiller) [inline src/pageEditor/panes/ModComponentEditorPane.tsx:52]: @grahamlangford do you remember why the code was double-debouncing?

Comment (grahamlangford) [reply src/pageEditor/panes/ModComponentEditorPane.tsx:52]: I have no context there, sorry

File: src/pageEditor/panes/ModComponentEditorPane.tsx [hunk 4]
```diff
@@ -37,39 +36,76 @@ import IntegrationsSliceModIntegrationsContextAdapter from "@/integrations/store
...
+
+/**
+ * Returns callback to generate the current key to force reinitialization of Formik form.
+ */
+function useGetFormReinitializationKey(): () => string {
+  const store = useStore<EditorRootState>();
+
+  return useCallback(() => {
+    const state = store.getState();
+    const editorUpdateKey = selectEditorUpdateKey(state);
```
[the remark this answers is not in the document]
Comment (twschiller) [reply src/pageEditor/panes/ModComponentEditorPane.tsx:53]: I think I needed to use it so that the `syncReduxState` callback could see the latest value. I wasn't 100% sure the semantics of how `useDebouncedCallback` would update the closure to ensure the call saw that latest value (esp. given that `useDebouncedCallback` doesn't expose a dependency list).

So at least this approach is more readable/predictable to me on what the semantics are

File: src/pageEditor/panes/ModComponentEditorPane.tsx (hunk 1 above)
Comment (twschiller) [reply src/pageEditor/panes/ModComponentEditorPane.tsx]: I ended up going with approach 1. With approach 2, there's a corner case where normalizations get overwritten if the user's next change is not via Formik

File: src/pageEditor/panes/ModComponentEditorPane.tsx [hunk 5]
```diff
@@ -37,39 +36,83 @@ import IntegrationsSliceModIntegrationsContextAdapter from "@/integrations/store
...
+  }, [store]);
+}
 
 const EditorPaneContent: React.VoidFunctionComponent<{
   modComponentFormState: ModComponentFormState;
 }> = ({ modComponentFormState }) => {
   const dispatch = useDispatch();
+  const getFormReinitializationKey = useGetFormReinitializationKey();
+  const previousKey = useRef<string | null>(getFormReinitializationKey());
+  const previousValues = useRef(modComponentFormState);
```
Comment (grahamlangford) [inline src/pageEditor/panes/ModComponentEditorPane.tsx:73]: Am I missing where this value is updated?

File: src/pageEditor/panes/ModComponentEditorPane.tsx (hunk 1 above)
Comment (twschiller) [reply src/pageEditor/panes/ModComponentEditorPane.tsx]: Latest changes have a blended approach - it updates the form state but does not update the dirty flag
