### PR TITLE
#8075 ensure we capture events in selection menu handlers

### LINKED ISSUE #8075: Text Selection Menu never closes on Notion modals
## Describe the bug

In Notion, when a page modal is open and text is selected, clicking away does not close the menu. The same behavior does not happen when the page is opened as a full page.

## To Reproduce

1. Go to Notion
2. Open the preview of a page (in a modal)
3. Select text
4. the Text Selection Menu is shown
5. Click elsewhere in the modal

## Actual behavior

The menu remains open in the same location. Highlighting other text moves the menu, but it does not appear possible to close it

## Expected behavior

The menu should be dismissed

## Screenshots/Loom

https://www.loom.com/share/47ae5403286e4d0fb793e8e5b6e83ad2

## Desktop (please complete the following information):

- Extension Version: 1.8.11

### PR DESCRIPTION
**Pull request by fungairino**
## What does this PR do?

- Fixes #8075

## Demo

- https://www.loom.com/share/e1a27b1e822d4d22a95c52390a53491c

## Checklist

- [ ] Add tests and/or storybook stories
- [X] Designate a primary reviewer @grahamlangford

### CODE REVIEW

File: src/contentScript/textSelectionMenu/selectionMenuController.tsx [hunk 1]
```diff
@@ -48,12 +48,6 @@ export const selectionMenuActionRegistry = new ActionRegistry();
 
 let selectionMenu: Nullishable<HTMLElement>;
 
-const onMousedownHide = (event: MouseEvent) => {
```
Comment (fungairino) [inline src/contentScript/textSelectionMenu/selectionMenuController.tsx:51]: I moved this function closer to where it's used for better code organization
