### PR TITLE
#7735: adds very basic null checks to prevent NPE

### LINKED ISSUE #7735: Page Editor NPE (destructure property blockId)
## Describe the bug

An NPE was thrown in the Page Editor caused by an attempt to destructure `blockId`. See https://pixiebrix.slack.com/archives/C04373D2R18/p1708967778693429

## Desktop (please complete the following information):

- Extension Version: 1.8.9

### PR DESCRIPTION
**Pull request by grahamlangford**
## What does this PR do?

- Fixes #7735

## Discussion

- Tried adding the file to `tsconfig.strictNullChecks.json`, but that threw 500+ errors (not surprising since it imports from editorSelectors)

## Checklist

- [x] Designate a primary reviewer @fungairino

### CODE REVIEW

File: src/pageEditor/tabs/editTab/editorNodeConfigPanel/EditorNodeConfigPanel.tsx [hunk 1]
```diff
@@ -37,9 +37,15 @@ const EditorNodeConfigPanel: React.FC = () => {
   const {
     blockId: brickId,
     path: brickFieldName,
-    blockConfig: { comments },
-  } = useSelector(selectActiveNodeInfo);
+    blockConfig,
+  } = useSelector(selectActiveNodeInfo) ?? {};
+  const { comments } = blockConfig ?? {};
```
Comment (fungairino) [inline src/pageEditor/tabs/editTab/editorNodeConfigPanel/EditorNodeConfigPanel.tsx:42]: nit: I think this can be simplified to:
```
    blockConfig: { comments = {} },
  } = useSelector(selectActiveNodeInfo) ?? {};
```

**Review by fungairino — APPROVED** [review]

File: src/pageEditor/tabs/editTab/editorNodeConfigPanel/EditorNodeConfigPanel.tsx (hunk 1 above)
Comment (grahamlangford) [reply src/pageEditor/tabs/editTab/editorNodeConfigPanel/EditorNodeConfigPanel.tsx:42]: I think it would have to be:

```
  blockConfig: { comments } = {}
```

Which I find harder to read.

Comment (fungairino) [reply src/pageEditor/tabs/editTab/editorNodeConfigPanel/EditorNodeConfigPanel.tsx:42]: Oh right, the actual right way to right this is:
```
  const {
    blockId: brickId,
    path: brickFieldName,
    blockConfig: { comments} = {},
  } = activeNodeInfo ?? {};
```
