### PR TITLE
#8347 Fix custom document stylesheets nested stylesheet inheritance

### LINKED ISSUE #8347: CSS style sheets for embedded form not inherited from the parent document
## Describe the bug

- https://pixiebrix.slack.com/archives/C0436P48QHY/p1714060287364699

## To Reproduce

1. Create a document with a theme CSS, e.g., https://pixiebrix-public-stylesheets.s3.us-east-2.amazonaws.com/pixiebrix/snippet-manager.css?versionId=bdX2jLRU2EH54uG3uLEOm28vuOl0Ny5R
2. Add a form

I also created a mod here we can use for testing: `@pixies/testing/panel-theme`

## Actual behavior

Theme CSS is not applied to the form

## Expected behavior

Theme should be applied to the form

## Screenshots/Loom

image

image

## Workaround

- Repeat the stylesheet in the Theme for the form

## Desktop (please complete the following information):

- Extension Version: 1.8.13-beta.5-mv3

## Discussion

- I think CSS behavior would be a good use of Playwright visual snapshot testing, so we can detect unintentional changes in rendering

## Testing

- I created a mod here we can use for testing: `@pixies/testing/panel-theme`

## Investigation

- Looks like the code was accidentally removed: https://pixiebrix.slack.com/archives/C0436P48QHY/p1714061651271019?thread_ts=1714060287.364699&cid=C0436P48QHY
- Likely related to the IsolatedComponent work? Either the fix or the original work: https://github.com/pixiebrix/pixiebrix-extension/pull/8325

### PR DESCRIPTION
**Pull request by mnholtz**
## What does this PR do?

- Closes #8347 
- Replaces logic introduced in https://github.com/pixiebrix/pixiebrix-extension/pull/7550 and accidentally removed in https://github.com/pixiebrix/pixiebrix-extension/pull/8200
- In draft because I want to make sure that I understand the relationship between this feature and IsolatedComponent before opening
- But, see Playwright test for demonstration that this fixes the regression

## Demo
- See playwright test

Screenshot 2024-04-26 at 5 39 41 PM

## Checklist

- [x] Add jest or playwright tests and/or storybook stories
- [x] Designate a primary reviewer @BLoe

### CODE REVIEW

File: src/components/StylesheetsContext.ts [hunk 1]
```diff
@@ -0,0 +1,109 @@
...
+  stylesheets: string[];
+} {
+  return useStylesheetsContextWithDefaultValues({
+    newStylesheets,
+    defaultStylesheets: [
+      bootstrap,
+      bootstrapOverrides,
+      // CustomFormComponent.css and EphemeralFormContent.css are artifacts produced by webpack, see the entrypoints.
+      "/EphemeralFormContent.css",
+      "/CustomFormComponent.css",
```
Comment (BLoe) [inline src/components/StylesheetsContext.ts:102]: I assume this change is related to the isolated components? I didn't need to include these when I built this before.

File: src/components/StylesheetsContext.ts [hunk 2]
```diff
@@ -0,0 +1,109 @@
...
+    newStylesheets,
+    defaultStylesheets: [
+      bootstrap,
+      bootstrapOverrides,
+      // DocumentView.css is an artifact produced by webpack, see the DocumentView entrypoint included in
+      // `webpack.config.mjs`. We build styles needed to render documents separately from the rest of the sidebar
+      // in order to isolate the rendered document from the custom Bootstrap theme included in the Sidebar app
+      "/DocumentView.css",
+      // Required because it can be nested in the DocumentView.
+      "/CustomFormComponent.css",
```
Comment (BLoe) [inline src/components/StylesheetsContext.ts:80]: I don't know if it matters at all, but was there a specific reason you changed the ordering here from what it was in my first PR? Just curious to learn how the order can impact things here.

File: end-to-end-tests/tests/runtime/sidebarPanelTheme.spec.ts [hunk 3]
```diff
@@ -0,0 +1,54 @@
...
+  ).toBeVisible();
+
+  const green = "rgb(0, 128, 0)";
+  const elementsThatShouldBeGreen = await sidebarPage
+    .getByText("This should be green")
+    .all();
+  await Promise.all(
+    elementsThatShouldBeGreen.map(async (element) =>
+      expect(element).toHaveCSS("color", green),
+    ),
```
Comment (fungairino) [inline end-to-end-tests/tests/runtime/sidebarPanelTheme.spec.ts:52]: (not required)
This would be a great candidate for a screenshot test if you want to take a look at it. https://playwright.dev/docs/test-snapshots#generating-screenshots

File: src/components/StylesheetsContext.ts (hunk 2 above)
Comment (mnholtz) [reply src/components/StylesheetsContext.ts:80]: As discussed in person I just copied the file that was deleted in Federico's PR. This was a change that @grahamlangford introduced.

File: end-to-end-tests/tests/runtime/sidebarPanelTheme.spec.ts (hunk 3 above)
Comment (mnholtz) [reply end-to-end-tests/tests/runtime/sidebarPanelTheme.spec.ts:52]: Thank you. I want to hold off on screenshot testing for now, so we can have a separate discussion/exploration with the feature.

**Review by BLoe — APPROVED** [review]
