### PR TITLE
#4363 Fix Read All Tables brick when there are empty rows in a table on the page

### LINKED ISSUE #4363: Read All Tables brick errors with NPE
Context
---
- Test on 1.7.9-beta.1
- Visit: https://mthek10.github.io/OldPortal/index.html
- Use the Read All Tables brick

image

### PR DESCRIPTION
**Pull request by BLoe**
## What does this PR do?

- Fixes #4363 

## Reviewer Tips

- My new code fills in empty rows with an empty array, which is then filled in by the existing loop at the end of the function, up to the max row length.

## Discussion

- This means that empty table rows will be normalized to rows of empty cells. Does this break any existing behavior/expectations around how the brick works? I think any cases of empty rows would have been hitting this error before, regardless.

## Checklist

- [ ] Add tests
- [ ] Designate a primary reviewer

### CODE REVIEW

File: src/utils/parseDomTable.ts [hunk 1]
```diff
@@ -85,10 +85,25 @@ function flattenTableContent(table: HTMLTableElement): RawTableContent {
...
+  }
+
+  // Normalize empty rows
+  for (const index of emptyRowIndexes) {
+    // eslint-disable-next-line security/detect-object-injection -- numeric array index
+    flattened[index] = [];
+  }
+
   // In case of malformed tables, ensure that the result is a perfect matrix so we don't have runtime errors
-  const maxRowlength = Math.max(...flattened.map((row) => row.length));
```
Comment (fregante) [inline src/utils/parseDomTable.ts:89]: If the error is here, it can just be solved with `?.`

IMO this solution is too verbose for what it's doing.

If that's not it, we just need to immediately initialize `flattened` with an array of empty arrays and skip line 77.

In short:

```js
const flattened = Array.from(table.rows, () => [])
// or [...rows].map(() => [])
```

**Review by fregante — CHANGES_REQUESTED** [review]

File: src/utils/parseDomTable.ts (hunk 1 above)
Comment (BLoe) [reply src/utils/parseDomTable.ts:89]: I changed this up a bit, do you mind looking at it again?

I suppose we could filter out empty table rows instead of normalizing, but couldn't users also do that if they choose?

Comment (BLoe) [reply src/utils/parseDomTable.ts:89]: @fregante I changed it to filter out empty rows as well.

**Review by twschiller — APPROVED** [review]
