### PR TITLE
#2906 JQuery Reader brick shows incorrect preview for trigger in eventTarget root mode

### LINKED ISSUE #2906: JQuery Reader brick shows incorrect preview for trigger in eventTarget root mode
Steps to reproduce
- Define a click trigger on a button
- Add a JQuery reader with the default (using "inherit" for root mode)

Actual Behavior
- Preview shows results relative to the root document

Expected Behavior
- Preview should be relative to the element/target from the last run

Considerations
- If the trigger is eventTarget root mode and the JQuery brick is configured to inherit, we can just say "Preview not available" (TODO: improve this error message)

### PR DESCRIPTION
**Pull request by BALEHOK**
Fixes #2906

### CODE REVIEW

File: src/pageEditor/tabs/effect/BlockPreview.tsx [hunk 1]
```diff
@@ -191,6 +207,18 @@ const BlockPreview: React.FunctionComponent<{
     );
   }
 
+  if (
+    blockRootMode === "inherit" &&
+    extensionPointDefinition.targetMode !== "root"
+  ) {
+    return (
+      <div className="text-muted">
+        Output previews are not supported for blocks with inherited rootMode and
```
Comment (twschiller) [inline src/pageEditor/tabs/effect/BlockPreview.tsx:216]: Change copy to:

> Output Preview not supported because this brick's Root Mode is "Inherit" and the Trigger's Target Mode is "Event Target". Run the Trigger to see the output on the Output tab

File: src/pageEditor/tabs/effect/BlockPreview.tsx [hunk 2]
```diff
@@ -191,6 +207,18 @@ const BlockPreview: React.FunctionComponent<{
     );
   }
 
+  if (
+    blockRootMode === "inherit" &&
```
Comment (twschiller) [inline src/pageEditor/tabs/effect/BlockPreview.tsx:211]: I don't think this condition is correct? I think it needs to check if the extension point is a trigger?

File: src/pageEditor/tabs/effect/BlockPreview.tsx [hunk 3]
```diff
@@ -151,15 +154,28 @@ const BlockPreview: React.FunctionComponent<{
 
   const [blockInfo, blockLoading, blockError] = usePreviewInfo(blockConfig.id);
 
+  const blockRootMode = blockConfig.rootMode ?? "inherit";
+  const extensionPointDefinition: any = extensionPoint.definition;
```
Comment (twschiller) [inline src/pageEditor/tabs/effect/BlockPreview.tsx:158]: Let's avoid assigning to `any` here. Check if it's a trigger definition

- [ ] Avoid any

File: src/pageEditor/tabs/effect/BlockPreview.tsx [hunk 4]
```diff
@@ -151,15 +154,28 @@ const BlockPreview: React.FunctionComponent<{
 
   const [blockInfo, blockLoading, blockError] = usePreviewInfo(blockConfig.id);
 
+  const blockRootMode = blockConfig.rootMode ?? "inherit";
```
Comment (twschiller) [inline src/pageEditor/tabs/effect/BlockPreview.tsx:157]: Would be helpful to comment that this defaults to inherit due as described in documentation for BlockConfig.rootMode

File: src/pageEditor/tabs/effect/BlockPreview.tsx [hunk 5]
```diff
@@ -151,15 +154,28 @@ const BlockPreview: React.FunctionComponent<{
...
+  const extensionPointDefinition: any = extensionPoint.definition;
+
   const debouncedRun = useDebouncedCallback(
     async (blockConfig: BlockConfig, context: BlockArgContext) => {
       dispatch(previewSlice.actions.startRun());
       const { outputKey } = blockConfig;
+
+      // If the block is configured to inherit the root element,
+      // try to get the root element from the extension point.
+      // Note: not possible when extensionPoint's targetMode equals "targetElement"
```
Comment (twschiller) [inline src/pageEditor/tabs/effect/BlockPreview.tsx:167]: Don't silently do the wrong behavior. If targetElement is undefined this will pass along undefined which downstream will cause the document to be used

At least in the comment indicate which check is preventing this from happening

File: src/contentScript/pageEditor.ts [hunk 6]
```diff
@@ -94,6 +96,15 @@ export async function runBlock({
     previousOutput: {},
   };
 
+  if (rootSelector) {
+    // Not 100% accurate, since we're looking for an element in the document,
```
Comment (twschiller) [inline src/contentScript/pageEditor.ts:100]: I don't understand the comment. Won't this code path will only ever be used when the is root is the document?

The "closest" terminology is misleading. It would be $safeFind relative to the event target. In JQuery closest actually means the opposite, searching the ancestors: https://api.jquery.com/closest/

File: src/pageEditor/tabs/effect/BlockPreview.tsx (hunk 2 above)
Comment (twschiller) [reply src/pageEditor/tabs/effect/BlockPreview.tsx:211]: If you place a single button, the message is showing:

image

**Review by twschiller — CHANGES_REQUESTED** [review]
See comments about checking if the extension point is a trigger. The current behavior is incorrect for buttons (and potentially other extension points)

File: src/contentScript/pageEditor.ts (hunk 6 above)
Comment (BALEHOK) [reply src/contentScript/pageEditor.ts:100]: I added the comment mainly because of this code: https://github.com/pixiebrix/pixiebrix-extension/blob/756208b2286a83c576af71ac7c3041961648b3a1/src/extensionPoints/triggerExtension.ts#L331

If my understanding is correct the element may not be exactly the one returned by `$findSafe`.

Comment (twschiller) [reply src/contentScript/pageEditor.ts:100]: Thanks for the link. If the selector is unique, it will always be the same element

The code you linked is to handle a gotcha with event targets during propagation:
- Takes the element that generated the DOM event (e.g., click)
- Finds the trigger target

The reason we have to do this is supposed we have:
```
<button id="foo"><span>abc</span></button>
```

If the triggerSelector is `#foo", when the user clicks if they click on the span part of the button (or maybe an icon on the button), the target will be the span during the event propagation

File: src/pageEditor/extensionPoints/elementConfig.ts [hunk 7]
```diff
@@ -45,21 +45,23 @@ export type SingleLayerReaderConfig =
   | RegistryId[]
   | Record<string, RegistryId>;
 
-export interface BaseExtensionPointState {
+export type BaseExtensionPointState = {
   metadata: Metadata;
   definition: {
+    type: ExtensionPointType;
```
Comment (BALEHOK) [inline src/pageEditor/extensionPoints/elementConfig.ts:51]: The property `type` is actually there on the `FormState.extensionPoint.definition` , but wasn't included in the type definition and was assigned by `fromNativeElement` methods.
Maybe we can drop the `type` on the root level of `FormState`?

File: src/pageEditor/extensionPoints/formStateTypes.ts [hunk 8]
```diff
@@ -0,0 +1,174 @@
...
+  traits?: {
+    style: {
+      mode: "default" | "inherit";
+    };
+  };
+};
+
+export interface ActionFormState
+  extends BaseFormState<ActionExtensionState, ActionExtensionPointState> {
+  type: "menuItem";
```
Comment (BALEHOK) [inline src/pageEditor/extensionPoints/formStateTypes.ts:73]: Should this type be called `MenuItemFormState`?

Comment (BLoe) [reply src/pageEditor/extensionPoints/formStateTypes.ts:73]: If we're going to update the naming, should we just change the entire thing to "button"/Button or "actionButton"/ActionButton or something like that? "menuItem" is not that much more accurate than "action" imo.

File: src/pageEditor/extensionPoints/formStateTypes.ts [hunk 9]
```diff
@@ -0,0 +1,174 @@
...
+}
+
+// PanelFormState
+export type PanelTraits = {
+  style: {
+    mode: "default" | "inherit";
+  };
+};
+
+type PanesExtensionState = BaseExtensionState & Except<PanelConfig, "body">;
```
Comment (BLoe) [inline src/pageEditor/extensionPoints/formStateTypes.ts:117]: Typo here `Panes` --> `Panel`

File: src/pageEditor/extensionPoints/formStateTypes.ts [hunk 10]
```diff
@@ -0,0 +1,174 @@
...
+
+export interface PanelFormState
+  extends BaseFormState<PanesExtensionState, PanelExtensionPointState> {
+  type: "panel";
+
+  containerInfo: ElementInfo;
+}
+
+// ContextMenuFormState
+type Extension = BaseExtensionState & Except<ContextMenuConfig, "action">;
```
Comment (BLoe) [inline src/pageEditor/extensionPoints/formStateTypes.ts:138]: Why is this just called `Extension`? Should it be `ContextMenuExtensionState`?

Comment (BALEHOK) [reply src/pageEditor/extensionPoints/formStateTypes.ts:138]: It should `ContextMenuExtensionState` :)

File: src/pageEditor/extensionPoints/elementConfig.ts (hunk 7 above)
Comment (twschiller) [reply src/pageEditor/extensionPoints/elementConfig.ts:51]: > Maybe we can drop the type on the root level of FormState?

Let's keep it on the root level for this PR. Can refactor FormState in a separate PR later

File: src/pageEditor/extensionPoints/formStateTypes.ts (hunk 8 above)
Comment (twschiller) [reply src/pageEditor/extensionPoints/formStateTypes.ts:73]: My vote would be for ButtonFormState. But let's not do in this PR

**Review by twschiller — APPROVED** [review]
