### PR TITLE
#6531 Fix tab names field for gsheets

### LINKED ISSUE #6531: Tab name is cleared from Google bricks
Steps to Reproduce
---
- Take a brick with legacy integration
- Click to use the PKCE integration
- The tab name field gets cleared out
image

### PR DESCRIPTION
**Pull request by BLoe**
## What does this PR do?

- Fixes #6531 

## Discussion

* I tried to figure out a way to fire the listeners from the background script when `setCachedAuthData()` is called, but couldn't figure anything out that wasn't a giant hairy mess of messenger code back and forth, so I went with the simple-if-slightly-hacky method of monitoring local storage directly from the React component

## Checklist

- [x] Add tests
- [ ] New files added to `src/tsconfig.strictNullChecks.json` (if possible)
- [x] Designate a primary reviewer - @grahamlangford

### CODE REVIEW

File: src/extensionConsole/pages/integrations/IntegrationEditorModal.tsx [hunk 1]
```diff
@@ -74,8 +74,8 @@ const IntegrationEditorModal: React.FunctionComponent<OwnProps> = ({
   const onSubmit = useCallback<OnSubmit<IntegrationConfig>>(
     async (values, helpers) => {
       helpers.setSubmitting(true);
-      await onSave(values);
       onClose();
+      await onSave(values);
```
Comment (BLoe) [inline src/extensionConsole/pages/integrations/IntegrationEditorModal.tsx:78]: I'm reverting a change I made in the telemetry PR, I realized it's worse UX because a delete button flashes that I couldn't (quickly) figure out how to prevent.

**Review by grahamlangford — APPROVED** [review]
