### PR TITLE
#8086: fixed width icons in page editor mod sidebar

### LINKED ISSUE #8086: Page Editor sidebar icons are not fixed width
Context
---
- This is probably a regression given that we hadn't noticed it before?

Screenshot
---
image

### PR DESCRIPTION
**Pull request by fungairino**
## What does this PR do?

- Closes #8086

## Demo
Screenshot 2024-04-03 at 9 22 59 PM

## Future Work

Visual screenshot testing with playwright would be a nice follow up

## Checklist

- [ ] Add tests and/or storybook stories
- [X] Designate a primary reviewer @BLoe

### CODE REVIEW

File: src/pageEditor/sidebar/ExtensionIcons.tsx [hunk 1]
```diff
@@ -29,7 +29,10 @@ import Icon from "@/icons/Icon";
 export const ExtensionIcon: React.FunctionComponent<{
   type: StarterBrickType;
 }> = ({ type }) => (
-  <FontAwesomeIcon icon={ADAPTERS.get(type)?.icon ?? faPuzzlePiece} />
+  <FontAwesomeIcon
+    fixedWidth={true}
```
Comment (twschiller) [inline src/pageEditor/sidebar/ExtensionIcons.tsx:33]: NIT: you don't need the `={true}`, can just write `fixedWidth`

**Review by twschiller — APPROVED** [review]
@fungairino snapshots will need to be updated
