### PR TITLE
#9069: Don't require control room integration for users authenticating with PixieBrix Token

### LINKED ISSUE #9069: AA Username/Password partner login screen shows even after success message
## Describe the bug

- https://www.notion.so/pixiebrix/419bf2db2d2141eb94a0f0248ed3df0c?pvs=4#fff43b21a25380f99103e92230446a85

## To Reproduce

The main thing I think you're trying to replicate is getting the extension into a state where:
- The organization of the admin use has an associated control room
- The partner is `automation-anywhere` 
- The authentication method is `default`

Steps to reproduce the behavior using Automation Anywhere CE:

1. Activate PixieBrix via AA community flow
   1. Uninstall the browser extension
   2. Visit an Copilot page: https://community2.cloud-2.automationanywhere.digital/aari/#/requests/all?sortBy=createdOn&orderBy=desc
   3. Click the user profile selector and click Get PixieBrix Extension
image
   4. Or you can try using this link directly: https://app.pixiebrix.com/start?hostname=community2.cloud-2.automationanywhere.digital&partner=automation-anywhere&tenantId=3d27ff32-34c5-4f26-8458-018a9c42445e
2. Follow instructions to setup PixieBrix
3. In extension on AA screen, provide your community control room URL username/password

## Actual behavior

Shows success toast, but doesn't then show extension console. Page Editor shows as logged out

## Expected behavior

Extension is authenticated using PixieBrix token and an AA username/password authentication exists as a local integration

## Discussion

- Related to the recent `v1` vs. `v2` AA authentication URL change somehow (AA had retired the v1 authentication endpoint?)?
- We might consider making the authentication type field a dropdown instead of text entry
- From a UX perspective, we should really get around to making the UX of the form normal with a "Save" button (they update on blur, but not if you click the left side nav to force it to blur)

## Workaround

- Go to `/settings` and change the authentication method from `default` to `pixiebrix-token`
- Click outside the field so it takes effect
- Click the Mods Screen to verify the extension was connected

## Related Issues

- https://github.com/pixiebrix/pixiebrix-extension/issues/9089

## Related Code

- https://github.com/pixiebrix/pixiebrix-extension/blob/3d6b531253fbe7047d5b0e059f8699fce9e34d3b/src/extensionConsole/pages/onboarding/partner/PartnerSetupCard.tsx#L73-L73

### PR DESCRIPTION
**Pull request by mnholtz**
## What does this PR do?

- Closes #9069

## Discussion

- I recommend unit test coverage as the best way to ensure other cases are still handled. We have several unit tests in place for the `useRequirePartnerAuth` hook that demonstrate expected behavior

### CODE REVIEW

File: src/auth/useRequiredPartnerAuth.ts [hunk 1]
```diff
@@ -187,12 +191,28 @@ function useRequiredPartnerAuth(): RequiredPartnerState {
...
   } else if (localAuth) {
+    const organization = localAuth.organization ?? null;
+    const organizationMembership = localAuth.organizations.find(
+      (membership) => membership.id === organization?.id,
+    );
+    organizationRole = organizationMembership
+      ? transformUserOrganizationMembershipRoleResponse(
+          organizationMembership.role,
+        )
+      : null;
```
Comment (grahamlangford) [inline src/auth/useRequiredPartnerAuth.ts:215]:
```suggestion
    organizationRole = organizationMembership?.role === UserRole.admin ? "admin" : null
```

**Comment by mnholtz** [comment]
E2E test is appropriately failing on expected sidebar behavior. I have an additional question about expected requirements for this feature: https://www.loom.com/share/364c13c60bec4a87934bdac3bd9067ad

**Comment by twschiller** [comment]
cc @Pashaminkovsky for awareness. This week I'll chat with you and @grahamlangford about getting you both more up to speed on the partner integration behavior

**Review by BLoe — APPROVED** [review]

**Comment by twschiller** [comment]
@mnholtz are there any outstanding questions on this PR?

File: src/auth/useRequiredPartnerAuth.ts [hunk 2]
```diff
@@ -248,15 +258,18 @@ function useRequiredPartnerAuth(): RequiredPartnerState {
...
-    // Primary organization has a partner and linked control room
-    (hasPartner && controlRoom != null) ||
-    // Partner Automation Anywhere is configured in managed storage (e.g., set by Bot Agent installer)
-    managedPartnerId === "automation-anywhere" ||
-    // Community edition users are required to be linked until they join an organization
-    (me?.partner && isCommunityEditionUser) ||
-    // User has overridden local settings
-    authMethodOverride === "partner-oauth2" ||
-    authMethodOverride === "partner-token";
+    [null, "default"].includes(authMethodOverride) &&
```
Comment (twschiller) [inline src/auth/useRequiredPartnerAuth.ts:261]: NIT: does includes handle null vs. undefined the same way that `==` does?

**Comment by twschiller** [comment]
> @twschiller see slack - I just wanted to double check the updated logic before merging

Seems correct -- see comment on null vs. undefined

File: src/auth/useRequiredPartnerAuth.ts (hunk 2 above)
Comment (mnholtz) [reply src/auth/useRequiredPartnerAuth.ts:261]: I added this because of the typing for authMethodOverride (it's specifically null). I can include undefined to be thorough, but do you see any reason not to trust the type in this case?
