### PR TITLE
#9354: fix Page Editor lag regression when clicking between mods

### LINKED ISSUE #9354: Lag in Page Editor when working large mods
Context
--- 
- Probably introduced in: https://github.com/pixiebrix/pixiebrix-extension/pull/9298
- Can performance debug using profile: `chrome-extension://mpjjildhmpddojocokjkgmlkkkfjnepo/pageEditor.html`

### PR DESCRIPTION
**Pull request by twschiller**
## What does this PR do?

- Closes #9354 
- Modifies `useRegisterDraftModInstanceOnAllFrames` to only check for reinjection on sequence number changes
  - Why? The selected mod component is handled by Formik/Reload Toolbar. The only way for the other mod components to be changed is Redux modifications, which would bump the sequence number
- Refactors `useRegisterDraftModInstanceOnAllFrames` to be a thunk. (Avoids calculating selectGetCleanComponentsAndDirtyFormStatesForMod, etc. on every Formik update that's committed)

## Discussion

- On beta.1 build on my M1, the click into a large mod was taking 110ms. Preliminary profiling didn't point out any major bottlenecks - it seems like computation just add up
- Not sure at what number of mods shifting to a storage format of `Record<UUID, ModComponentFormState>` would make a measurable/noticeable difference

For more information on our expectations for the PR process, see the
[code review principles doc](https://www.notion.so/pixiebrix/Code-Review-Principles-1ce7276b82a84d2a995d55ad85e1310d?pvs=4)

### CODE REVIEW

File: src/pageEditor/hooks/useRegisterDraftModInstanceOnAllFrames.ts [hunk 1]
```diff
@@ -180,12 +161,48 @@ function useRegisterDraftModInstanceOnAllFrames(): void {
...
 
   // Run updateDraftModInstance whenever the mod instance configuration changes
+  // The ReloadToolbar manages reloading for Formik changes for the active mod component (if any). The other
+  // mod components can only change when the editor sequence number changes. (The sequence number changes whenever
+  // a update occurs via Redux instead of Formik)
   useAsyncEffect(async () => {
-    await updateDraftModInstance();
-  }, [updateDraftModInstance]);
+    await dispatch(updateDraftModInstance());
+  }, [dispatch, editorUpdateKey]);
```
Comment (twschiller) [inline src/pageEditor/hooks/useRegisterDraftModInstanceOnAllFrames.ts:205]: Main performance change
