### PR TITLE
Feature/2446 fix actions

### LINKED ISSUE #2446: fix useInstallableActions and BlueprintActions to match existing Active Bricks functionality
Actions provided to each Installable with the BlueprintActions component do not currently match actions available on the existing Active Bricks page. This includes:
- [x] - fix shared to include share link
- [x] - add notify to uninstall actions
- [x] - remove uninstall from inactive recipes/extensions

### PR DESCRIPTION
**Pull request by mnholtz**
Closes #2446 

This adds and fixes actions provided to Installables on the Blueprints page.

- [x] On Extension delete, need to re-render or remove the extension from the data passed to React Table

### CODE REVIEW

File: src/options/pages/blueprints/BlueprintActions.tsx [hunk 1]
```diff
@@ -24,23 +23,31 @@ import {
...
   const {
-    remove,
+    data: { flags },
+  } = useGetAuthQuery();
+  const { installable, hasUpdate, status, sharing } = installableViewItem;
+  const {
+    uninstall,
     viewLogs,
     // TODO: consistent naming
     onExportBlueprint,
```
Comment (BALEHOK) [inline src/options/pages/blueprints/BlueprintActions.tsx:44]: Great chance to rename.

**Review by BALEHOK — COMMENTED** [review]
Didn't test, but the code looks good to me.

**Review by BALEHOK — APPROVED** [review]
