### PR TITLE
#3722: keep unminified error class names

### LINKED ISSUE #3722: Cancel/Business Error in panel extension being shown as application error
Steps to reproduce:
1. Add a cancel brick
2. Render the panel

### PR DESCRIPTION
**Pull request by twschiller**
## What does this PR do?

- Closes #3722 
- Turns off class name minimization for error classes
- Adds some more tests for sanity-checking our error code

## Checklist

- [X] Add tests
- [X] Designate a primary reviewer: @fregante

### CODE REVIEW

File: src/errors/errorHelpers.ts [hunk 1]
```diff
@@ -171,21 +172,6 @@ export function isConnectionError(possibleError: unknown): boolean {
   );
 }
 
-/**
- * Some pages are off-limits to extension. This function can find out if an error is due to this limitation.
```
Comment (twschiller) [inline src/errors/errorHelpers.ts:175]: Not imported anywhere

Comment (fregante) [reply src/errors/errorHelpers.ts:175]: 🙌 Likely because we now no longer try, thanks to https://github.com/fregante/webext-content-scripts
