### PR TITLE
#3613: fix network error cause tracking

### LINKED ISSUE #3613: RTK errors lose `cause` (the page editor HTTP error log is broken)
Something (presumably RTK) is _only partially_ serializing errors, not `serialize-errors`. This is an example I'm seeing in the page editor: 

Screen Shot 13

The error is thrown  when I try to expand this, which then crashes the app because it expects `cause`:

Screen Shot 14

 The only place where we generate a RemoteServiceError has a `cause`:

https://github.com/pixiebrix/pixiebrix-extension/blob/e1c4679df66679a1d51e10100b18f69735f6a6e5/src/utils/enrichAxiosErrors.ts#L67

## Possible solution

RTK appears to expose a `serializeError` option but I didn't immediately find a way to implement this in our codebase.

- https://github.com/reduxjs/redux-toolkit/pull/812
- https://redux-toolkit.js.org/api/createAsyncThunk#options

## Related

Recently we've encountered errors that somehow lacked a `cause` property. Maybe around this time, but I'm not sure:

- https://github.com/pixiebrix/pixiebrix-extension/issues/3020

Found while looking into:

- https://github.com/pixiebrix/pixiebrix-extension/issues/3372

This worked three months ago:

- https://github.com/pixiebrix/pixiebrix-extension/pull/2860

RTK docs:

- https://redux-toolkit.js.org/api/createAsyncThunk#handling-thunk-errors

### PR DESCRIPTION
**Pull request by twschiller**
## What does this PR do?

- Closes #3613 
- Fixes an error in the dev code to set the text on the icon
- Adds some logging to isolate where the `cause` is getting dropped

## Discussion

- It looks like there's a discrepancy between how Chrome and node handle the overridden `cause` class properties w.r.t. serialize error

## TODO

- [X] Fix serialization of cause

## Future Work

- Fix serialization of config/response: they appear to be getting dropped at the messenger boundary

## Checklist

- [X] Add tests
- [X] Designate a primary reviewer: @fregante

### CODE REVIEW

File: src/background/requests.ts [hunk 1]
```diff
@@ -271,7 +271,15 @@ export async function proxyService<TData>(
       );
     }
 
-    return serializableAxiosRequest<TData>(requestConfig);
+    try {
+      return await serializableAxiosRequest<TData>(requestConfig);
+    } catch (error) {
+      console.debug("Error making request without service config", {
```
Comment (twschiller) [inline src/background/requests.ts:277]: @fregante There's no cause here. It looks likely an issue involving axios interceptors: https://github.com/pixiebrix/pixiebrix-extension/blob/0d52387d18dbe56627ddab94697ab37f228a4163/src/utils/enrichAxiosErrors.ts#L41-L41

Comment (twschiller) [reply src/background/requests.ts:277]: > The issue is in a serializer somewhere

Sorry, my message was ambiguous. Thinking it might be an issue with how Axios itself handles errors coming from transformers. The code logging point is consuming what's thrown from Axios. Will dig in and see what I find
