### PR TITLE
#7835: save focus on sidebar load

### LINKED ISSUE #7835: Insert at Cursor brick doesn't work sometimes from MV2 sidebar
## Describe the bug

- The fix in https://github.com/pixiebrix/pixiebrix-extension/pull/7827 sometimes doesn't work. Likely due to mouse movement patterns, or potentially if the user mouses into the sidebar to quickly?
- Observed by both @twschiller and @MMirandi on Zendesk on 1.8.10-beta.4 (Zendesk uses CKEditor without a frame). Works if you leave the sidebar to reselect the text and then mouse back into it

## Discussion

- Potentially, need to add a focus save when the sidebar is shown sidebarShowEvents to handle the case where the user has already mouseentered the sidebar: https://github.com/pixiebrix/pixiebrix-extension/blob/5df77606067da48fe8b438d60add8b9e98b2c2a0/src/contentScript/sidebarController.tsx#L549-L549

### PR DESCRIPTION
**Pull request by twschiller**
## What does this PR do?

- Fixes #7835 
- Saves focus via focusController automatically when the sidebar is shown to handle case where user `mouseenter`s the sidebar before the React App fires the ready event

## Demo

- https://www.loom.com/share/eb5c700c97644eb9bde31bbc2a312560

## Future Work

- Zendesk/CKEditor is still impacted by: https://github.com/pixiebrix/pixiebrix-extension/issues/7779

## Checklist

- 😞: Add tests: will require E2E test due to reliance on focus/editors
- [x] New files added to `src/tsconfig.strictNullChecks.json` (if possible): N/A
- [x] Designate a primary reviewer: @grahamlangford

### CODE REVIEW

File: src/contentScript/sidebarController.tsx [hunk 1]
```diff
@@ -554,6 +554,13 @@ export function initSidebarFocusEvents(): void {
         return;
       }
 
+      // Save focus on initial load, because the user may have `mouseenter`ed the sidebar before the React App
+      // fired the sidebarShowEvent event. For example, if the user clicked the browserAction toolbar button and
+      // immediately `mouseenter`ed the sidebar (because the top of the sidebar is very close to the top browserAction)
+      if (document.activeElement !== sidebar) {
+        focusController.save();
```
Comment (fregante) [inline src/contentScript/sidebarController.tsx:561]: Also save the selection like in my PR?

- https://github.com/pixiebrix/pixiebrix-extension/pull/7842

**Review by fregante — APPROVED** [review]

File: src/contentScript/sidebarController.tsx (hunk 1 above)
Comment (twschiller) [reply src/contentScript/sidebarController.tsx:561]: That's not required at the moment for this particular focus issue, so I'll leave it out
