### PR TITLE
#918: fix error root cause filtering

### LINKED ISSUE #918: Fix error root cause filtering
**Actual behavior**
- Exceptions are being reported to Rollbar as errors regardless of whether they have a application, business, or cancel root cause

**Expected behavior**
- Cancellations should not be reported to rollbar
- Business errors should only be reported to rollbar for deployments/enterprise

**Triaging**
- Medium/high priority: since it's impacting our error notifications for devops

### PR DESCRIPTION
**Pull request by twschiller**
Closes #918

- Fixes bug where nested ContextErrors weren't getting unrolled all the way to get the root cause
- Fixes handling of BusinessError subclasses
- Introduces `NoElementsFoundError` and `MultipleElementsFoundError` classes that take a selector (to keep the message in the error telemetry cleaner)

### CODE REVIEW

File: src/errors.ts [hunk 1]
```diff
@@ -200,24 +292,49 @@ export function isConnectionError(
...
+
+  if (isPromiseRejectionEvent(error)) {
+    return selectPromiseRejectionError(error);
+  }
+
+  if (isErrorEvent(error)) {
+    return error.error;
+  }
+
+  return error;
```
Comment (fregante) [inline src/errors.ts:339]: 🙌

**Review by fregante — COMMENTED** [review]
✅
