### PR TITLE
#5444 - Fix SheetsFileWidget and icon spacing

### LINKED ISSUE #5444: `SheetsFileWidget` crashing on the mod options tab in the page editor and on the activation page
https://pixiebrix.slack.com/archives/C05051S2SNR/p1680198304423919

* Happens in 1.7.22-beta.4

image

### PR DESCRIPTION
**Pull request by BLoe**
## What does this PR do?

- Fixes #5444 
- Fix icon spacing/width on the gsheet file icon

## Checklist

- [x] Add tests - now covered by `RecipeOptionsValues.test`, mocking was hiding the error in this test previously, this now tests a case where the state isn't `FormState`, and SheetsFileWidget doesn't fail anymore
- [x] Designate a primary reviewer

### CODE REVIEW

File: src/contrib/google/sheets/SheetsFileWidget.tsx [hunk 1]
```diff
@@ -46,12 +46,16 @@ const SheetsFileWidget: React.FC<SchemaFieldProps> = (props) => {
...
   const [doc, setDoc] = useState<SheetMeta | null>(null);
 
-  const { values: formState, setValues: setFormState } =
-    useFormikContext<FormState>();
+  const { values: formState, setValues: setFormState } = useFormikContext();
 
   // Remove unused services from the element - cleanup from deprecated integration support for gsheets
   useEffect(
     () => {
+      // This widget is also used outside the page editor, so this won't always be FormState
```
Comment (twschiller) [inline src/contrib/google/sheets/SheetsFileWidget.tsx:54]: This comment needs to be clarified. Is this also addressing the error when used in Current Inputs which is in the Page Editor, but is not the form state used when editing an IExtension

**Review by twschiller — APPROVED** [review]

File: src/contrib/google/sheets/SheetsFileWidget.tsx (hunk 1 above)
Comment (BLoe) [reply src/contrib/google/sheets/SheetsFileWidget.tsx:54]: Yep, you're right, I'll fix it.
