### PR TITLE
#3437: use proper pixiebrix favicon for toolbar icon

### LINKED ISSUE #3437: Wrong logo in browser toolbar
Context
- For small logos (favicon, browser toolbar), we use a 3 box logo without anything in the boxes
- I think in the Theme PR we accidentally switched over to the detailed logo? I see this in 1.6.3-alpha.3

### PR DESCRIPTION
**Pull request by mnholtz**
## What does this PR do?

- Fixes #3437 

## Reviewer Tips

- Double check that the icon appears as expected, and that theming still works.

Shoutout to @fregante for the suggested fix :)

## Demo/Screenshots
Screen Shot 2022-05-19 at 10 26 57 AM

## Team Coordination

_Leave all that are relevant and check off as completed_

- [ ] This PR requires security review
- [ ] This PR introduces a new library: double check it's MIT/Apache2/permissively licensed
- [ ] This PR requires a node/npm version update: let the team know on #engineering
- [ ] This PR requires a documentation change (link to old docs)
- [ ] This PR requires a tutorial update (link to old tutorials)
- [ ] This PR requires a feature flag
- [ ] This PR requires a environment variable change

## Checklist

- [ ] Add tests
- [ ] Designate a primary reviewer

### CODE REVIEW

File: src/background/partnerTheme.ts [hunk 1]
```diff
@@ -17,11 +17,19 @@
 
 import { getSettingsState } from "@/store/settingsStorage";
 import { getThemeLogo } from "@/utils/themeUtils";
+import { DEFAULT_THEME } from "@/options/constants";
```
Comment (mnholtz) [inline src/background/partnerTheme.ts:20]: Is this because I'm importing something from the options page into the background page? Is this ok in this case? I'd ideally like to use this constant.
Screen Shot 2022-05-19 at 10 23 56 AM

Comment (twschiller) [reply src/background/partnerTheme.ts:20]: > Is this because I'm importing something from the options page into the background page?

Yes, that's the reason why. The rule is defined here: https://github.com/pixiebrix/pixiebrix-extension/blob/6c2551acd86a2b5489982c67776860a2d9596558/.eslintrc.js#L15-L15

You have a couple options. 1) move the DEFAULT_THEME constant to a "types.ts" file in the options folder, 2) move shared code to a separate folder

**Review by twschiller — APPROVED** [review]
