### PR TITLE
#4935: disable brick buttons while deleting in Workshop

### LINKED ISSUE #4935: Workshop editor. Disable Delete button while sending request.
Workshop Editor allows multiple clicks on Delete button.

Steps to Reproduce:
1. Open a brick in Workshop
2. Click Delete button

**Expected**: the button is disable and/or loading indicator appears
**Actual**: I can click the Button several times sending multiple requests to the server.

### PR DESCRIPTION
**Pull request by BALEHOK**
## What does this PR do?

-  Fixes #4935 

## Demo

https://www.loom.com/share/92fecb9ac7d44a71b6298fb8f8557132

## Checklist

- [x] Add tests
- [x] Designate a primary reviewer @BLoe

### CODE REVIEW

File: src/options/pages/brickEditor/EditPage.tsx [hunk 1]
```diff
@@ -146,17 +161,18 @@ const EditForm: React.FC<{ id: UUID; data: Package }> = ({ id, data }) => {
...
-                      <Button disabled={!isValid || isSubmitting} type="submit">
+                      <Button
+                        disabled={!isValid || isSubmitting || isRemoving}
+                        type="submit"
+                      >
                         {values.public ? "Publish Brick" : "Update Brick"}
                       </Button>
                     </div>
                     <div>
                       <Button
```
Comment (twschiller) [inline src/options/pages/brickEditor/EditPage.tsx:172]: I'm assuming you didn't use AsyncButton here so that you could also disable the Submit button while deleting?

**Review by twschiller — APPROVED** [review]
