### PR TITLE
#5272 Fix Google Sheets file picker in sidebar mod activation flow

### LINKED ISSUE #5272: Google Sheet integration configuration not showing file picker in 1.7.20-alpha.2
Context
---
- https://pixiebrix.slack.com/archives/C02CN01JXAA/p1677610463203189

### PR DESCRIPTION
**Pull request by BLoe**
## What does this PR do?

- Fixes #5272 
- Adds some test coverage for the sheets UI

## Demo

https://www.loom.com/share/d1220ad7066843b9a7c5d744fad1f0eb

## Checklist

- [x] Add tests
- [x] Designate a primary reviewer - @twschiller

### CODE REVIEW

File: src/contrib/google/sheets/useCurrentOrigin.ts [hunk 1]
```diff
@@ -0,0 +1,59 @@
...
+      // page (i.e. the Page Editor)
+      isDevToolsPage() ||
+      // Check for the page editor pagePath in the location pathname
+      location.pathname === "/pageEditor.html"
+    ) {
+      return "devtools://devtools";
+    }
+
+    // Default to using the Chrome tabs API to get the active tab url
+    const tabs = await chrome.tabs.query({
```
Comment (twschiller) [inline src/contrib/google/sheets/useCurrentOrigin.ts:49]: Could we add a note here? Technically we might want to instead ping the background page and have it report back what the URL is

I suspect this is fine since the tab with the sidebar will be active when this code is run in this PR. But to be correct in all cases we'd not want to rely on the tab being active

**Review by twschiller — APPROVED** [review]
