### PR TITLE
#6275: clearing a property in the extract from page brick then blurring throws an error

### LINKED ISSUE #6275: Clearing a property in the Extract From Page brick then blurring throws an error
### Steps to Reproduce
1. Open the Page Editor
2. Edit an Extract From Page brick
3. Clear the property field
4. Blur the field

#### Actual Behavior
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcVVNIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--b0f56ab4cec219709c19611df3bd3f8599a3108b/image.png)

#### Expected Behavior
The field value should return to the defaultValue

### Context
https://pixiebrix.slack.com/archives/C0436P48QHY/p1692198871002769

### PR DESCRIPTION
**Pull request by grahamlangford**
## What does this PR do?

- Closes #6275

## Demo

https://www.loom.com/share/e2bf07f7fe014eaca895f5485c706b61

## Checklist

- [x] Add tests
- [x] Designate a primary reviewer @turbochef

### CODE REVIEW

File: src/bricks/transformers/jquery/JQueryReaderOptions.tsx [hunk 1]
```diff
@@ -251,10 +251,14 @@ const SelectorCard: React.FC<{
...
-                  name: event.target.value,
-                  selector: selectorDefinition,
-                });
+                if (event.target.value) {
+                  onChange({
+                    name: event.target.value,
+                    selector: selectorDefinition,
+                  });
+                } else {
+                  setName(initialName);
```
Comment (turbochef) [inline src/bricks/transformers/jquery/JQueryReaderOptions.tsx:260]: Are users allowed to have this be blank? I think it would make a better UX if we do 
```suggestion
                  setName("");
```
and add some validation error.

**Review by turbochef — APPROVED** [review]
Non-blocking UX question. Code looks good and fixes the bug. Approved 👍

File: src/bricks/transformers/jquery/JQueryReaderOptions.tsx (hunk 1 above)
Comment (grahamlangford) [reply src/bricks/transformers/jquery/JQueryReaderOptions.tsx:260]: The user is setting the name of a property on `@data`. It should never be blank.
