### PR TITLE
refresh AA token every 10 hours to avoid 24 hour expiration

### LINKED ISSUE #6603: Incorrect partner refresh interval
Context
---
- See "Refresh Token" email thread
- The refresh interval needs to be less than the access_token's lifetime to ensure that the access_token is refreshed

Related Code
---
- https://github.com/pixiebrix/pixiebrix-extension/blob/3aeeb4468c71734398b98b7f21dd209c0652ab59/src/background/partnerIntegrations.ts#L242-L242

### PR DESCRIPTION
**Pull request by grahamlangford**
## What does this PR do?

- Fixes #6603 

## Discussion

- Still need to confirm the token expires every 24 hours: https://pixiebrix.slack.com/archives/C042T2TBZ17/p1696957614998249

## Checklist

- [x] Designate a primary reviewer @johnnymetz

### CODE REVIEW

File: src/background/partnerIntegrations.ts [hunk 1]
```diff
@@ -232,12 +232,14 @@ export async function safeTokenRefresh(): Promise<void> {
   }
 }
 
+const TWENTY_THREE_HOURS = 1000 * 60 * 60 * 23;
+
 /**
- * The Automation Anywhere JWT has an absolute expiry of 30 days and an inactivity expiry of 15 days.
- * Refresh the JWT every week, so it doesn't expire after the inactivity period.
+ * The Automation Anywhere JWT acess token expires every 24 hours
```
Comment (johnnymetz) [inline src/background/partnerIntegrations.ts:238]: Nit: type: `access`

File: src/background/partnerIntegrations.ts [hunk 2]
```diff
@@ -232,12 +232,14 @@ export async function safeTokenRefresh(): Promise<void> {
...
+ * Refresh the JWT every 23 hours to avoid
```
Comment (johnnymetz) [inline src/background/partnerIntegrations.ts:239]: Nit: to avoid "what"?

File: src/background/partnerIntegrations.ts [hunk 3]
```diff
@@ -232,12 +232,14 @@ export async function safeTokenRefresh(): Promise<void> {
   }
 }
 
+const TWENTY_THREE_HOURS = 1000 * 60 * 60 * 23;
```
Comment (johnnymetz) [inline src/background/partnerIntegrations.ts:235]: I just confirmed the access token is valid for 24 hours 👍

File: src/background/partnerIntegrations.ts (hunk 2 above)
Comment (johnnymetz) [reply src/background/partnerIntegrations.ts:239]: Can you also keep how long the refresh token for, just for documentation purposes: see the old comment above: "absolute expiry of 30 days and an inactivity expiry of 15 days"
