### PR TITLE
#3113 Throw more informative error on malformed Nunjucks template

### LINKED ISSUE #3113: Throw more informative error on malformed Nunjucks template
Context
- Nunjucks throws inscrutable errors if it encounters a malformed template
- If a brick is using multiple templates, it's hard to track down which template is failing

Implementation Sketch:
- Wrap [the nunjucks](http://github.com/pixiebrix/pixiebrix-extension/blob/9c31084c12a86ed5a3976d19f1cbab467b0254c7/src/runtime/renderers.ts#L63-L63) renderer in a method that throws an InvalidTemplate error with the message and the template that contained the compilation error
- Add tests for malformed templates to [pipelineTests](http://github.com/pixiebrix/pixiebrix-extension/blob/9c31084c12a86ed5a3976d19f1cbab467b0254c7/src/runtime/pipelineTests#L1-L1)
- The InvalidTemplate error should subclass BusinessError: http://github.com/pixiebrix/pixiebrix-extension/blob/f9ea679ff467fa2341488b837dd03c757beed811/src/errors.ts#L107-L107
- Include the error under BUSINESS_ERROR_NAMES and BUSINESS_ERROR_CLASSES: http://github.com/pixiebrix/pixiebrix-extension/blob/f9ea679ff467fa2341488b837dd03c757beed811/src/errors.ts#L286-L286

Example: here's an error when a panel errors because one field in the panel is missing a closing bracket on the template expression:
image

Future Work:
- In the text template field toggle, can we pre-validate template syntax? Would we use setError on the Formik state?

### PR DESCRIPTION
**Pull request by BALEHOK**
Closes #3113

### CODE REVIEW

File: src/errors.ts [hunk 1]
```diff
@@ -281,6 +292,7 @@ const BUSINESS_ERROR_CLASSES = new Set([
   MultipleElementsFoundError,
   InvalidSelectorError,
   PropError,
+  InvalidTemplateError,
```
Comment (twschiller) [inline src/errors.ts:295]: 👍

**Review by twschiller — APPROVED** [review]
@BALEHOK looks good. Just one comment on truncating the template
