### PR TITLE
#2269 Fix bug with formik helper reference changing

### LINKED ISSUE #2269: Some schema fields improperly show a loading indicator and don't set a value in the block config
Reproducible example:
1. Add a new button
2. Add the `Send Deployment Message` brick

image

The `message` field doesn't get set in the block config:

image

### PR DESCRIPTION
**Pull request by BLoe**
Fixes #2269

### CODE REVIEW

File: src/devTools/editor/hooks/useToggleFormField.tsx [hunk 1]
```diff
@@ -54,7 +54,7 @@ function useToggleFormField(
   const {
     values: formState,
     setValues: setFormState,
-  } = useFormikContext<UnknownObject>();
+  } = useFormikContext<FormState>();
```
Comment (BLoe) [inline src/devTools/editor/hooks/useToggleFormField.tsx:57]: Also just noticed the generic object type here and updated it to use the proper `FormState` type

**Review by twschiller — APPROVED** [review]
