### PR TITLE
#4996: Highlight Text Brick: don't highlight text in the head of the document

### LINKED ISSUE #4996: Highlight Text Brick: don't highlight text in the head of the document
Steps to Reproduce
--- 
- Add Highlight Text brick
- Set it to highlight "PixieBrix"
- Visit Admin Console
- Observe that tab title won't show properly because the title has been wrapped in a span

### PR DESCRIPTION
**Pull request by fregante**
## What does this PR do?

- Fixes #4996

## Checklist

- [x] Add tests
- [x] Designate a primary reviewer: @twschiller

### CODE REVIEW

File: src/blocks/effects/highlight.ts [hunk 1]
```diff
@@ -14,6 +14,7 @@
  * You should have received a copy of the GNU Affero General Public License
```
Comment (fregante) [inline src/blocks/effects/highlight.ts:14]: I made changes to this effect but feel free to discard them if it's deprecated. We should probably mark it as such if it is.

Alternatively I can fix the same bug in this file too, it's 1 line after `documentRoot`

File: src/blocks/effects/highlight.ts [hunk 2]
```diff
@@ -130,36 +131,30 @@ export class HighlightEffect extends Effect {
...
-      $roots = rootSelector ? $safeFind(rootSelector) : $(document);
-    } else {
-      $roots = rootSelector ? $safeFind(rootSelector, root) : $(root);
-    }
-
     if (condition !== undefined && !boolean(condition)) {
       return;
     }
 
-    $roots.each(function () {
```
Comment (fregante) [inline src/blocks/effects/highlight.ts:145]: jQuery already loops internally

File: src/blocks/effects/highlight.ts (hunk 1 above)
Comment (twschiller) [reply src/blocks/effects/highlight.ts:14]: The effect isn't deprecated, it just has some deprecated inputs

**Review by twschiller — APPROVED** [review]
