### PR TITLE
#7208: Restore background worker in MV3

### LINKED ISSUE #7208: Background worker not starting on MV3 build
Steps to Reproduce
---
- Download `build-production-3` from https://github.com/pixiebrix/pixiebrix-extension/actions/runs/7315969068
- Load the extension
- Background service worker shows as not started

Discussion
---
- It might be caused by a transitive import to the hover intent code? Or: https://github.com/pixiebrix/pixiebrix-extension/issues/7209
 
Screenshots
---
image

image

Related Issues
---
- https://github.com/pixiebrix/pixiebrix-extension/issues/7209

### PR DESCRIPTION
**Pull request by fregante**
## What does this PR do?

- Fixes #7208

## Future Work

- [ ] https://github.com/pixiebrix/pixiebrix-extension/issues/7185

## Checklist

- [x] Designate a primary reviewer: @grahamlangford

### CODE REVIEW

File: src/background/browserAction.ts [hunk 1]
```diff
@@ -43,13 +43,12 @@ async function _toggleSidebar(tabId: number, tabUrl: string): Promise<void> {
   // Load the raw toggle script first, then the content script. The browser executes them
   // in order, but we don't need to use `Promise.all` to await them at the same time as we
   // want to catch each error separately.
-  // Call browser.tabs.executeScript instead of using webext-content-scripts:executeScript because we need to
-  // await the script running. See https://github.com/fregante/webext-content-scripts/issues/22
-  const sidebarTogglePromise = browser.tabs.executeScript(tabId, {
-    file: "browserActionInstantHandler.js",
```
Comment (fregante) [inline src/background/browserAction.ts:49]: That issue was resolved, `webext-content-scripts` is useful to bridge the gap between MV2 and MV3

File: .eslintrc.js [hunk 2]
```diff
@@ -71,7 +71,7 @@ module.exports = {
           "@/telemetry/reportUncaughtErrors",
           "@testing-library/jest-dom",
           "regenerator-runtime/runtime", // Automatic registration
-          "@/vendors/hoverintent/hoverintent", // JQuery plugin
+          "@/vendors/hoverintent", // JQuery plugin
```
Comment (fregante) [inline .eslintrc.js:74]: Moved the file out of its single-file folder.

File: src/vendors/hoverintent.js [hunk 3]
```diff
@@ -43,6 +43,11 @@
 })(function ($) {
   "use strict";
 
+  // jQuery loaded in a non-document context
+  if (!$.fn) {
+    return;
+  }
```
Comment (fregante) [inline src/vendors/hoverintent.js:49]: Quick change, but eventually we'd want to avoid loading bricks and other unrelated code in the background script, so that we don't have to litter the code with these conditions.

**Review by fregante — COMMENTED** [review]
I tested:

- the page editor
- the sidebar
- the options page
- adding buttons
- running bricks
- in-page notifications
- tour

✅

**Review by twschiller — APPROVED** [review]
