### PR TITLE
#2021: fix bug in iframe sanitization

### LINKED ISSUE #2021: iframe renderer brick broken in sidebar
Related:
- #1975 
- #1990

### PR DESCRIPTION
**Pull request by twschiller**
Closes #2021 

- Fixes a bug introduced in PanelBody where we were sanitizing the HTML which broke our iframe renderer
- I updated RenderedHTML to have a nominal type so we can track explicitly where we're passing around sanitized HTML

### CODE REVIEW

File: src/blocks/renderers/common.ts [hunk 1]
```diff
@@ -44,13 +44,15 @@ export async function errorBoundary(
...
-      return '<div style="color: red;">Expected a renderer brick</div>';
+      return '<div style="color: red;">Expected a renderer brick</div>' as SafeHTML;
     }
 
     // TODO: validate the shape of the value returned
     return value;
   } catch (error) {
     logger.error(error);
-    return `<div>An error occurred: ${getErrorMessage(error)}</div>`;
+    return `<div>An error occurred: ${getErrorMessage(
```
Comment (fregante) [inline src/blocks/renderers/common.ts:54]: If the error message contains raw HTML, it will be injected, so it's not safe in this case. Example:

```
Element <a> was not found
```

File: src/blocks/renderers/iframe.ts [hunk 2]
```diff
@@ -60,15 +60,29 @@ export class IFrameRenderer extends Renderer {
...
+    title?: string;
+    height?: string;
+    width?: string;
+    safeMode?: boolean;
+  }>): Promise<SafeHTML> {
+    const parsedURL = new URL(url);
+
     if (safeMode) {
-      return `<iframe src="${url}" title="${title}" height="${height}" width="${width}" style="border:none;" allowfullscreen="false" allowpaymentrequest="false"></iframe>`;
+      return `<iframe src="${parsedURL.toString()}" title="${title}" height="${height}" width="${width}" style="border:none;" allowfullscreen="false" allowpaymentrequest="false"></iframe>` as SafeHTML;
```
Comment (fregante) [inline src/blocks/renderers/iframe.ts:74]: Alternatively, to convert a URL into a string:

```suggestion
      return `<iframe src="${parsedURL.href}" title="${title}" height="${height}" width="${width}" style="border:none;" allowfullscreen="false" allowpaymentrequest="false"></iframe>` as SafeHTML;
```

**Review by fregante — APPROVED** [review]
From a very quick look, the change makes sense!

File: src/blocks/renderers/common.ts (hunk 1 above)
Comment (twschiller) [reply src/blocks/renderers/common.ts]: Good catch!
