### PR TITLE
#5998: check for other panels for the mod on remove

### LINKED ISSUE #5998: Closing a temporary tab jumps you to the wrong mod
When a user has multiple tabs open in the sidebar and clicks on something that opens a new tab, when they close the tab, it takes them back to a different tab then the one that launched it. It should go back to the last one that was open.

https://www.loom.com/share/69843fc279fd44e9a197c9a8285e2456

[Related Notion](https://www.notion.so/pixiebrix/Closing-a-temporary-tab-doesn-t-return-you-to-the-mod-that-you-were-on-6fddfbeb2bf546539bdcf63022b1902a)

### PR DESCRIPTION
**Pull request by grahamlangford**
## What does this PR do?

- Closes #5998

## Discussion

- [Slack Discussion Thread](https://pixiebrix.slack.com/archives/C023KL47XV4/p1688405282167619)

## Demo
https://www.loom.com/share/f9e3c9282fe34aba85056fd23ed77ef8

## Checklist

- [ ] Add tests
- [x] Designate a primary reviewer @BLoe

### CODE REVIEW

File: src/sidebar/sidebarSlice.ts [hunk 1]
```diff
@@ -153,16 +153,30 @@ async function resolvePanel(
...
-    // See: https://github.com/immerjs/immer/issues/839
-    // @ts-expect-error -- SidebarEntries.panels --> PanelEntry.actions --> PanelButton.detail is JsonObject
-    state.activeKey = defaultEventKey(state);
+    const prevPanel = [
+      ...state.forms,
+      ...state.panels,
+      ...state.temporaryPanels,
+    ].find(({ extensionId }) => {
+      if ("extensionId" in removedEntry) {
+        return extensionId === removedEntry.extensionId;
```
Comment (twschiller) [inline src/sidebar/sidebarSlice.ts:168]: This isn't quite right, we also need to look for blueprintId as well in order to cover the scenario where there's a persistent side bar

File: src/types/sidebarTypes.ts [hunk 2]
```diff
@@ -195,7 +195,7 @@ export type FormPanelEntry = BasePanelEntry & {
    *
    * @since 1.7.33
    */
-  blueprintId: RegistryId;
```
Comment (twschiller) [inline src/types/sidebarTypes.ts]: I recommend we use `RegistryId | null` if the property is always present, but it can be nullish.

Comment (grahamlangford) [reply src/types/sidebarTypes.ts]: Just updated that with my latest commit.

File: src/sidebar/sidebarSlice.ts [hunk 3]
```diff
@@ -153,16 +153,42 @@ async function resolvePanel(
...
+      ...state.temporaryPanels,
+    ].filter(({ extensionId }) => {
+      if ("extensionId" in removedEntry) {
+        return extensionId === removedEntry.extensionId;
+      }
+
+      return false;
+    });
+
+    const matchingMod = matchingExtensions.find(({ blueprintId }) => {
```
Comment (twschiller) [inline src/sidebar/sidebarSlice.ts:174]: This doesn't seem right - why is this only searching within matchingExtensions? The point of the mod check is to look for panels from other IExtensions that are from the same mod

File: src/sidebar/sidebarSlice.test.ts [hunk 4]
```diff
@@ -178,3 +232,133 @@ describe("sidebarSlice.addForm", () => {
...
+    const modId = validateRegistryId("test/123");
+
+    const originalPanel = sidebarEntryFactory("panel", {
+      extensionId,
+      blueprintId: validateRegistryId("test/456"),
+    });
+    const firstFormPanel = sidebarEntryFactory("form", {
+      extensionId,
+    });
+    const matchingFormPanel = sidebarEntryFactory("form", {
```
Comment (twschiller) [inline src/sidebar/sidebarSlice.test.ts:276]: This test should vary the extensionId but keep the mod id the same

File: src/sidebar/sidebarSlice.ts (hunk 3 above)
Comment (twschiller) [reply src/sidebar/sidebarSlice.ts:174]: See comment here on the test: https://github.com/pixiebrix/pixiebrix-extension/pull/6018/files#r1253102863

File: src/sidebar/sidebarSlice.ts [hunk 5]
```diff
@@ -153,16 +153,42 @@ async function resolvePanel(
...
   // Only update the active panel if the panel needs to change
   if (removedEntry && state.activeKey === eventKeyForEntry(removedEntry)) {
-    // Immer Draft<T> type resolution can't handle JsonObject (recursive) types properly
-    // See: https://github.com/immerjs/immer/issues/839
-    // @ts-expect-error -- SidebarEntries.panels --> PanelEntry.actions --> PanelButton.detail is JsonObject
-    state.activeKey = defaultEventKey(state);
+    const panels = [...state.forms, ...state.panels, ...state.temporaryPanels];
+
+    const matchingExtension = panels.find(({ extensionId }) => {
+      if ("extensionId" in removedEntry) {
```
Comment (twschiller) [inline src/sidebar/sidebarSlice.ts:165]: NIT: simplify as 
```
panels.find(({ extensionId }) => "extensionId" in removedEntry && extensionId === removedEntry.extensionId)
```

File: src/sidebar/sidebarSlice.ts [hunk 6]
```diff
@@ -153,16 +153,42 @@ async function resolvePanel(
...
+    });
+
+    if (matchingExtension) {
+      // Immer Draft<T> type resolution can't handle JsonObject (recursive) types properly
+      // See: https://github.com/immerjs/immer/issues/839
+      // @ts-expect-error -- SidebarEntries.panels --> PanelEntry.actions --> PanelButton.detail is JsonObject
+      state.activeKey = eventKeyForEntry(matchingExtension);
+    } else {
+      const matchingMod = panels.find(({ blueprintId }) => {
+        if ("blueprintId" in removedEntry && removedEntry.blueprintId) {
```
Comment (twschiller) [inline src/sidebar/sidebarSlice.ts:179]: NIT: adding a comment here that you need to check for `removedEntry.blueprintId` to avoid switching between IExtensions that don't have blueprint ids would be helpful

Comment (twschiller) [reply src/sidebar/sidebarSlice.ts:179]: NIT: Some comment as above to just use the expression: https://github.com/pixiebrix/pixiebrix-extension/pull/6018/files#r1253146215

**Review by twschiller — APPROVED** [review]
👍  Logic looks correct, see comments on using expressions in the find clauses. I personally find that more readable, as `return` statements you have to double-check they're within the find and not an early return in the method

File: src/sidebar/sidebarSlice.test.ts (hunk 4 above)
Comment (grahamlangford) [reply src/sidebar/sidebarSlice.test.ts]: fixed

File: src/sidebar/sidebarSlice.ts (hunk 3 above)
Comment (grahamlangford) [reply src/sidebar/sidebarSlice.ts]: fixed

File: src/sidebar/sidebarSlice.ts [hunk 7]
```diff
@@ -161,27 +161,24 @@ export function fixActiveTabOnRemove(
...
-      const matchingMod = panels.find(({ blueprintId }) => {
-        if ("blueprintId" in removedEntry && removedEntry.blueprintId) {
-          return blueprintId === removedEntry.blueprintId;
-        }
-
-        return false;
-      });
+      const matchingMod = panels.find(
+        ({ blueprintId }) =>
+          "blueprintId" in removedEntry &&
```
Comment (twschiller) [inline src/sidebar/sidebarSlice.ts:178]: I think you need to check for blueprintId is not null?
