### PR TITLE
#9257: fix heartbeat telemetry regression

### LINKED ISSUE #9257: Invalid mod version number passed in heartbeat
## Describe the bug

- Regression in 2.1.5-beta.2
- https://pixiebrix.slack.com/archives/C0436P48QHY/p1728476815729479

### PR DESCRIPTION
**Pull request by twschiller**
## What does this PR do?

- Closes #9257

## Checklist

- [ ] Cut/submit a beta to CWS beta channel

## Future Work

- Fix type safety of `ModDefinition.metadata.version`: https://github.com/pixiebrix/pixiebrix-extension/issues/9259

For more information on our expectations for the PR process, see the
[code review principles doc](https://www.notion.so/pixiebrix/Code-Review-Principles-1ce7276b82a84d2a995d55ad85e1310d?pvs=4)

### CODE REVIEW

File: src/utils/deploymentUtils.ts [hunk 1]
```diff
@@ -150,11 +150,15 @@ export function selectActivatedDeployments(
...
-        deployment: x.deploymentMetadata!.id,
-        blueprint: x.definition.metadata.id,
-        blueprintVersion: x.definition.metadata.id,
+        deployment: modInstance.deploymentMetadata!.id,
+        blueprint: modInstance.definition.metadata.id,
+        // In practice, all activated mods must have a version. But be defensive given that Metadata type used by
+        // ModDefinition does not currently require version.
+        blueprintVersion:
+          modInstance.definition.metadata.version ??
+          normalizeSemVerString("0.0.0"),
```
Comment (fungairino) [inline src/utils/deploymentUtils.ts:161]: nit: why "0.0.0" vs "1.0.0"?

It seems like we do this defaulting logic in a couple of different places so it might be worth looking into if we can make this a non-optional field upstream.

File: src/utils/deploymentUtils.ts [hunk 2]
```diff
@@ -150,11 +150,15 @@ export function selectActivatedDeployments(
   return uniqBy(
     modInstances
       .filter((x) => x.deploymentMetadata != null)
-      .map((x) => ({
+      .map((modInstance) => ({
```
Comment (fungairino) [inline src/utils/deploymentUtils.ts:153]: Seems like we are missing some coverage for `selectActivatedDeployments`. Would be good to consider writing a simple set of unit tests.

File: src/utils/deploymentUtils.ts (hunk 1 above)
Comment (twschiller) [reply src/utils/deploymentUtils.ts:161]: > nit: why "0.0.0" vs "1.0.0"?

So on the backend it's easier to see if it's defaulted or not

> It seems like we do this defaulting logic in a couple of different places so it might be worth looking into if we can make this a non-optional field upstream.

I agree - see the future work ticket calling out fixing the upstream types
