### PR TITLE
#6955: google drive version of starter mods not installing

### LINKED ISSUE #6955: Google Drive version of starter mods not installing
## Describe the bug

On Monday, Nov 20, 2023, we updated the Starter Mods (AI Copilot, Writing Assist, KB Assist) to use the new optional Google Drive integration schema in the workshop. 

Since then, every Rainforest QA test that relies on the starter mods installing correctly and/or redirecting to the welcome page from the Admin Console has failed.

In Mixpanel:
- No `OnboardingStarterModsActivateSuccess` events after the update
- No `OnboardingStarterModsActivateFailed` events either
- Instead we're seeing `OnboardingStarterModsActivateStart` followed by `OnboardingStarterModsActivateSkipped`

We verified the cause is the change to the mods by reverting the mods to the previous version. After which, the installation and redirects began working again.

## To Reproduce

1. Open the Workshop
2. Update one or more of the starter mods to use the new optional Google Drive integration schema
3. Ensure you do not have any of the starter mods installed
4. Navigate to https://www.pixiebrix.com/welcome

## Actual behavior

The starter mods are not installed correctly and `OnboardingStarterModsActivateSuccess` is not reported in Mixpanel

## Expected behavior

The starter mods are all installed correctly, and `OnboardingStarterModsActivateSuccess` is reported to Mixpanel

## Desktop (please complete the following information):

- Extension Version: 1.8.3

## Additional context

- https://github.com/pixiebrix/pixiebrix-app/blob/43f50b13688726a0a5fea8621af0848ac9cdca16/pixiebrix-app/src/pages/onboarding/onboardingFlows.tsx#L231

- What mod(s) were you running?
  - `@pixies/support/knowledge-base-copilot @1.4.10`
  - `@pixies/ai/writer-assist @2.2.3`
  - `@pixies/ai/chatgpt-sidebar @4.1.11`
- What website(s) were you using?
  - https://www.pixiebrix.com/welcome

### PR DESCRIPTION
**Pull request by grahamlangford**
## What does this PR do?

- Fixes #6955 
- _Are there other changes (e.g., refactoring) included that aren’t from the ticket?_

## Demo

https://www.loom.com/share/1ea8b099d2bc4933936cb1480e12b1b6

## Checklist

- [x] Add tests
- [ ] New files added to `src/tsconfig.strictNullChecks.json` (if possible)
- [x] Designate a primary reviewer @BLoe

### CODE REVIEW

File: src/background/starterMods.ts [hunk 1]
```diff
@@ -88,9 +88,15 @@ async function installMods(modDefinitions: ModDefinition[]): Promise<boolean> {
...
       extensionPoints: modDefinitions.flatMap((mod) => mod.extensionPoints),
     });
+
   const builtInIntegrationConfigs = await getBuiltInIntegrationConfigs();
+
   const builtInDependencies = unconfiguredIntegrationDependencies.map(
     (unconfiguredDependency) => {
+      if (unconfiguredDependency.isOptional) {
+        return unconfiguredDependency;
+      }
```
Comment (grahamlangford) [inline src/background/starterMods.ts:98]: This is the actual bugfix

Comment (grahamlangford) [reply src/background/starterMods.ts:98]: Can a builtInIntegrationConfig be optional? Should we make this check later in the function?

**Review by BLoe — APPROVED** [review]
