### PR TITLE
#5764: fixes extension console icons

### LINKED ISSUE #5764: Bug: Extension console icon shows blocks instead of Marketplace icon
Activating LinkedIn Message Templates via the extension console shows the three blocks icon, but the Marketplace listing has it with the LinkedIn icon\. It should be using the same icon in the extension console as in the Marketplace\.

<p></p>

<p></p>

<p></p>

Additional Context: <https://pixiebrix.slack.com/archives/C057XU5V2G4/p1684523996319049>

<p></p>

From Todd:  
[https:\/\/github\.com\/pixiebrix\/pixiebrix\-extension\/blob\/7e142985d340b426b8b2c59560c8\[…\]rc\/extensionConsole\/pages\/activateRecipe\/ActivateRecipeCard\.tsx](https://github.com/pixiebrix/pixiebrix-extension/blob/7e142985d340b426b8b2c59560c8[…]rc/extensionConsole/pages/activateRecipe/ActivateRecipeCard.tsx)

<p></p>

### PR DESCRIPTION
**Pull request by grahamlangford**
## What does this PR do?

- Fixes #5764
- updates apiClient to use params

## Checklist

- [x] Add tests
- [x] Designate a primary reviewer

### CODE REVIEW

File: src/extensionConsole/pages/activateRecipe/ActivateRecipeCard.tsx [hunk 1]
```diff
@@ -88,6 +96,8 @@ const ActivateRecipeCard: React.FC = () => {
     },
   };
 
+  const recipeListing = listings[recipeId] ?? null;
```
Comment (twschiller) [inline src/extensionConsole/pages/activateRecipe/ActivateRecipeCard.tsx:99]: NIT: could put this in `listing={listings[recipeId] ?? null}` instead of introducing new local variable

The `?? null` is also redundant

File: src/services/api.test.tsx [hunk 2]
```diff
@@ -102,4 +104,26 @@ describe("appBaseQuery", () => {
     // The type definition is incorrect: https://github.com/axios/axios/pull/5331
     expect(axiosError.status).toBeUndefined();
   });
+
+  test("RTK forwards params to axios", async () => {
```
Comment (twschiller) [inline src/services/api.test.tsx:108]: ❤️

File: src/extensionConsole/pages/activateRecipe/ActivateRecipeCard.tsx (hunk 1 above)
Comment (grahamlangford) [reply src/extensionConsole/pages/activateRecipe/ActivateRecipeCard.tsx:99]: I was imitating code from the GetStartedView. I also thought it was redundant, but thought there might be a reason I didn't know about. I'll make the change.
