### PR TITLE
#4210: fix AA partner control room setup flow

### LINKED ISSUE #4209: Extension does not have access to make Control Room OAuth2 call during onboarding
Context
---
- On a fresh install, the browser extension does not have permission to call the Auth0 endpoints or Control Room to authenticate
- The form fails silently for the user

Implementation Sketch
---
- Request the permissions for the service prior to authentication. (This will prompt the user, the IT admin can pre-allocate)
- Show an error notification if an error occurs when submitting the Connect AARI onboarding form

Console Warning
---
```
An unhandled error was caught from submitForm() Error: Error getting OAuth2 token: Insufficient browser permissions to make request.
```

### LINKED ISSUE #4210: Extension doesn't pass Control Room URL header with JWT
Related Code
---
- https://github.com/pixiebrix/pixiebrix-extension/blob/e09c6e28eeaab3f1e1403b1ceb5cefd491302d7b/src/background/partnerIntegrations.ts#L109-L109

### PR DESCRIPTION
**Pull request by twschiller**
## What does this PR do?

- Closes #4210 
- Closes #4209

## Reviewer Notes
- The getOrigins method for services does include the `/token` and `/authorize` URLs for OAuth2 integrations (along with the base URL): https://github.com/pixiebrix/pixiebrix-extension/blob/8802f394eb6e7f71c519078c4e20e5139070ae17/src/services/factory.ts#L134-L134

## Blockers
- https://github.com/pixiebrix/pixiebrix-app/issues/2228

## Checklist

- [X] Manually test onboarding flow. I verified the login flow and that it's properly including the headers post login
- [X] 😐  Add tests
- [X] Designate a primary reviewer: @johnnymetz

### CODE REVIEW

File: src/auth/token.ts [hunk 1]
```diff
@@ -96,10 +96,10 @@ export async function getAuthHeaders(): Promise<UnknownObject | null> {
 
   if (partnerAuth?.token) {
     return {
-      ...partnerAuth?.extraHeaders,
+      ...partnerAuth.extraHeaders,
```
Comment (twschiller) [inline src/auth/token.ts:99]: Removes unnecessary "?"

File: src/background/partnerIntegrations.ts [hunk 2]
```diff
@@ -86,22 +89,31 @@ export async function launchAuthIntegration({
...
+  const config = await serviceLocator.getLocalConfig(localAuths[0].id);
   const data = await launchOAuth2Flow(service, config);
 
   if (serviceId === CONTROL_ROOM_OAUTH_SERVICE_ID) {
     // Hard-coding headers for now. In the future, will want to add support for defining in the service definition.
+
+    if (isEmpty(config.config.controlRoomUrl)) {
+      // Fine to dump to console for debugging because CONTROL_ROOM_OAUTH_SERVICE_ID doesn't have any secret props.
+      console.warn("controlRoomUrl is missing on configuration", config);
+      throw new Error("controlRoomUrl is missing on configuration");
```
Comment (twschiller) [inline src/background/partnerIntegrations.ts:114]: Defensive coding

File: src/options/pages/onboarding/partner/ControlRoomOAuthForm.tsx [hunk 3]
```diff
@@ -49,24 +53,47 @@ const ControlRoomOAuthForm: React.FunctionComponent<{
...
   const connect = useCallback(
-    async (values: ControlRoomConfiguration) => {
-      if (!configuredServices.some((x) => x.serviceId === authServiceId)) {
-        dispatch(
-          updateServiceConfig({
-            id: uuidv4(),
-            serviceId: CONTROL_ROOM_OAUTH_SERVICE_ID,
-            label: "Primary AARI Account",
-            config: {
-              controlRoom: values.controlRoomUrl,
```
Comment (twschiller) [inline src/options/pages/onboarding/partner/ControlRoomOAuthForm.tsx:60]: This was the bug. One the deployed OAuth2 integration, the field is controlRoomUrl

File: src/options/pages/onboarding/partner/ControlRoomOAuthForm.tsx [hunk 4]
```diff
@@ -49,24 +53,47 @@ const ControlRoomOAuthForm: React.FunctionComponent<{
...
+            })
+          );
+
+          // Ensure the service is available to background page (where launchAuthIntegration runs)
+          await persistor.flush();
+        }
 
-      await launchAuthIntegration({ serviceId: authServiceId });
+        // Ensure PixieBrix can call the Control Room and OAuth2 endpoints
+        const requiredPermissions = await serviceOriginPermissions({
```
Comment (twschiller) [inline src/options/pages/onboarding/partner/ControlRoomOAuthForm.tsx:86]: This is the fix for the permissions bug

**Comment by twschiller** [comment]
@jcforest To recap our call, here's what we need for this PR:

- [ ] Run selector generation from the  content script instead of the page script when framework is not provided (to avoid the Salesforce issue with differences in selection behavior)
- [ ] Define a constant SALESFORCE_SELECTOR_RULES, with the following:
      - Selector to determine if the site is a Salesforce lightening interface (i.e., if the heuristics should be applied), i.e., the "site rule"
      - Array of selector patterns to denylist, e.g., patterns including the data-aura-rendered-by attribute
      - Array of known good selector patterns
      - Array of known good stable anchors on the page
- [ ] Modify the inference to take into account these site-specific rules if the site rule matches

**Comment by jcforest** [comment]
@twschiller I think you wrote comment in wrong PR.

**Comment by twschiller** [comment]
> I think you wrote comment in wrong PR.

Thanks, will add to the correct PR

File: src/services/factory.test.ts [hunk 5]
```diff
@@ -16,11 +16,43 @@
...
+    const service = fromJS(
+      automationAnywhereOAuth2 as unknown as ServiceDefinition
+    );
+    const origins = service.getOrigins({
+      controlRoomUrl: "https://controlroom.example.com",
+    } as unknown as SanitizedConfig);
+
+    expect(origins).toEqual([
+      "https://controlroom.example.com/*",
+      "https://dev-5ufv3jh0.us.auth0.com/authorize?organization=org_55te9GGDwlzAS1PB&audience=https://dev-5ufv3jh0.us.auth0.com/userinfo",
```
Comment (johnnymetz) [inline src/services/factory.test.ts:40]: Small nit: `audience` is `https://controlroom ` now

**Comment by johnnymetz** [comment]
Just reviewed and looks good.

File: src/services/factory.test.ts (hunk 5 above)
Comment (twschiller) [reply src/services/factory.test.ts:40]: 👍  Shouldn't matter for the test case/behavior though as that param never gets parsed
