### PR TITLE
#2900: Avoid duplicate reporting in menuItemExtension

### LINKED ISSUE #2900: Menu Item extension point double reporting to Rollbar (and one is at wrong level)
Steps to Reproduce
- Add a BusinessError to a menu item extension
- Run the extension

Actual Behavior
- Reported twice to Rollbar: a) once as debug level with the BusinessError, and b) once at error level with message "Error running action"
- Notify the user with 

Expected Behavior
- Reported once to rollbar at debug level with the BusinessError

Implementation Sketch
- Suppress notifyResult from reporting error here by passing includeErrorDetails=false: http://github.com/pixiebrix/pixiebrix-extension/blob/04e410723ef92330d0be1ffc07b0568a183566b9/src/extensionPoints/menuItemExtension.ts#L564-L564
- Is this also going to report the error multiple times?: http://github.com/pixiebrix/pixiebrix-extension/blob/04e410723ef92330d0be1ffc07b0568a183566b9/src/extensionPoints/menuItemExtension.ts#L737-L737

What other locations are impacted?

### PR DESCRIPTION
**Pull request by fregante**
- Closes #2900

Related:

- https://github.com/pixiebrix/pixiebrix-extension/pull/2102
- https://github.com/pixiebrix/pixiebrix-extension/pull/2836
- https://github.com/pixiebrix/pixiebrix-extension/pull/2867

### CODE REVIEW

**Comment by fregante** [comment]
I think these are the only affected lines, at least around these APIs:

- notifyError
- notifyErrors
- notifyResult

They used to map directly to jQuery.notify without reporting the error anywhere. My recent PR added automatic error reporting to all notifications so there might be more elsewhere, but I think I checked those in my last PR (these already used the new API)

File: src/telemetry/BackgroundLogger.ts [hunk 1]
```diff
@@ -71,8 +71,7 @@ class BackgroundLogger implements Logger {
   }
 
   async error(error: unknown, data: JsonObject): Promise<void> {
-    console.error("An error occurred: %s", getErrorMessage(error), {
-      error,
+    console.error(error, {
```
Comment (fregante) [inline src/telemetry/BackgroundLogger.ts:74]: ### Before

Screen Shot 28

### After
Screen Shot 25

File: src/extensionPoints/triggerExtension.ts [hunk 2]
```diff
@@ -401,23 +413,14 @@ export abstract class TriggerExtensionPoint extends ExtensionPoint<TriggerConfig
 
     // The caller will have already waited for the element. So $element will contain at least one element
     if (this.attachMode === "once") {
-      for (const element of $element.get()) {
-        void this.runTrigger(element);
-      }
-
+      void this.runTriggersAndNotify(...$element);
```
Comment (fregante) [inline src/extensionPoints/triggerExtension.ts:416]: In this mode, `notify` was never called

File: src/extensionPoints/triggerExtension.ts [hunk 3]
```diff
@@ -372,9 +386,7 @@ export abstract class TriggerExtensionPoint extends ExtensionPoint<TriggerConfig
 
       const intervalEffect = async () => {
         const $root = await this.getRoot();
-        await Promise.allSettled(
-          $root.toArray().flatMap(async (root) => this.runTrigger(root))
-        );
+        await this.runTriggersAndNotify(...$root);
```
Comment (fregante) [inline src/extensionPoints/triggerExtension.ts:389]: In this mode, `notify` was never called

File: src/extensionPoints/triggerExtension.ts [hunk 4]
```diff
@@ -324,14 +323,29 @@ export abstract class TriggerExtensionPoint extends ExtensionPoint<TriggerConfig
     return compact(errors);
   }
 
-  static notifyErrors(results: Array<PromiseSettledResult<unknown[]>>): void {
-    const errors = compact(
-      results.flatMap((x) => (x.status === "fulfilled" ? x.value : [x.reason]))
+  private async runTriggersAndNotify(...roots: ReaderRoot[]): Promise<void> {
```
Comment (fregante) [inline src/extensionPoints/triggerExtension.ts:327]: This code was at least partially repeated in 3 places, so I merged it under a single method. However no errors actually ever reach this point due to https://github.com/pixiebrix/pixiebrix-extension/issues/2900#issuecomment-1061493695

File: src/utils/notify.tsx [hunk 5]
```diff
@@ -185,7 +185,11 @@ export function notifyResult(
   extensionId: string,
   { message, config: { className } }: MessageConfig
 ): void {
-  showNotification({ message, type: className as NotificationType });
+  showNotification({
+    message,
+    type: className as NotificationType,
+    reportError: false,
```
Comment (fregante) [inline src/utils/notify.tsx:191]: This restored the old _no-report_ behavior of `notifyResult`. 

Since this function called by a brick which depends on the `jQuery.notify` types, I have not fully refactored the function. We should probably look into it at some point. Added to https://github.com/pixiebrix/pixiebrix-extension/issues/2865#issue-1159399508

File: src/telemetry/BackgroundLogger.ts (hunk 1 above)
Comment (twschiller) [inline src/telemetry/BackgroundLogger.ts:74]: In practice this should be OK (because this should always be an object). But technically this is not safe/correct because you want to avoid user-defined format strings. In the case of console.log, I think the worst they can do is make the message non-sense

File: src/telemetry/BackgroundLogger.ts [hunk 6]
```diff
@@ -71,10 +71,18 @@ class BackgroundLogger implements Logger {
   }
 
   async error(error: unknown, data: JsonObject): Promise<void> {
-    console.error(error, {
-      context: this.context,
-      data,
-    });
+    if (typeof error === "string") {
+      // Avoid user-defined format strings
+      console.error("%s", error, {
```
Comment (fregante) [inline src/telemetry/BackgroundLogger.ts:76]: This solution is ok for now, why is the user able to throw strings? We should wrap them as soon as possible I think.

Comment (twschiller) [reply src/telemetry/BackgroundLogger.ts:76]: Theoretically the user isn't able to throw strings. However, the type of error is `unknown`, so from a defensive coding perspective you want to either: 1) update the type to be accurate, or 2) handle the possibilities

Comment (fregante) [reply src/telemetry/BackgroundLogger.ts:76]: We can use `selectError` in that case to ensure we have a real Error (it wraps strings in `new Error`)

Comment (fregante) [reply src/telemetry/BackgroundLogger.ts:76]: I'm kinda surprised and annoyed that `console.log` supports this stuff with random strings 😂

**Review by twschiller — APPROVED** [review]
