### PR TITLE
#5703 Add `searchQuery` to Mod Page table dependencies

### LINKED ISSUE #5703: Regression: can't search in extension console
Context
---
- Seen in 1.7.27-beta.4 and potentially before

### PR DESCRIPTION
**Pull request by mnholtz**
## What does this PR do?

- Fixes #5703 
- @twschiller and I aren't 100% sure why this was working before without the dependency added
- Adds a unit test to confirm searchQuery responsiveness

## Discussion

- I attempted to add a test with installables populated with test data, but ran into some snags that I think are still out of scope

## Checklist

- [x] Add tests
- [x] Designate a primary reviewer @twschiller

### CODE REVIEW

File: src/extensionConsole/pages/blueprints/BlueprintsPageLayout.tsx [hunk 1]
```diff
@@ -146,7 +146,7 @@ const BlueprintsPageLayout: React.FunctionComponent<{
             globalFilter: searchQuery,
           }),
           // eslint-disable-next-line react-hooks/exhaustive-deps -- table props are required dependencies
-          [state, groupBy, sortBy, activeTab.filters]
+          [searchQuery, state, groupBy, sortBy, activeTab.filters]
```
Comment (mnholtz) [inline src/extensionConsole/pages/blueprints/BlueprintsPageLayout.tsx:149]: This is the fix

File: src/extensionConsole/pages/blueprints/BlueprintsPageLayout.test.tsx [hunk 2]
```diff
@@ -235,6 +239,25 @@ describe("BlueprintsPageLayout", () => {
...
+
+    await user.type(
+      screen.getByTestId("blueprints-search-input"),
+      "hello world"
+    );
+    expect(rendered.getByTestId("blueprints-search-input").value).toBe(
+      "hello world"
+    );
+    jest.runAllTimers();
+    expect(screen.queryByText('0 results for "hello world"')).not.toBeNull();
```
Comment (twschiller) [inline src/extensionConsole/pages/blueprints/BlueprintsPageLayout.test.tsx:259]: NIT: it would be good to type again and double check that the value is updated

**Review by twschiller — APPROVED** [review]

**Comment by twschiller** [comment]
@mnholtz see the type error

File: src/extensionConsole/pages/blueprints/BlueprintsPageLayout.tsx (hunk 1 above)
Comment (BLoe) [reply src/extensionConsole/pages/blueprints/BlueprintsPageLayout.tsx:149]: I'm curious why eslint gets the dependency list wrong here 🤔
