### PR TITLE
#5854 Fix NPE in Home Panel for mods with no inner definition found

### LINKED ISSUE #5854: NPE on home tab when the `@pixies/linkedin/organization-demos` mod is activate
Steps to Reproduce
---
- Activate the `@pixies/linkedin/organization-demos` mod

Discussion
---
- ActiveModListItem needs error handling for it's async state
- You could use the fallbackValue util: https://github.com/pixiebrix/pixiebrix-extension/blob/9d2ceb06535f66f6fd06a5e1306e0eefb9364a95/src/utils/asyncStateUtils.ts#L158-L158

### PR DESCRIPTION
**Pull request by mnholtz**
## What does this PR do?

- Fixes #5854
- Fixes NPE for mods that have no inner definition defined for the extension point (i.e. if `definitions = {}`, as opposed to `definitions = undefined`)
- Prevents the UI from crashing if `getContainedStaterBrickNames` (called in the `useAsyncState` hook) throws an error (the starter brick feature is not critical to the UI)

## Reviewer Tips

- Note the test that I added to demonstrate the fix - it will fail if the changes to `getExtensionPointType` are reverted

## Discussion

- See question here in the engineering channel about the proper way to handle logic errors in `useAsyncState` hooks: https://pixiebrix.slack.com/archives/C023KL47XV4/p1685988221732089

## Checklist

- [x] Add tests
- [x] Designate a primary reviewer @BLoe

### CODE REVIEW

File: src/utils/recipeUtils.ts [hunk 1]
```diff
@@ -63,13 +63,13 @@ export const getRequiredServiceIds = (recipe: RecipeDefinition): RegistryId[] =>
...
   extensionPoint: ExtensionDefinition,
-  recipe?: RecipeDefinition
+  recipe: RecipeDefinition
 ): Promise<ExtensionPointType | null> => {
   // Look up the extension point in recipe inner definitions first
   if (recipe.definitions) {
     const definition: ExtensionPointDefinition = recipe.definitions[
       extensionPoint.id
-    ].definition as ExtensionPointDefinition;
+    ]?.definition as ExtensionPointDefinition;
```
Comment (mnholtz) [inline src/utils/recipeUtils.ts:72]: This is the main fix

File: src/sidebar/homePanel/ActiveModListItem.tsx [hunk 2]
```diff
@@ -65,7 +71,7 @@ export const ActiveModListItem: React.FunctionComponent<{
                   : styles.lineClampTwoLines
               )}
             >
-              {starterBricksContained.join(" • ")}
+              {(starterBricksContained ?? []).join(" • ")}
```
Comment (mnholtz) [inline src/sidebar/homePanel/ActiveModListItem.tsx:74]: This is a preventative measure - don't take down the UI if `getContainedStarterBrickNames` fails for some reason

Comment (twschiller) [reply src/sidebar/homePanel/ActiveModListItem.tsx:74]: You could also write as `{ data: starterBricksContained = [], error }` when destructuring the useAsyncState call

File: src/utils/recipeUtils.ts (hunk 1 above)
Comment (twschiller) [reply src/utils/recipeUtils.ts:72]: Technically, this assumes that mods don't mix internal and external reference.  

The better check for inner definitions seems to be `if (recipe.definitions && recipe.definitions[extensionPoint.id])`

Or, as shorthand: `if (recipe.definitions?[extensionPoint.id])

Comment (mnholtz) [reply src/utils/recipeUtils.ts]: As it is, the logic will still fall back to looking up the definition in the registry. But makes sense to be more explicity

**Review by twschiller — APPROVED** [review]
