### PR TITLE
#5343: fix variable analysis false positives for Document Builder list buttons

### LINKED ISSUE #5343: False positive unknown variable for button inside list element in Document Builder

### PR DESCRIPTION
**Pull request by twschiller**
## What does this PR do?

- Closes #5343 
- Cleans up `VarAnalysis` internal state to have a single `contextStack` for bookkeeping while recursing and iterating over bricks in a pipeline
- Fixes a bug in where `VarAnalysis.visitDocument` was visiting nested pipelines directly instead of while visting their parent elements in the document
- Updates ReduxAnalysisManager to dispatch an analysis failed action to help with debugging via redux-logger

## Reviewer Tips

1. Read the types in `varAnalysis.ts`
2. Look at the internal state of `VarAnalysis`
3. Look at visitPipeline, visitBlock, visitDocument, and visitDocumentElement methods

## Remaining Work

- [x] Add Jest tests for brick inputs inside the pipeline for the button in the list. (Analysis not currently flagging unknown variable during manual QA)

## Demo

- https://www.loom.com/share/f6ddd8e592004d8999d34624f1300a50

## Future Work

- List Element in the Document Builder can determine the shape of the element based on the item type of the array. Currently, the analysis is allowing any prop on the element

## Checklist

- [x] Add tests
- [x] Designate a primary reviewer: @BLoe

### CODE REVIEW

File: src/analysis/ReduxAnalysisManager.ts [hunk 1]
```diff
@@ -116,7 +117,18 @@ class ReduxAnalysisManager {
           })
         );
 
-        await analysis.run(activeElement);
+        try {
+          await analysis.run(activeElement);
+        } catch (error) {
+          listenerApi.dispatch(
```
Comment (twschiller) [inline src/analysis/ReduxAnalysisManager.ts:123]: Dispatch the failure to assist with debugging
