### PR TITLE
#5700: fix blueprints screen infinite messages bug

### LINKED ISSUE #5700: Regression: `locate` background call being spammed in extension console
Context
---
- Appears to be coming from useInstallablePermissions either remounting or useAsyncState running over and over again

### PR DESCRIPTION
**Pull request by twschiller**
## What does this PR do?

- Closes #5700
- Main fix: Memoizes the selector that selects the extensions passed to useInstallablePermissions
- Wraps calls to locateWithRetry and refreshServices in memoizeUntilSettled
- Removes unused state property on useInstallable
- Modifies useInstallableViewItems to not show loading indicator during the server call to `useGetMarketplaceListingsQuery`

## Reviewer Tips

- Review `useInstallables` and `useInstallableViewItems` and `useInstallableActions`

## Discussion

- I'm still not sure which change triggered the bug. My understanding is that the reference should have always been changing from the selector

## Demo

- https://www.loom.com/share/52ac8b0d4e4445ad9c23c7bd483c0cfb

## Future Work

- Clean up "installables" code so useInstallableViewItemActions isn't mounted multiple times per installable
- When the marketplace query loads, the installables re-mount. So if you had a 3-dot menu open, it will close. I think this happens because the data is passed to reactTable, so the whole reactTable re-renders. The code needs to be re-factored so that the fields impacted by the marketplace query (`icon` and `sharing`) are calculated on the  individual items instead of pre-calculated. (Although, that might not be possible for sharing, because it needs to be used in filters)

## Checklist

- [x] Add tests
- [x] Designate a primary reviewer: @mnholtz

### CODE REVIEW

File: src/extensionConsole/pages/blueprints/useInstallableViewItemActions.ts [hunk 1]
```diff
@@ -89,11 +91,16 @@ function useInstallableViewItemActions(
   // https://github.com/pixiebrix/pixiebrix-app/blob/5b30c50d7f9ca7def79fd53ba8f78e0f800a0dcb/api/serializers/account.py#L198-L198
   const isRestricted = isDeployment && restrict("uninstall");
 
-  const extensionsFromInstallable = useSelector(
+  // Without memoization, the selector the reference changes on every render, which causes useInstallablePermissions
+  // to recompute, spamming the background worker with service locator requests
+  const memoizedExtensionsSelector = useCallback(
```
Comment (twschiller) [inline src/extensionConsole/pages/blueprints/useInstallableViewItemActions.ts:96]: This is the main fix

File: src/extensionConsole/pages/blueprints/useInstallableViewItems.tsx [hunk 2]
```diff
@@ -118,53 +118,56 @@ function useInstallableViewItems(installables: Installable[]): {
...
-            }),
-            // eslint-disable-next-line security/detect-object-injection -- packageId is a registry id
-            listingId: listingsQuery.data?.[packageId]?.id,
-          },
-          updatedAt: getUpdatedAt(installable),
-          status: getStatus(installable),
-          hasUpdate: updateAvailable(recipes, installedExtensions, installable),
-          installedVersionNumber: getInstalledVersionNumber(
+  const installableViewItems = useMemo(() => {
+    const recipeMap = new Map(
```
Comment (twschiller) [inline src/extensionConsole/pages/blueprints/useInstallableViewItems.tsx:122]: Create a map, so lookup is faster if you have a lot of recipes

File: src/extensionConsole/pages/blueprints/useInstallables.ts [hunk 3]
```diff
@@ -84,17 +85,16 @@ function useInstallables(): InstallablesState {
...
-      async () =>
-        Promise.all(
-          allExtensions.map(async (extension) =>
-            resolveExtensionInnerDefinitions(extension)
-          )
-        ),
-      [allExtensions],
-      []
-    );
+  const { data: resolvedExtensions, isError: resolveError } = useAsyncState(
```
Comment (twschiller) [inline src/extensionConsole/pages/blueprints/useInstallables.ts:88]: Use the new hook

File: src/extensionConsole/pages/blueprints/useInstallablePermissions.ts [hunk 4]
```diff
@@ -32,22 +32,25 @@ const fallback: PermissionsStatus = {
...
 
   const {
     data: { hasPermissions, permissions },
   } = fallbackValue(
-    useAsyncState(
-      async () => checkExtensionPermissions(extensions),
-      [extensions, browserPermissions]
-    ),
+    useAsyncState(async () => {
+      if (isSuccess) {
```
Comment (twschiller) [inline src/extensionConsole/pages/blueprints/useInstallablePermissions.ts:48]: Avoid an unnecessary call while useExtensionsPermissions is loading

File: src/extensionConsole/pages/blueprints/useInstallableViewItems.tsx [hunk 5]
```diff
@@ -118,53 +118,65 @@ function useInstallableViewItems(installables: Installable[]): {
...
+    );
+
+    // Pick any IExtension from the blueprint to check for updates. All of their versions should be the same.
+    const extensionsMap = new Map(
+      installedExtensions
+        .filter((x) => x._recipe?.id)
+        .map((extension) => [extension._recipe.id, extension])
+    );
+
+    return installables.map((installable) => {
```
Comment (twschiller) [inline src/extensionConsole/pages/blueprints/useInstallableViewItems.tsx:134]: No changes below. View this diff without whitespace

File: src/extensionConsole/pages/blueprints/useInstallables.test.ts [hunk 6]
```diff
@@ -66,7 +66,6 @@ describe("useInstallables", () => {
 
     expect(wrapper.result.current).toEqual({
       installables: [],
-      isLoading: false,
```
Comment (twschiller) [inline src/extensionConsole/pages/blueprints/useInstallables.test.ts:69]: See comment here: https://github.com/pixiebrix/pixiebrix-extension/pull/5701/files#diff-063828abdc6db95c2993d1d5509d8d3ad8ef434e9bc29aa3ca8e5c680a1a44f7R31

File: src/types/extensionTypes.ts [hunk 7]
```diff
@@ -263,7 +263,12 @@ export function selectSourceRecipeMetadata(
   }
 
   return {
-    ...recipeDefinition.metadata,
+    ...pick(recipeDefinition.metadata, [
```
Comment (twschiller) [inline src/types/extensionTypes.ts:266]: Copy what we're doing in extensionsSlice

File: src/extensionConsole/pages/blueprints/useInstallables.ts [hunk 8]
```diff
@@ -108,6 +108,10 @@ function useInstallables(): InstallablesState {
   );
 
   const unknownRecipes: UnavailableRecipe[] = useMemo(() => {
```
Comment (mnholtz) [inline src/extensionConsole/pages/blueprints/useInstallables.ts:110]: Unrelated nit: This addition of `unknownRecipes` is new to me. The term `unknownRecipes` doesn't make a lot of sense to me at first glance; I have to dig into the logic to figure out what it does.

File: src/extensionConsole/pages/blueprints/useInstallableViewItemActions.ts [hunk 9]
```diff
@@ -89,11 +91,16 @@ function useInstallableViewItemActions(
   // https://github.com/pixiebrix/pixiebrix-app/blob/5b30c50d7f9ca7def79fd53ba8f78e0f800a0dcb/api/serializers/account.py#L198-L198
   const isRestricted = isDeployment && restrict("uninstall");
 
-  const extensionsFromInstallable = useSelector(
+  // Without memoization, the selector the reference changes on every render, which causes useInstallablePermissions
```
Comment (mnholtz) [inline src/extensionConsole/pages/blueprints/useInstallableViewItemActions.ts:94]:
```suggestion
  // Without memoization, the selector reference changes on every render, which causes useInstallablePermissions
```

File: src/extensionConsole/pages/blueprints/useInstallables.ts (hunk 8 above)
Comment (twschiller) [reply src/extensionConsole/pages/blueprints/useInstallables.ts]: Added a comment to explain
