### PR TITLE
#7844: fix NPE in deployments async state

### LINKED ISSUE #7844: NPE when activating team deployments in extension console
## Describe the bug

- https://pixiebrix.slack.com/archives/C06KXAGU0GK/p1709822277668609

### PR DESCRIPTION
**Pull request by twschiller**
## What does this PR do?

- Closes #7844 
- Main functional change is to refactor DeploymentContext to use useDeriveAsyncState
- Exposes async state from useFlags hook 
- Extracts out useBrowserIdentifier hook

## Remaining Work

- [x] Resolve FIXME on use of useFlags: https://github.com/pixiebrix/pixiebrix-extension/pull/7845/files#diff-7a369df688af99125d8ddd4d69d3f405d17f6492f4e80ad99a8c923acb061f09R121
  - Have a version of useFlags that uses AsyncState (not a good fit since it returns functions though)
  - Have a FlagsContext in the tree?
- [x] Double-check why auto-deployment is not working in the Loom Demo
  - It's because I'm an admin

## Demo

- https://www.loom.com/share/e75f586bbf0e4375b87f80a043beb52a

## Checklist

- [x] Add tests: updated tests
- [x] New files added to `src/tsconfig.strictNullChecks.json` (if possible)
- [x] Designate a primary reviewer: @BLoe

### CODE REVIEW

File: src/extensionConsole/pages/deployments/DeploymentsContext.tsx [hunk 1]
```diff
@@ -141,68 +118,67 @@ function useDeployments(): DeploymentsState {
...
-  // TODO: Refactor this to use RTK query: https://github.com/pixiebrix/pixiebrix-extension/issues/7841
-  const {
-    data: activatableDeployments,
-    isLoading: isLoadingModDefinitions,
-    error: modDefinitionsError,
-  } = useAsyncState(async () => {
-    if (!updatedDeployments) {
-      return null;
-    }
+  // Map flags state to standard AsyncState shape. Is savf because useDeriveAsyncState does not require that
```
Comment (grahamlangford) [inline src/extensionConsole/pages/deployments/DeploymentsContext.tsx:121]:
```suggestion
  // Map flags state to standard AsyncState shape. Is safe because useDeriveAsyncState does not require that ???
```

File: src/extensionConsole/pages/deployments/DeploymentsContext.tsx [hunk 2]
```diff
@@ -270,17 +253,13 @@ function useDeployments(): DeploymentsState {
...
     updateExtension,
     extensionUpdateRequired,
-    isLoading:
-      isLoadingDeployments || isLoadingModDefinitions || isLoadingPermissions,
-    error: getError({
-      deploymentsError,
-      modDefinitionsError,
-      permissionsError,
-    }),
+    // XXX: should `isLoading` if isAutoDeploying is true?
```
Comment (grahamlangford) [inline src/extensionConsole/pages/deployments/DeploymentsContext.tsx:260]: Currently handled by the `isAutoDeploying` key, but we might be able to combine without problem. See `DeploymentBanner` and `ModsPageLayout`

**Review by grahamlangford — APPROVED** [review]
