### PR TITLE
6398: fixes unknown variable flashup with the Variable Popup 

### LINKED ISSUE #6398: Slice 2.1: Fix Unknown Variable warning flash-up after selecting a variable from the popover (Impact: can cause confusion that they did something wrong)
https://www.notion.so/pixiebrix/Make-Variable-Popover-Generally-Available-e64deef53c894457901e88a606262f04?pvs=4#ff514f24d1134ba28d9c5eab690da952

Potential Regressions to Check Against
---
https://www.notion.so/pixiebrix/Release-1-8-0-9852a76e26f645bcaf4957c624cbf714?pvs=4#857f734af7cf4a448fd38dc9f6519e0a

### PR DESCRIPTION
**Pull request by grahamlangford**
## What does this PR do?

- Closes #6398 

## Demo
https://www.loom.com/share/d4a39a1508f94c6f97ac82b306653fd6

## Checklist

- [ ] Add tests
- [ ] New files added to `src/tsconfig.strictNullChecks.json` (if possible)
- [x] Designate a primary reviewer @twschiller

### CODE REVIEW

File: src/components/fields/schemaFields/widgets/TemplateToggleWidget.tsx
Comment (grahamlangford) [inline src/components/fields/schemaFields/widgets/TemplateToggleWidget.tsx:1]: This is all performance improvements that I originally made because I suspected that the extremely high number of renderings I was seeing might have something to do with the problem. Unrelated to the actual fix.

File: src/components/fields/schemaFields/widgets/TemplateToggleWidget.tsx [hunk 1]
```diff
@@ -137,24 +146,31 @@ const TemplateToggleWidget: React.VFC<TemplateToggleWidgetProps> = ({
...
-          setValue={setNewValueFromString}
-        />
+        {renderVarPopup ? (
+          <VarPopup
+            inputMode={inputMode}
+            inputElementRef={inputRef}
+            value={stringValue}
+            setValue={setNewValueFromString}
+          />
+        ) : null}
```
Comment (BLoe) [inline src/components/fields/schemaFields/widgets/TemplateToggleWidget.tsx:173]: Any reason for this pattern over `{renderVarPopup && (...)}`?

Comment (BLoe) [reply src/components/fields/schemaFields/widgets/TemplateToggleWidget.tsx:173]: Also, we've seen that conditionally rendering modal/popup type of content will almost always break any "hide" animation that exists or might be added later, so I'm not sure if we want to be conditionally rendering this popup? Could split the modal and content into 2 separate components if we want to conditionally render the _content_ of the modal (only when it's visible/showing).

**Review by BLoe — APPROVED** [review]
This makes sense, although it feels a bit hacky. I think we need to re-think the entire `shouldUseAnalysis` pattern at some point, it's pretty clunky.

File: src/components/fields/schemaFields/widgets/TemplateToggleWidget.tsx (hunk 1 above)
Comment (grahamlangford) [reply src/components/fields/schemaFields/widgets/TemplateToggleWidget.tsx:173]: > Any reason for this pattern over {renderVarPopup && (...)}?
Not in this case, but this is the pattern I use for cases like `{ arr.length ? }` because `{ arr.length && }` renders `0` when there are no indices.

Comment (BLoe) [reply src/components/fields/schemaFields/widgets/TemplateToggleWidget.tsx:173]: Ah yeah, in that case, I agree that it probably makes sense for now to make your change
