### PR TITLE
#7821 - Fix issue preventing save-as-new-mod with sidebar component

### LINKED ISSUE #7821: Unable to save sidebar mod component as a mod
## Describe the bug

Unable to save sidebar mod component as a mod

## To Reproduce

1. Go to the Page Editor
2. Add a standalone sidebar mod component
3. Click 3-dot menu to add to mod
4. Select an organization scope
5. Click save

## Actual behavior

Converted to a mod component

## Expected behavior

Modal closes and nothing happens. 

## Screenshots/Loom

One of the checks is potentially getting fired incorrectly? But it was was getting fired, I'd expect a warning modal to show?

image

## Desktop (please complete the following information):

- OS: [e.g. OSX, Windows 10, Windows 11]
- Browser: [e.g. chrome, edge]
- Extension Version: 1.8.10-beta.2 and main

## Additional context

- What mod(s) were you running?
- What website(s) were you using?
- Do you need any special permissions to reproduce?
  - Access to a Control Room?
  - Membership on a specific team?

### PR DESCRIPTION
**Pull request by BLoe**
## What does this PR do?

- Fixes #7821

## Checklist

- [x] Add tests
- [ ] New files added to `src/tsconfig.strictNullChecks.json` (if possible)
- [x] Designate a primary reviewer - @grahamlangford

### CODE REVIEW

File: src/pageEditor/hooks/useCompareModComponentCounts.ts [hunk 1]
```diff
@@ -19,25 +19,36 @@ import { type UnsavedModDefinition } from "@/types/modDefinitionTypes";
...
+      newModComponentFormState?: ModComponentFormState,
+    ) => {
       const modId = modDefinition.metadata.id;
       const { cleanModComponents, dirtyModComponentFormStates } =
         getCleanComponentsAndDirtyFormStatesForMod(modId);
+      const dirtyFormStates = dirtyModComponentFormStates;
+
+      if (newModComponentFormState) {
+        dirtyFormStates.push(newModComponentFormState);
+      }
```
Comment (grahamlangford) [inline src/pageEditor/hooks/useCompareModComponentCounts.ts:47]: This is technically mutating `dirtyModComponentFormStates`. Need to use the spread operator if you want a new reference.

File: src/pageEditor/hooks/useCheckModStarterBrickInvariants.ts [hunk 2]
```diff
@@ -26,21 +26,15 @@ import { ADAPTERS } from "@/pageEditor/starterBricks/adapter";
...
 };
 
 function useCheckModStarterBrickInvariants(): (
   unsavedModDefinition: UnsavedModDefinition,
-  {
-    sourceModDefinition,
-    sourceModComponent,
-    sourceModComponentFormState,
-  }: SourceModParts,
+  { sourceModDefinition, newModComponentFormState }: SourceModParts,
```
Comment (grahamlangford) [inline src/pageEditor/hooks/useCheckModStarterBrickInvariants.ts:37]: NIT: I think this we should standardize on _either_ `new` or `unsaved`. 

Or does `sourceModComponentFormState` still make sense? It would be used only in cases where that formState is the "source" for the unsavedModDefinition, right?

Comment (BLoe) [reply src/pageEditor/hooks/useCheckModStarterBrickInvariants.ts:37]: I differentiated the naming because "source" mod definition already exists, and it's used for either saving an existing mod or making a copy of an existing mod. The form state is only used in the create-mod-from-component use case, and it's always a _new_ mod component that does not currently exist in state.

Comment (BLoe) [reply src/pageEditor/hooks/useCheckModStarterBrickInvariants.ts:37]: The new component is not a "source" for anything else, it's literally the new component being used to save to create a new mod. It's already been cloned from the active existing mod component and had its `uuid` updated to a new one.

Comment (BLoe) [reply src/pageEditor/hooks/useCheckModStarterBrickInvariants.ts:37]: I experimented with passing in the existing active mod component as the "source" mod component and leaving the name as `source*`, but there is other logic in the create flow that references the cloned, "new" component that made this tricky to do right now.

**Review by grahamlangford — APPROVED** [review]
