### PR TITLE
#8203 Fix missing error toast notifications when saving mod

### LINKED ISSUE #8203: Page Editor is not showing mod save error toast
## Describe the bug

Page Editor is not showing mod save error toast. Is this only impacting marketplace mods version restrictions, or is it impacting all save errors in 1.8.12

## To Reproduce

1. Open a marketplace mod in the Page Editor
2. Make a change
3. Save the mod, without bumping the version number

## Actual behavior

A 400 network error appears in the Page Editor console network tab, but no error UI is displayed to the user

```
{
    "config": [
        "Cannot overwrite version of a published brick. Increment the version"
    ]
}
```

## Expected behavior

An error toast is shown with detail to the user can correct the error

## Screenshots/Loom

If applicable, add screenshots/looms to help explain your problem.

## Desktop (please complete the following information):

- OS: Mac
- Browser: Edge
- Extension Version: 1.8.12-mv3

### PR DESCRIPTION
**Pull request by mnholtz**
## What does this PR do?

- Closes #8203
- The fix was removing the try/catch from the `save` func in `useSaveMod`

## Discussion

- Struggling a bit with the Page Object pattern w.r.t. the PageEditorPage. In this particular test, the regular `page` object available on the context was referring to the wrong tab, so couldn't make any assertions on the actually page editor page without introducing the redundant `getByText` method. Any tips here?

## Checklist

- [x] Add jest or playwright tests and/or storybook stories
- [x] Designate a primary reviewer @grahamlangford

### CODE REVIEW

File: src/pageEditor/hooks/useSaveMod.ts
Comment (mnholtz) [inline src/pageEditor/hooks/useSaveMod.ts:1]: The only thing I changed in this file was removing the try/catch in `save`

File: end-to-end-tests/pageObjects/pageEditorPage.ts [hunk 1]
```diff
@@ -88,6 +88,28 @@ export class PageEditorPage {
...
+    // TODO: this method is currently meant for packaged mods that aren't meant to be
+    //  cleaned up after the test. Future work is adding affordance to clean up saved packaged
+    //  mods, with an option to avoid cleanup for certain mods.
+    await this.page.locator("[data-icon=save]").click();
+    await this.page.getByRole("button", { name: "Save" }).click();
+  }
+
+  getByText(text: string) {
+    return this.page.getByText(text);
+  }
```
Comment (mnholtz) [inline end-to-end-tests/pageObjects/pageEditorPage.ts:111]: @fungairino any tips here regarding my discussion bullet in the PR description?

> Struggling a bit with the Page Object pattern w.r.t. the PageEditorPage. In this particular test, the regular page object available on the context was referring to the wrong tab, so couldn't make any assertions on the actually page editor page without introducing the redundant getByText method. Any tips here?

File: src/pageEditor/hooks/useSaveMod.ts [hunk 2]
```diff
@@ -129,74 +129,64 @@ function useSaveMod(): ModSaver {
...
-      });
+    reportEvent(Events.PAGE_EDITOR_MOD_UPDATE, {
+      modId: newMod.metadata.id,
+    });
 
-      return true;
-    } catch {
-      return false;
-    }
+    return true;
```
Comment (fungairino) [inline src/pageEditor/hooks/useSaveMod.ts:189]: I'm confused why this function can both return false and throw errors to indicate if a save was not successful. 

I guess returning false here really means that the save was aborted from some reason rather than if it failed. But it's not clear from reading the jsdoc or type signature.

File: end-to-end-tests/pageObjects/pageEditorPage.ts (hunk 1 above)
Comment (fungairino) [reply end-to-end-tests/pageObjects/pageEditorPage.ts:111]: I think having a passthrough to the underlying page method is fine in this case. 

Even better probably would be to write the specific locator that you used in your test as a named method in this page object.

```
   getIncrementVersionWarning() {
    this.page.getByText(
      "Cannot overwrite version of a published brick. Increment the version",
    )
  } 
```

File: end-to-end-tests/pageObjects/pageEditorPage.ts [hunk 3]
```diff
@@ -88,6 +88,28 @@ export class PageEditorPage {
...
+      .first();
+  }
+
+  /**
+   * Save a packaged mod. Prefer saveStandaloneMod for standalone mods.
+   */
+  async savePackagedMod() {
+    // TODO: this method is currently meant for packaged mods that aren't meant to be
+    //  cleaned up after the test. Future work is adding affordance to clean up saved packaged
+    //  mods, with an option to avoid cleanup for certain mods.
```
Comment (fungairino) [inline end-to-end-tests/pageObjects/pageEditorPage.ts:104]: To clear up the confusion in what gets cleaned up, we could use a different terminology in the method names. Maybe we could name the other method `createStarterBrick`, and have it add the starter brick and save it as well.

File: end-to-end-tests/pageObjects/pageEditorPage.ts [hunk 4]
```diff
@@ -88,6 +88,28 @@ export class PageEditorPage {
...
+    return this.page
+      .locator(".list-group-item")
+      .locator("span", { hasText: modName })
+      .first();
+  }
+
+  /**
+   * Save a packaged mod. Prefer saveStandaloneMod for standalone mods.
+   */
+  async savePackagedMod() {
```
Comment (fungairino) [inline end-to-end-tests/pageObjects/pageEditorPage.ts:101]: Maybe we could maybe make this more specific - "saveSelectedPackagedMod" ?

There isn't anything that is specific to a packaged mod in this method, either. Maybe it's worth considering to see if we can either find more specific selectors or add add data test attributes to the html.

File: src/pageEditor/hooks/useSaveMod.ts (hunk 2 above)
Comment (grahamlangford) [reply src/pageEditor/hooks/useSaveMod.ts:189]: > I guess returning false here really means that the save was aborted from some reason rather than if it failed.

That's exactly the reasoning. JSDoc could be better. Everything to do with saving a mod needs to be improved. That's going to be one of our next initiatives.

File: end-to-end-tests/pageObjects/pageEditorPage.ts (hunk 1 above)
Comment (BLoe) [reply end-to-end-tests/pageObjects/pageEditorPage.ts:111]: Are we able to use custom assertions for these page objects with these playwright tests? Are those a pain/hassle to set up and/or use? Any chance we could get to a place where we could write:

`expect(pageEditorPage).toShowBrickVersionSaveError()`

File: src/pageEditor/hooks/useSaveMod.ts (hunk 2 above)
Comment (BLoe) [reply src/pageEditor/hooks/useSaveMod.ts:189]: I believe the point of adding the try-catch was that we didn't actually want to show some of the errors to users? The functional change here of removing the try-catch is that both errors in the api response and errors thrown from the `buildAndValidateMod()` function will now be shown explicitly to users in the UI in toasts.

Like this one: https://github.com/pixiebrix/pixiebrix-extension/blob/6cb955b540391391e38f12dd2b4f0a83a8bc6172/src/pageEditor/hooks/useBuildAndValidateMod.ts#L109

Comment (BLoe) [reply src/pageEditor/hooks/useSaveMod.ts:189]: I'm not 100% sure, but I think we wanted to catch this situation and report it to telemetry, but then we are showing the modal that says "we need to reset the page editor state" instead of showing the error toast with the scary "business integrity error" messaging to end-users.

We probably implemented this in a messy way and didn't realize we were also hiding/eating the API response errors in addition to explicitly thrown ones.

File: end-to-end-tests/pageObjects/pageEditorPage.ts (hunk 4 above)
Comment (mnholtz) [reply end-to-end-tests/pageObjects/pageEditorPage.ts]: This actually is specific to a packaged mod. The standalone mod components don't have the extra confirmation modal.

File: end-to-end-tests/pageObjects/pageEditorPage.ts (hunk 3 above)
Comment (mnholtz) [reply end-to-end-tests/pageObjects/pageEditorPage.ts:104]: I want to hold off on this refactor for now. I don't see this solving the root issue (trying to direct devs to use the right methods via comments) while proliferating the number of methods on this Page object. I'd like to see more usage of PageEditorPage for different tests before we decide to generalize more.

**Review by fungairino — APPROVED** [review]
