### PR TITLE
#4177 Analysis Engine shows error on wrong brick if you insert a brick before a brick

### LINKED ISSUE #4177: Analysis Engine shows error on wrong brick if you insert a brick before a brick
Steps to Reproduce
---
- Create an extension with 2 bricks, on the 2nd brick misconfigure a field
- Run the extension
- Inserts a brick between the two bricks

Expected behavior: error shows on the 3rd brick, (or no longer shows is also acceptable)
Actual behavior: error message shows on the newly inserted brick

Discussion
---
- The analysis engine now uses the "path" to determine where to show the annotations, but I think it needs to also double check the brick instance id to ensure it's not showing information on the wrong brick?

### PR DESCRIPTION
**Pull request by BALEHOK**
## What does this PR do?

- Fixes #4177

## Demo
https://www.loom.com/share/5fc68a081c864eeb89b4d8083fb962cf

## Checklist

- [ ] Add tests
- [x] Designate a primary reviewer @BLoe

### CODE REVIEW

**Review by BLoe — APPROVED** [review]

File: src/analysis/analysisVisitors/traceAnalysis.ts [hunk 1]
```diff
@@ -108,6 +107,14 @@ class TraceAnalysis extends AnalysisVisitor {
       });
     }
   }
+
+  override run(extension: FormState): void {
+    if (this.traceErrorMap.size === 0) {
```
Comment (BLoe) [inline src/analysis/analysisVisitors/traceAnalysis.ts:112]: Should this be `>0`? Or why would we _not_ run the extension when there are _no_ errors? Am I thinking about this wrong?

Comment (twschiller) [reply src/analysis/analysisVisitors/traceAnalysis.ts:112]: @BLoe the answer I think is that the analysis takes the pre-existing trace error records and converts it into annotations

So if there’s no errors in the error map, there wouldn’t be any annotations, so we can just skip running the analysis

Comment (BLoe) [reply src/analysis/analysisVisitors/traceAnalysis.ts:112]: Thanks!
