### PR TITLE
#9349: fix unsaved mod saving and refactor page editor modal state

### LINKED ISSUE #9349: Mod component is deselected on save of unsaved mod
## Describe the bug

- https://pixiebrix.slack.com/archives/C07SFDT3CSK/p1729775571211539

### PR DESCRIPTION
**Pull request by twschiller**
## What does this PR do?

- Fixes #9349
- Covered by Rainforest tests (which is how the regression was caught)
- The root cause was:
  - The unsaved mod modal wasn't being called. Instead, the Page Editor was creating a mod from the mod component
  - The `CreateModal` didn't have enough information to distinguish between the saving scenarios (it was trying to guess based on what was selected in the mod listing pane vs. the actual action that was performed)
- Refactors Page Editor modal data to a single prop with context about the source mod/mod component for the create modal

## Reviewer Notes

- Redux migration not required because the editorSlice modal props aren't persisted

## Remaining Work

- [x] Fix types
- [x] Refactor modals to handle when modals aren't showing
- [x] Fix mod component selection bug
- [x] Add playwright test for the original bug
- [x] Manual test

## Future Work

- Rework modal content in Page Editor to be gated based on the availability of the data. As-is the hooks/components need to handle different combinations of nullish data 😞 
- Rationalize the use of hooks vs. callback arguments in the save hooks. The save callbacks likely be async thunks dispatched from the modal instead of hooks
- Move helpers from editorSliceHelpers into the slice itself to make code easier to read
- Come up with better naming for active vs. current mod id (maybe parent mod id instead of current mod id?)

For more information on our expectations for the PR process, see the
[code review principles doc](https://www.notion.so/pixiebrix/Code-Review-Principles-1ce7276b82a84d2a995d55ad85e1310d?pvs=4)

### CODE REVIEW

File: end-to-end-tests/pageObjects/pageEditor/pageEditorPage.ts [hunk 1]
```diff
@@ -134,11 +134,50 @@ export class PageEditorPage extends BasePageObject {
     );
   }
 
+  /**
+   * @param currentModName the current name (not registry id) of the mod to save
+   */
+  @ModifiesModFormState
+  async saveNewModWithoutSelectingModItem({
```
Comment (twschiller) [inline end-to-end-tests/pageObjects/pageEditor/pageEditorPage.ts:141]: There wasn't a particularly clean way to combine this with the existing saveNewMod because this flow doesn't get a mod id because the Page Editor doesn't show the mod metadata pane on save in this flow

File: src/pageEditor/hooks/useCreateModFromMod.test.ts [hunk 2]
```diff
@@ -80,6 +80,7 @@ describe("useCreateModFromMod", () => {
       await result.current.createModFromMod(
```
Comment (twschiller) [inline src/pageEditor/hooks/useCreateModFromMod.test.ts:80]: Refactored the callback to take the save options vs. including in the callback closure defined in the hook. IMO, that's easier to reason about. See future work on rationalizing args vs. closures (or if we convert to thunks, use of getState)

File: src/pageEditor/hooks/useCreateModFromModComponent.ts [hunk 3]
```diff
@@ -53,23 +54,19 @@ function useCreateModFromModComponent(
...
-          "Expected mod component to be selected",
-        );
-
         if (!hasPermissions) {
           return;
         }
 
         const modId = newModMetadata.id;
-        const draftModComponents = [activeModComponentFormState];
+        const draftModComponents = [modComponentFormState];
```
Comment (twschiller) [inline src/pageEditor/hooks/useCreateModFromModComponent.ts:69]: In practice activeModComponentFormState would be the same as modComponentFormState so the old code was correct. But this code properly uses just the callback arg

File: src/pageEditor/modListingPanel/modals/MoveOrCopyToModModal.tsx [hunk 4]
```diff
@@ -142,18 +151,18 @@ const MoveOrCopyToModModal: React.FC = () => {
...
-    [isCopyAction, hideModal],
+    [modalData?.keepLocalCopy, hideModal],
   );
 
   return (
     <Modal show={show} onHide={hideModal}>
       <Modal.Header closeButton>
         <Modal.Title>
-          {isCopyAction ? "Copy" : "Move"}{" "}
+          {modalData?.keepLocalCopy ? "Copy" : "Move"}{" "}
```
Comment (twschiller) [inline src/pageEditor/modListingPanel/modals/MoveOrCopyToModModal.tsx:165]: Examples of where gating the modal title/body would simplify reasoning about the code

File: src/pageEditor/modListingPanel/modals/SaveAsNewModModal.tsx [hunk 5]
```diff
@@ -20,31 +20,26 @@ import { useDispatch, useSelector } from "react-redux";
...
   const { data: mod, isFetching } = useOptionalModDefinition(modId);
   const modName = mod?.metadata?.name ?? "this mod";
 
-  const dispatch = useDispatch();
-
   const hideModal = () => {
     dispatch(actions.hideModal());
   };
 
-  const onConfirm = () => {
```
Comment (twschiller) [inline src/pageEditor/modListingPanel/modals/SaveAsNewModModal.tsx:43]: Move inline to component for readability

File: src/pageEditor/store/editor/editorSlice.ts [hunk 6]
```diff
@@ -1031,12 +1066,7 @@ export const persistEditorConfig = {
   storage: localStorage as StorageInterface,
   version: 9,
   migrate: createMigrate(migrations, { debug: Boolean(process.env.DEBUG) }),
-  blacklist: [
-    "inserting",
-    "isVarPopoverVisible",
-    "isSaveDataIntegrityErrorModalVisible",
```
Comment (twschiller) [inline src/pageEditor/store/editor/editorSlice.ts:1037]: isSaveDataIntegrityErrorModalVisible wasn't on the state

File: src/pageEditor/store/editor/editorSliceHelpers.test.ts [hunk 7]
```diff
@@ -457,28 +456,3 @@ describe("removeModData", () => {
     ).toBeUndefined();
   });
 });
-
-describe("selectActiveModId", () => {
```
Comment (twschiller) [inline src/pageEditor/store/editor/editorSliceHelpers.test.ts:461]: Moved to editorSlice.test.ts

File: src/pageEditor/store/editor/editorSliceHelpers.ts [hunk 8]
```diff
@@ -186,22 +186,6 @@ export function removeModData(state: Draft<EditorState>, modId: RegistryId) {
   delete state.deletedModComponentFormStatesByModId[modId];
 }
 
-export function setActiveModId(state: Draft<EditorState>, modId: RegistryId) {
```
Comment (twschiller) [inline src/pageEditor/store/editor/editorSliceHelpers.ts:189]: There isn't a reason for this logic to be in this helper file vs. in the slice definition. IMO we should prefer to keep in the editorSlice definition to make easier to read

File: src/pageEditor/hooks/useCreateModFromUnsavedMod.ts [hunk 9]
```diff
@@ -109,14 +116,25 @@ function useCreateModFromUnsavedMod(): UseCreateModFromUnsavedModReturn {
...
 
-        dispatch(editorActions.setActiveModId(newModId));
+        if (activeModId === unsavedModId) {
+          // If the mod list item is selected, reselect the mod item using the new id
+          dispatch(editorActions.setActiveModId(newModId));
+        } else if (
+          activeModComponentFormState?.modMetadata.id === unsavedModId
+        ) {
+          // A mod component in the unsaved mod is selected. Expand the mod using the new new mod id
+          // XXX: currently, there's a short flicker for the mod to re-expand
```
Comment (twschiller) [inline src/pageEditor/hooks/useCreateModFromUnsavedMod.ts:126]: UI/UX papercut callout. Better than the user having to manually expand the mod and reselect the mod component though

File: src/pageEditor/modListingPanel/modals/SaveAsNewModModal.tsx [hunk 10]
```diff
@@ -58,7 +53,20 @@ const SaveAsNewModModal: React.FC = () => {
         <Button variant="info" onClick={hideModal}>
           Cancel
         </Button>
-        <Button variant="primary" disabled={isFetching} onClick={onConfirm}>
+        <Button
+          variant="primary"
+          disabled={isFetching}
+          onClick={() => {
+            assertNotNullish(modId, "Expected selected mod");
```
Comment (twschiller) [inline src/pageEditor/modListingPanel/modals/SaveAsNewModModal.tsx:60]: Another example of where gating the modal header/content would simplify the code

File: src/pageEditor/modals/addBrickModal/useAddBrick.ts [hunk 11]
```diff
@@ -136,14 +138,18 @@ function useAddBrick(): AddBrick {
 
       return {};
     },
-    [activeModComponent, addBrickLocation, makeNewBrick],
+    [activeModComponent, modalData, makeNewBrick],
   );
 
   const addBrick = useCallback(
     async (brick: Brick) => {
```
Comment (twschiller) [inline src/pageEditor/modals/addBrickModal/useAddBrick.ts:145]: Consider moving the addBrick location to the callback. See Future Work on rationalizing use of callback args/hooks (and rewriting as async thunks)

File: src/pageEditor/store/editor/editorSelectors/editorModalSelectors.ts [hunk 12]
```diff
@@ -17,23 +17,43 @@
...
-export const selectEditorModalVisibilities = ({ editor }: EditorRootState) => ({
-  isMoveCopyToModVisible: editor.visibleModalKey === ModalKey.MOVE_COPY_TO_MOD,
-  isSaveAsNewModModalVisible:
-    editor.visibleModalKey === ModalKey.SAVE_AS_NEW_MOD,
-  isCreateModModalVisible: editor.visibleModalKey === ModalKey.CREATE_MOD,
-  isAddBlockModalVisible: editor.visibleModalKey === ModalKey.ADD_BRICK,
-  isSaveDataIntegrityErrorModalVisible:
-    editor.visibleModalKey === ModalKey.SAVE_DATA_INTEGRITY_ERROR,
-});
+export const selectEditorModalVisibilities = ({ editor }: EditorRootState) => {
```
Comment (twschiller) [inline src/pageEditor/store/editor/editorSelectors/editorModalSelectors.ts:25]: NIT: IMO we could drop this selector in favor of a selector returning the visible modal type that could be compared to the `ModalKey`. To me this is redundant with the enum

File: src/pageEditor/store/editor/editorSlice.test.ts [hunk 13]
```diff
@@ -257,6 +258,31 @@ describe("Add/Remove Bricks", () => {
   });
 });
 
+describe("mod navigation", () => {
+  describe("selectActiveModId", () => {
```
Comment (twschiller) [inline src/pageEditor/store/editor/editorSlice.test.ts:262]: Moved from the editorHelper tests. IMO reducer methods can and should be directly tested vs. having separate helpers for each

File: src/pageEditor/store/editor/editorSelectors/editorModalSelectors.ts [hunk 14]
```diff
@@ -17,23 +17,43 @@
...
+    isMoveCopyToModVisible: type === ModalKey.MOVE_COPY_TO_MOD,
+    isSaveAsNewModModalVisible: type === ModalKey.SAVE_AS_NEW_MOD,
+    isCreateModModalVisible: type === ModalKey.CREATE_MOD,
+    isAddBlockModalVisible: type === ModalKey.ADD_BRICK,
+    isSaveDataIntegrityErrorModalVisible:
+      type === ModalKey.SAVE_DATA_INTEGRITY_ERROR,
+  };
+};
+
+// Typescript-Fu for getModalDataSelector
```
Comment (twschiller) [inline src/pageEditor/store/editor/editorSelectors/editorModalSelectors.ts:38]: 🙌  Thanks for @grahamlangford for the Typescript-Fu

File: end-to-end-tests/pageObjects/pageEditor/pageEditorPage.ts [hunk 15]
```diff
@@ -134,6 +134,44 @@ export class PageEditorPage extends BasePageObject {
...
+
+    await expect(saveNewModModal.getByText("Save new mod")).toBeVisible();
+    // // Can't use getByLabel to target because the field is composed of multiple widgets
+    const registryIdInput = saveNewModModal.getByTestId("registryId-id-id");
+    const currentId = await registryIdInput.inputValue();
+    // Add a random uuid to the mod id to prevent test collisions
+    await registryIdInput.fill(`${currentId}-${uuidv4()}`);
+
+    // Click the Save button in the modal
+    await saveNewModModal.getByRole("button", { name: "Save" }).click();
```
Comment (grahamlangford) [inline end-to-end-tests/pageObjects/pageEditor/pageEditorPage.ts:165]: I see where you copied this logic from, but we have a CreateModModal page object that should be used for this

File: src/pageEditor/hooks/useCreateModFromModComponent.ts (hunk 3 above)
Comment (grahamlangford) [reply src/pageEditor/hooks/useCreateModFromModComponent.ts:64]: Also means we don't recreate the function as often. 👍

File: src/pageEditor/hooks/useCreateModFromUnsavedMod.ts (hunk 9 above)
Comment (grahamlangford) [reply src/pageEditor/hooks/useCreateModFromUnsavedMod.ts:126]: I think we mountonenter for performance reasons? That's probably the cause of the flicker. There might not be much we can do about it without harming performance

File: end-to-end-tests/pageObjects/pageEditor/pageEditorPage.ts (hunk 15 above)
Comment (twschiller) [reply end-to-end-tests/pageObjects/pageEditor/pageEditorPage.ts]: 👍 That page object allowed for consolidating the hooks. Have merged to get a CI run in

File: src/pageEditor/store/editor/editorSlice.test.ts (hunk 13 above)
Comment (grahamlangford) [reply src/pageEditor/store/editor/editorSlice.test.ts:262]: Strong agree calling the reducer directly is better than using produce

File: src/pageEditor/hooks/useCreateModFromUnsavedMod.ts (hunk 9 above)
Comment (twschiller) [reply src/pageEditor/hooks/useCreateModFromUnsavedMod.ts:126]: I was hoping there was an affordance to open without the animation, but I don't see one: https://react-bootstrap-v4.netlify.app/components/accordion/

**Review by grahamlangford — APPROVED** [review]

File: src/pageEditor/hooks/useCreateModFromUnsavedMod.ts (hunk 9 above)
Comment (grahamlangford) [reply src/pageEditor/hooks/useCreateModFromUnsavedMod.ts:126]: If the flicker is just the animation, looks like Accordion uses react-transition-group under the hood (pretty typical). Props are spread to the `Collapse` component: https://github.com/react-bootstrap/react-bootstrap/blob/b415c70022291a1aa8751d7083beabf3dbbbb59d/src/AccordionCollapse.tsx#L37, which takes timeout: https://github.com/react-bootstrap/react-bootstrap/blob/b415c70022291a1aa8751d7083beabf3dbbbb59d/src/Collapse.tsx#L26

https://reactcommunity.org/react-transition-group/transition#Transition-prop-timeout

Comment (grahamlangford) [reply src/pageEditor/hooks/useCreateModFromUnsavedMod.ts:126]: Just validated that the flicker is less noticeable if we set the timeout to 0. We want the animation normally though, so we would need to have some additional logic to dynamically set the timeout

Comment (twschiller) [reply src/pageEditor/hooks/useCreateModFromUnsavedMod.ts:126]: > Just validated that the flicker is less noticeable if we set the timeout to 0. We want the animation normally though, so we would need to have some additional logic to dynamically set the timeout

I think you could do it by:
- Use a ref to determine if the render is the first render
- Pass the timeout as zero if it's the first render and isExpanded is true

File: src/pageEditor/hooks/useCreateModFromModComponent.ts (hunk 3 above)
Comment (twschiller) [reply src/pageEditor/hooks/useCreateModFromModComponent.ts:64]: > Also means we don't recreate the function as often. 👍

💯  I'll likely refactor soonish to make these async thunks so we don't have to recreate the function at all

File: end-to-end-tests/pageObjects/pageEditor/createModModal.ts [hunk 16]
```diff
@@ -22,24 +22,46 @@ import { uuidv4 } from "@/types/helpers";
 
 export class CreateModModal extends BasePageObject {
   modIdInput = this.getByTestId("registryId-id-id");
-  modNameInput = this.getByLabel("Name", { exact: true });
+  modNameInput = this.getByRole("textbox", { name: "Name" });
+  descriptionInput = this.getByRole("textbox", { name: "Description" });
```
Comment (grahamlangford) [inline end-to-end-tests/pageObjects/pageEditor/createModModal.ts:26]: `getByRole` > `getByLabel` > `getByTestId` > `locator`

File: src/components/form/FieldTemplate.tsx [hunk 17]
```diff
@@ -149,7 +150,7 @@ const FieldTemplate: <As extends React.ElementType, T = Element>(
   // because it gets both `controlId` from Group and `id` from props of `AsControl`.
   // See their logic at https://github.com/react-bootstrap/react-bootstrap/blob/v1.6.4/src/FormControl.tsx#L179:L182
   // The most simple solution is to manually set `htmlFor` on the Label and `id` on the Control.
-  const controlId = name;
+  const controlId = id ?? name;
```
Comment (grahamlangford) [inline src/components/form/FieldTemplate.tsx:153]: prefer id if provide but default to name, this allows us to fix the `getByRole` and `getByLabel` issues we've been seeing in some of our tests due to multiples of the same `id` in the document

File: src/pageEditor/modListingPanel/modals/CreateModModal.tsx [hunk 18]
```diff
@@ -243,25 +255,29 @@ const CreateModModalBody: React.FC = () => {
       <ConnectedFieldTemplate
         name="id"
         label="Mod ID"
+        id="create-mod-modal-id"
```
Comment (grahamlangford) [inline src/pageEditor/modListingPanel/modals/CreateModModal.tsx:258]: Override the ids for each of the modal fields, unfortunately this isn't enough to prevent us from needing `getByTestId` for the mod id
