### PR TITLE
#7729: Handle Gmail's deselection on mousedown

### LINKED ISSUE #7729: Text Selection popover doesn't run action in Gmail email composer
## Describe the bug

Text selection popover over buttons don't work in Gmail email composer

## To Reproduce

- Enable the text selection popover
- Add a context menu for selection (e.g., one that shows the selected text as an alert)
- Open the email composer in Gmail
- Write "hello", select the text, and click your action

## Actual behavior

- Popover disappears but doesn't run

## Expected behavior

- Action runs and popover disappears

## Investigation

- What appears to happening is that upon clicking the the popover, the `selectionchange` event fires with an empty selection, so tooltipController calls hideTooltip. It likely calls the Abort before the click has a chance to run
- If you remove the `hideTooltip()` in the selectionchange handler, the action runs, but doesn't see any selected text

## Desktop (please complete the following information):

- https://github.com/pixiebrix/pixiebrix-extension/pull/7728

### PR DESCRIPTION
**Pull request by fregante**
## What does this PR do?

- Closes #7729

## Checklist

- [x] Designate a primary reviewer: @twschiller

### CODE REVIEW

File: src/contentScript/selectionTooltip/SelectionToolbar.tsx [hunk 1]
```diff
@@ -65,12 +67,14 @@ const ToolbarItem: React.FC<
...
     }}
     title={selectButtonTitle(title, selection)}
+    onMouseDown={() => {
+      // Don't use selectionController.save() because restoring it brings up the
+      // toolbar even after it's been hidden by onHide()
+      lastKnownSelection = window.getSelection()?.toString();
+    }}
     onClick={() => {
-      const selection = window.getSelection();
-      if (selection) {
```
Comment (fregante) [inline src/contentScript/selectionTooltip/SelectionToolbar.tsx:70]: A few notes:

1. The component already had a `selection`, it should reuse it
2. If there's no selection, there shouldn't be a toolbar
3. `getSelection` is never null outside of Firefox

File: src/contentScript/selectionTooltip/tooltipController.tsx [hunk 2]
```diff
@@ -296,7 +298,7 @@ export const initSelectionTooltip = once(() => {
         trailing: true,
       },
     ),
-    { passive: true },
+    { passive: true, signal: onContextInvalidated.signal },
```
Comment (fregante) [inline src/contentScript/selectionTooltip/tooltipController.tsx:301]: This event was left behind, making debugging confusing. Related:

- https://github.com/pixiebrix/eslint-config-pixiebrix/issues/235

**Review by grahamlangford — APPROVED** [review]
