### PR TITLE
#880: refactor permissions and deployment activation code; fix deployment permissions checks

### LINKED ISSUE #880: Brick definitions (readers, etc.) not being refreshed when activating new deployment from sidebar

### PR DESCRIPTION
**Pull request by twschiller**
Closes #880

@fregante Apologies in advance for the structure of the PR. Because everything was tangled up, I was in a lot of files, so I took the opportunity to clean up some technical debt

You can just focus on the `permissions/index.ts` file since it impacts your work

I'll be doing a full round of QA for a release tomorrow

* Removes use of permissions lists except where needed for our current by-origin display
* Consolidates the deployment permissions hooks
* Blueprint and deployment permissions checks now consider block permissions
* Introduces a `useNotifications` hook that exposes helpers for our standard user notifications. The warning/error levels automatically handle error telemetry

@fregante I'll have to show you how to create team deployments so that you can test the functionality on Firefox at some point. We don't have any enterprise users using FF with deployments though, so not urgent

### CODE REVIEW

File: src/hooks/useNotifications.ts [hunk 1]
```diff
@@ -0,0 +1,163 @@
...
+        appearance: "info",
+        autoDismiss: true,
+      });
+    },
+    [addToast]
+  );
+
+  const notify = useCallback(
+    (
+      content: string,
```
Comment (twschiller) [inline src/hooks/useNotifications.ts:94]: I thought it was called prettier... 😞

File: src/core.ts [hunk 2]
```diff
@@ -141,6 +141,11 @@ export type ServiceLocator = (
   id?: string
 ) => Promise<SanitizedServiceConfiguration>;
 
+export type ServiceAuthPair = {
```
Comment (twschiller) [inline src/core.ts:144]: Move it to a more logical location since it's used across different components

File: src/options/pages/deployments/DeploymentBanner.tsx [hunk 3]
```diff
@@ -15,201 +15,11 @@
...
-import { reportError } from "@/telemetry/logging";
-import { activeDeployments, queueReactivate } from "@/background/deployment";
-import { selectInstalledExtensions } from "@/options/selectors";
-import { uninstallContextMenu } from "@/background/contextMenus";
-import { refreshRegistries } from "@/hooks/refresh";
-import { getErrorMessage } from "@/errors";
-
-const { actions } = optionsSlice;
-
-function useEnsurePermissions(deployments: Deployment[]) {
```
Comment (twschiller) [inline src/options/pages/deployments/DeploymentBanner.tsx:49]: This redundant code got axed/consolidated

File: src/options/pages/installed/InstalledPage.tsx [hunk 4]
```diff
@@ -98,7 +98,12 @@ const InstalledPage: React.FunctionComponent<{
       <Row>
         <Col>
           <div className="pb-4">
-            {!isEmpty(extensions) ? (
```
Comment (twschiller) [inline src/options/pages/installed/InstalledPage.tsx:101]: Flip ternary

File: src/options/pages/marketplace/ActivateWizard.tsx [hunk 5]
```diff
@@ -15,202 +15,26 @@
...
-    // eslint-disable-next-line security/detect-object-injection -- safe because it's from Object.entries
-    result[id] = configs[0];
-  }
-
-  return result;
-}
-
-type Reinstall = (recipe: RecipeDefinition) => Promise<void>;
-
-export function useReinstall(): Reinstall {
```
Comment (twschiller) [inline src/options/pages/marketplace/ActivateWizard.tsx:79]: Extracted to it's own file

File: src/options/pages/marketplace/ActivateWizard.tsx [hunk 6]
```diff
@@ -15,202 +15,26 @@
...
-          extensionPoints: recipe.extensionPoints,
-          services: currentAuths,
-        })
-      );
-    },
-    [dispatch, extensions]
-  );
-}
-
-function useInstall(recipe: RecipeDefinition): InstallRecipe {
```
Comment (twschiller) [inline src/options/pages/marketplace/ActivateWizard.tsx:118]: Extracted to it's own file

File: src/permissions/index.ts [hunk 7]
```diff
@@ -15,89 +15,122 @@
  * along with this program.  If not, see <http://www.gnu.org/licenses/>.
  */
 
-import extensionRegistry from "@/extensionPoints/registry";
```
Comment (twschiller) [inline src/permissions/index.ts:18]: @fregante You can focus your review on this file

File: src/permissions/index.ts [hunk 8]
```diff
@@ -155,37 +201,21 @@ export async function extensionPermissions(
...
+      compact([
+        opts.includeExtensionPoint ? extensionPoint.permissions : null,
+        ...(opts.includeServices ? services : []),
+        ...blockPermissions,
+      ])
+    )
   );
 }
 
-export async function checkPermissions(
```
Comment (twschiller) [inline src/permissions/index.ts:167]: Only used in 1 place

File: src/permissions/index.ts [hunk 9]
```diff
@@ -155,37 +201,21 @@ export async function extensionPermissions(
...
-  permissionsList: Permissions.Permissions[]
-): Promise<boolean> {
-  const merged = mergePermissions(permissionsList);
-  return containsPermissions(merged);
-}
-
-export async function permissionsEnabled(
```
Comment (twschiller) [inline src/permissions/index.ts:174]: Only used in 1 place

File: src/permissions/index.ts [hunk 10]
```diff
@@ -155,37 +201,21 @@ export async function extensionPermissions(
...
-  extension: IExtension
-): Promise<boolean> {
-  return checkPermissions(await extensionPermissions(extension));
-}
-
-export async function ensureExtensionPermissions(
```
Comment (twschiller) [inline src/permissions/index.ts:180]: Only used in 1 place

File: src/permissions/index.ts [hunk 11]
```diff
@@ -206,30 +236,3 @@ export function originPermissions(
 
   return sortBy(grouped, (x) => x.origins[0]);
 }
-
-export function useExtensionPermissions(
```
Comment (twschiller) [inline src/permissions/index.ts:210]: Extracted to it's own file

File: src/hooks/useDeployments.ts [hunk 12]
```diff
@@ -0,0 +1,187 @@
...
+        `Error fetching latest bricks from server: ${getErrorMessage(error)}`,
+        { error, report: true }
+      );
+    }
+
+    const permissions = await selectDeploymentPermissions(deployments);
+
+    let accepted = false;
+    try {
+      accepted = await ensureAllPermissions(permissions);
```
Comment (twschiller) [inline src/hooks/useDeployments.ts:164]: @fregante This will probably be broken on Firefox (that there's awaits before the check)

File: src/pages/marketplace/useReinstall.ts [hunk 13]
```diff
@@ -0,0 +1,95 @@
...
+  const serviceAuths = groupBy(
+    extensions.flatMap((x) => x.services),
+    (x) => x.id
+  );
+  const result: Record<ServiceId, string> = {};
+  for (const [id, auths] of Object.entries(serviceAuths)) {
+    const configs = uniq(auths.map(({ config }) => config));
+    if (configs.length === 0) {
+      throw new Error(`Service ${id} is not configured`);
+    } else if (configs.length > 1) {
```
Comment (fregante) [inline src/pages/marketplace/useReinstall.ts:44]: Annoyingly https://eslint.org/docs/rules/no-else-return does not enforce this on throws, even though it's the same idea

```suggestion
      throw new Error(`Service ${id} is not configured`);
    }

    if (configs.length > 1) {
```

**Review by fregante — CHANGES_REQUESTED** [review]

File: src/permissions/index.ts [hunk 14]
```diff
@@ -15,89 +15,122 @@
...
 
-export type ServiceAuthPair = {
-  id: string;
-  config: string;
-};
+/**
+ * Exclude MANDATORY_PERMISSIONS that were already granted on install. Firefox errors when you request a permission
+ * that's in the permissions, but not the optional_permissions
+ */
+function normalizeOptionalPermissions(
```
[the remark this answers is not in the document]
Comment (twschiller) [reply src/permissions/index.ts:58]: Not all FF permissions requests will go through PermissionsPopup though? If the user is on the options page and clicks "Grant Permissions" FF will just show the native prompt -- correct? So we still need to filter out the optional permissions before that point?

File: src/permissions/index.ts [hunk 15]
```diff
@@ -15,89 +15,122 @@
...
 export async function ensureAllPermissions(
-  permissionsList: Permissions.Permissions[]
+  permissions: Permissions.Permissions
 ): Promise<boolean> {
-  // TODO: Instead of passing around `Array<Permission>`, merge them into a regular `Permission`
-  // as early in the code as possible (e.g. in the hook that generates the array).
-  // This way we don't need to call `mergePermissions` or loop the array every time.
-  return requestPermissions(mergePermissions(permissionsList));
+  // `normalize` to ensure the request will succeed on Firefox. See normalize
+  return requestPermissions(normalizeOptionalPermissions(permissions));
```
[the remark this answers is not in the document]
Comment (twschiller) [reply src/permissions/index.ts:51]: I think it has to go into `requestPermissions` because we still need to filter the permissions even if we're prompting using the native permissions prompt

**Comment by twschiller** [comment]
@fregante I bumped the webext-additional-permissions dependency and axed the ensureAllPermissions method in favor of using requestPermission directly

**Comment by fregante** [comment]
> @fregante I bumped the webext-additional-permissions dependency and axed the ensureAllPermissions method in favor of using requestPermission directly

Did you forget to push? I don't see this change here

File: src/permissions/index.ts (hunk 15 above)
[the remark this answers is not in the document]
Comment (fregante) [reply src/permissions/index.ts:51]: In Chrome `request` passes without filtering, which is how it has worked until my related Firefox PR: If no changes are required, `request()` just returns without prompt.
