### PR TITLE
#4003 Fix invalid old blueprint warnings

### LINKED ISSUE #4003: Fix old blueprint in Page Editor warning
https://github.com/pixiebrix/pixiebrix-extension/blob/444db65968c6e96371052bf7e37eaba1989035f7/src/pageEditor/tabs/editRecipeTab/EditRecipe.tsx#L119-L119

Implementation Sketch
---
- Switch the comparison to use the lt or gt method from the "semver" package

### PR DESCRIPTION
**Pull request by BLoe**
## What does this PR do?

- Fixes #4003 

## Checklist

- [ ] Add tests
- [ ] Designate a primary reviewer

### CODE REVIEW

File: src/pageEditor/tabs/editRecipeTab/EditRecipe.tsx [hunk 1]
```diff
@@ -116,7 +117,7 @@ const EditRecipe: React.VoidFunctionComponent = () => {
       <Card>
         <Card.Header>Blueprint Metadata</Card.Header>
         <Card.Body>
-          {installedRecipeVersion !== latestRecipeVersion && (
+          {lt(installedRecipeVersion, latestRecipeVersion) && (
```
Comment (twschiller) [inline src/pageEditor/tabs/editRecipeTab/EditRecipe.tsx:120]: @BLoe do we need to handle null here? Or does `lt` do the right thing?

**Review by twschiller — APPROVED** [review]

File: src/pageEditor/tabs/editRecipeTab/EditRecipe.tsx [hunk 2]
```diff
@@ -73,6 +74,10 @@ const EditRecipe: React.VoidFunctionComponent = () => {
 
   const installedRecipeVersion = recipeExtension?._recipe.version;
   const latestRecipeVersion = recipe?.metadata?.version;
+  const showOldRecipeWarning =
```
Comment (twschiller) [inline src/pageEditor/tabs/editRecipeTab/EditRecipe.tsx:77]: 👍
