### PR TITLE
#8104 Do not automatically close the sidebar when saving in the Page Editor

### LINKED ISSUE #8104: Do not automatically close the sidebar while the Page Editor is open
## Describe the bug

- If the mod panel is the only panel open, the sidebar automatically closes when saving a mod because the dynamic element is removed from the page and the saved version is added to the page
- Auto-closing is jarring with the Chromium Sidepanel and annoying because you have to re-open the sidebar/re-render the panel to continue working

## To Reproduce

1. Create a mod package with a sidebar
2. Run the mod so it's the only sidebar panel
3. Make a change and save the mod

## Actual behavior

The sidebar is automatically closed

## Expected behavior

The sidebar is open to the saved version of the mod you are working on

## Discussion

- An alternative approach would be to debounce the hide because the panel will be immediately re-added. However, that would introduce a race condition. Not auto-hiding while the Page Editor is open seems like the easiest approach

## Desktop (please complete the following information):

- Browser: Chrome
- Extension Version: 1.8.11

## Related Code

- `useHideEmptySidebar` auto-hides the sidebar if there are no visible panels: https://github.com/pixiebrix/pixiebrix-extension/blob/71182b2a15b942cc70d63587dc8ce5d59411d8cc/src/sidebar/useHideEmptySidebar.ts#L32-L32

### PR DESCRIPTION
**Pull request by fungairino**
## What does this PR do?

- Closes #8104

## Discussion

- reading `lifecycle.ts` and trying to understand all the different code execution paths gives me a migraine.
- I'm not a fan of the check for sidebar kind equals "actionPanel" that we do in many different places. 
- I manually verified that the regression fixed in this PR with trigger mods running multiple times after save doesn't happen: https://github.com/pixiebrix/pixiebrix-extension/pull/5505

## Checklist

- [X] Add jest or playwright tests and/or storybook stories
- [X] Designate a primary reviewer @BLoe

### CODE REVIEW

**Comment by fungairino** [comment]
Flakiness of the new e2e tests is due to a known issue: https://github.com/pixiebrix/pixiebrix-extension/blob/e378e888cea7394d139d44f58b664654e1c76e2e/end-to-end-tests/pageObjects/extensionConsole/modsPage.ts#L72

File: src/contentScript/lifecycle.ts [hunk 1]
```diff
@@ -409,10 +409,17 @@ async function loadPersistedExtensions(): Promise<StarterBrick[]> {
   // Exclude the following:
   // - disabled deployments: the organization admin might have disabled the deployment because via Admin Console
   // - dynamic extensions: these are already installed on the page via the Page Editor
-  const activeExtensions = options.extensions.filter(
-    (extension) =>
-      isDeploymentActive(extension) && !_editorExtensions.has(extension.id),
-  );
+  const activeExtensions = options.extensions.filter((extension) => {
```
[the remark this answers is not in the document]
Comment (BLoe) [reply src/contentScript/lifecycle.ts:412]: Render panel shouldn't affect what is being saved, but there's a race condition with the "effect" that syncs Formik to redux, and if you can click save within 500ms of a change, you can end up saving the state before the change.

File: src/contentScript/lifecycle.ts [hunk 2]
```diff
@@ -409,10 +409,17 @@ async function loadPersistedExtensions(): Promise<StarterBrick[]> {
...
+    if (_editorExtensions.has(extension.id)) {
+      const editorExtension = _editorExtensions.get(extension.id);
+      // Include sidebar (i.e. "actionPanel") starterbrick kind as those are replaced
+      // by the sidebar itself, automatically replacing old panels keyed by extension id
+      return editorExtension.kind === "actionPanel";
+    }
+
+    // Exclude disabled deployments
+    return isDeploymentActive(extension);
+  });
```
Comment (BLoe) [inline src/contentScript/lifecycle.ts:422]: @twschiller Here's the PR where you added this check to filter out editor extensions: https://github.com/pixiebrix/pixiebrix-extension/pull/5505

I think we may need to keep buttons here as well? I'm able to get a button to disappear by typing in a config field at the same time I click save in the page editor. If I include `"menuItem"` here in addition to `"actionPanel"`, the bug goes away. I'm not able to achieve the same behavior with quick bar and context menu items.

Comment (twschiller) [reply src/contentScript/lifecycle.ts:422]: Thanks for the callout, @BLoe 

Taking a step back - conceptually/in natural language what is the code change attempting to do?

Before: there are 1) mod components contributed by the Page Editor, and 2) mod components contributed by what the user has activated. The edited contributed by the Page Editor takes precedence in what's running on the page

After: for sidebar starter bricks, both the Page Editor copy and version the user has activated should run

To me, the "After" seems like a potential for a race condition. Both copies will register themselves. The last one to register itself will win

I guess this is guaranteed to work because the order will always be?
1. Main version is instantiated on the page
2. User opens Page Editor. Main version replaced with editor version
3. User makes a change. Editor version is updated on the page
4. User saves their change in the Page Editor. (Conceptually, what happens here - does the Page Editor remove it from the page?)
5. The new saved version is instantiated on the page and replaces the editor version. (Because the new check allows it to be instantiated even though it's open in the Page Editor)
6. The user makes another edit in the Page Editor, and the editor version replaces the main version

Is the above sequence accurate? What details are missing

The antidote to understanding the lifecycle is taking a step back from and trying to write down in natural language what the flow is

Comment (fungairino) [reply src/contentScript/lifecycle.ts:422]: It's guaranteed to work as long as the user waits for the pageEditor mod is persisted (there is a 500ms debounce for persisting the current mod form state to redux storage in the page editor)

Save will trigger [all tabs to reactivate](https://github.com/pixiebrix/pixiebrix-extension/blob/4565cbab5538c8a02a6cdda8e5289939cccf1afe/src/pageEditor/hooks/useSaveMod.ts#L211), which remounts all active extensions except for the ones currently open by the page editor (to avoid issues like the one described here: https://github.com/pixiebrix/pixiebrix-extension/pull/5505). However this causes the sidebar page to be uninstalled and removed. This change ensures that the sidebar itself handles replacing the sidebar panel with the most current version that was just saved. This is in line with several other places where we specifically don't uninstall the mod if it's a "actionPanel" kind.
https://github.com/pixiebrix/pixiebrix-extension/blob/9c4ce5d73442ad97be7a184e5e1b60dea29036b7/src/contentScript/lifecycle.ts#L290
https://github.com/pixiebrix/pixiebrix-extension/blob/65ab778884244c4b5251813587f27077dfd17855/src/contentScript/pageEditor/dynamic/updateDynamicElement.ts#L42

Comment (fungairino) [reply src/contentScript/lifecycle.ts:422]: I do think that the content script lifecycle, sidebar and pageEditor interactions deserve a deeper analysis and we should consider where we can refactor to simplify and remove some of this complexity, and where we can't to document this complexity in a clear manner (maybe using a sequence diagram or similar).

The extension types also could use another look and encapsulate more of the code related to them rather than having to check for the kind of starter brick in many different places.
