### PR TITLE
Fix ContextError constructor selecting error message for "aggregate errors"

### LINKED ISSUE #6405: Missing Error Message in Mod Telemetry
https://pixiebrix.slack.com/archives/C05DW7JE16Y/p1694007948197949

### PR DESCRIPTION
**Pull request by mnholtz**
## What does this PR do?

- Fixes #6405
- `ContextError`s weren't being constructed properly for "aggregate errors" due to false assumptions about the shape of aggregate errors in `getErrorMessage` error utility method
- Also fixes the way we are selecting additional data to report to error service in order to also save information about error cause, stack, context, etc.

## Checklist

- [x] Add tests
- [x] Designate a primary reviewer @twschiller or @grahamlangford

### CODE REVIEW

File: src/errors/errorHelpers.ts [hunk 1]
```diff
@@ -217,13 +228,35 @@ export function getErrorMessage(
     return error;
   }
 
+  // TODO: Remove me if we'd rather have the specific Input/OutputValidationError message here;
+  //  no impact on page editor validation errors
+  if (isErrorObject(error)) {
+    return error.message;
+  }
```
Comment (mnholtz) [inline src/errors/errorHelpers.ts:235]: Did a quick manual test to see what would happen here:
https://www.loom.com/share/f500551228c94949b17339c26e55d6e2

Comment (mnholtz) [reply src/errors/errorHelpers.ts:235]: Might remove later as needed

File: src/errors/errorHelpers.ts [hunk 2]
```diff
@@ -222,11 +227,25 @@ export function getErrorMessage(
     return requestErrorMessage;
   }
 
+  // TODO: Remove me if we'd rather have a specific Input/OutputValidationError message here
+  const selectedError = selectError(error);
+  if (selectedError.message) {
+    return String(selectedError.message);
+  }
```
Comment (mnholtz) [inline src/errors/errorHelpers.ts:234]: See https://pixiebrix.slack.com/archives/C023KL47XV4/p1694488588036059?thread_ts=1694476151.520909&cid=C023KL47XV4

File: src/errors/errorHelpers.ts [hunk 3]
```diff
@@ -222,11 +227,25 @@ export function getErrorMessage(
...
+
+  if (isIOValidationError(error)) {
+    const firstError = error.errors[0];
+    return formatIOValidationMessage(firstError) ?? defaultMessage;
```
Comment (mnholtz) [inline src/errors/errorHelpers.ts:238]: If there's no "message" property at this point, tentatively prefer the first validation error?

File: src/errors/errorHelpers.ts [hunk 4]
```diff
@@ -222,11 +227,25 @@ export function getErrorMessage(
...
+  }
+
   if (isCustomAggregateError(error)) {
```
Comment (mnholtz) [inline src/errors/errorHelpers.ts:241]: I'm not sure what other errors other than `InputValidationError` or `OutputValidationError` could fall under this check, but keeping for now just in case.

File: src/sidebar/components/__snapshots__/RootErrorPanel.test.tsx.snap
Comment (mnholtz) [inline src/sidebar/components/__snapshots__/RootErrorPanel.test.tsx.snap:1]: This snapshot was actually wrong before we added this change. No errors were being extracted from the Error object.

File: src/bricks/errors.ts [hunk 5]
```diff
@@ -107,6 +101,12 @@ export class OutputValidationError extends BusinessError {
   }
 }
 
+export function isIOValidationError(
+  error: unknown
+): error is InputValidationError | OutputValidationError {
+  return typeof error === "object" && "schema" in error && "errors" in error;
+}
+
```
Comment (mnholtz) [inline src/bricks/errors.ts:109]: These errors are very similar in shape; at least, for our purposes so far. The original actually didn't differentiate between `Input` and `Output` validation errors

File: src/bricks/transformers/jq.ts [hunk 6]
```diff
@@ -93,6 +93,8 @@ export class JQTransformer extends TransformerABC {
     const input = isNullOrBlank(data) ? ctxt : data;
 
     try {
+      //throw new Error("compile error");
```
Comment (mnholtz) [inline src/bricks/transformers/jq.ts:96]: Will remove later; been using this for manual testing purposes.

File: src/services/errorService.ts [hunk 7]
```diff
@@ -89,7 +89,12 @@ export async function selectExtraContext(
     };
   }
 
-  return { extensionVersion };
+  // TODO: dumping entire error object (includes stack, cause, context, etc.); we can alternatively select
+  //  specific properties
+  return {
+    extensionVersion,
+    ...error,
+  };
```
Comment (mnholtz) [inline src/services/errorService.ts:97]: This should fix the missing `error_data` on `ErrorItems` in the back-end. Obviously we can be more selective on what we report here.

File: src/errors/errorHelpers.test.ts [hunk 8]
```diff
@@ -0,0 +1,91 @@
...
+  test("if InputValidationError, prefer error message", () => {
+    const inputValidationError = {
+      message: "error message",
+      errors: [{ error: "error", keywordLocation: "#/foo" }],
+    } as InputValidationError;
+    const message = getErrorMessage(inputValidationError, "default message");
+    expect(message).toEqual(inputValidationError.message);
+  });
+
+  test("if InputValidationError with no message, return first error", () => {
```
Comment (grahamlangford) [inline src/errors/errorHelpers.test.ts:52]: NIT: If we're only going to return the first error, we should include more than one error in the `inputValidationError`.

File: src/bricks/errors.ts [hunk 9]
```diff
@@ -107,6 +101,12 @@ export class OutputValidationError extends BusinessError {
   }
 }
 
+export function isIOValidationError(
```
Comment (twschiller) [inline src/bricks/errors.ts:104]: NIT: Typically I think of IO as "filesystem input/output". I'd prefer a name like `isSchemaValidationError`

File: src/errors/errorHelpers.ts [hunk 10]
```diff
@@ -183,6 +187,15 @@ function isBusinessError(error: unknown): boolean {
   return isErrorObject(error) && BUSINESS_ERROR_NAMES.has(error.name);
 }
 
+export function formatIOValidationMessage(
+  error: InputValidationError["errors"][0]
```
Comment (twschiller) [inline src/errors/errorHelpers.ts:191]: NIT: IIRC the type should be `InputValidationError["errors"][number]

File: src/errors/errorHelpers.ts (hunk 2 above)
Comment (twschiller) [reply src/errors/errorHelpers.ts:239]: NIT: it would be helpful to clarify here that we're always preferring the provided error message, if it exists vs. creating an error message from details

File: src/errors/errorHelpers.ts [hunk 11]
```diff
@@ -222,8 +234,20 @@ export function getErrorMessage(
...
+
+  if (isIOValidationError(error)) {
+    const firstError = error.errors[0];
+    return formatIOValidationMessage(firstError) ?? defaultMessage;
+  }
+
   if (isCustomAggregateError(error)) {
-    return error.errors.filter((x) => typeof x === "string").join(". ");
+    return (
+      error.errors.filter((x) => typeof x === "string").join(". ") ??
```
[the remark this answers is not in the document]
Comment (mnholtz) [reply src/errors/errorHelpers.ts]: You're right; replacing with `||` operator which will handle null, undefined, and empty string cases

File: src/sidebar/components/__snapshots__/RootErrorPanel.test.tsx.snap
Comment (grahamlangford) [reply src/sidebar/components/__snapshots__/RootErrorPanel.test.tsx.snap:1]: This is one of the reasons I don't trust snapshots, btw.

**Review by grahamlangford — APPROVED** [review]
