### PR TITLE
#5872: fix DocumentBuilder list element flickering

### LINKED ISSUE #5872: Don't flicker fetching indicator for Document Builder ListElement
Context
---
- The ListElement currently flickers on isFetching, which causes UI problems if the panel is listening to frequent state updates

### PR DESCRIPTION
**Pull request by twschiller**
## What does this PR do?

- Closes #5872 
- Switches to use the new useAsyncState hook, and shows loader on isLoading vs. isFetching
- Wraps loader in DelayedRender to avoid flickering on load, because DeferredExpression calculations are fast

## Demo

- https://www.loom.com/share/53cea03952964ed4ada14b3ade820c5a

## Future Work

- https://github.com/pixiebrix/pixiebrix-extension/issues/5825

## Checklist

- [x] Add tests: manually QA'd for now
- [x] Designate a primary reviewer: @BLoe

### CODE REVIEW

File: src/components/documentBuilder/render/ListElement.tsx [hunk 1]
```diff
@@ -58,22 +59,26 @@ const ListElementInternal: React.FC<DocumentListProps> = ({
...
-  const [rootDefinitions, isLoading, error] = useAsyncState(async () => {
+  const {
+    data: rootDefinitions,
+    isLoading,
+    error,
+  } = useAsyncState(async () => {
     const topLevelFrame = await getTopLevelFrame();
 
-    const key = `@${elementKey}`;
+    const elementVariableReference = `@${elementKey}`;
```
Comment (twschiller) [inline src/components/documentBuilder/render/ListElement.tsx:69]: Improve variable name

**Review by BLoe — APPROVED** [review]
