### PR TITLE
Feature/1396 fix blockmodal lag

### LINKED ISSUE #1396: Fix BlockModal lag
The BlockModal lags when opening and when searching, reference comment below:

> The main issue I see right now is the modal is a bit laggy - for the initial open and search. I'm not sure if I caused this (it probably is, as each brick needs to iterate through the marketplace to see if there's a listing for itself). If the cause is the block result rendering, we might need to use: https://github.com/bvaughn/react-virtualized or https://github.com/bvaughn/react-window (which should be pretty easy because the blocks have fixed heights)

https://github.com/pixiebrix/pixiebrix-extension/pull/1359#issuecomment-922546082

### PR DESCRIPTION
**Pull request by mnholtz**
Closes #1396 

This adds the `react-window` FixedWidthList component to the BlockModal results in order to reduce BlockModal lag upon adding a brick and searching for bricks.

### CODE REVIEW

**Comment by mnholtz** [comment]
Note: working on conflict resolution

File: src/components/fields/BlockModal.tsx [hunk 1]
```diff
@@ -40,31 +40,29 @@ import { useGetMarketplaceListingsQuery } from "@/services/api";
 import BlockIcon from "@/components/BlockIcon";
 import Fuse from "fuse.js";
 import { isNullOrBlank } from "@/utils";
+import { FixedSizeList as LazyList } from "react-window";
+import AutoSizer from "react-virtualized-auto-sizer";
+import styles from "@/options/pages/brickEditor/referenceTab/BlockResult.module.scss";
```
Comment (mnholtz) [inline src/components/fields/BlockModal.tsx:45]: I re-used some of this css and html from the workshop editor reference. Maybe we can combine these at some point.

File: src/components/fields/BlockModal.tsx [hunk 2]
```diff
@@ -203,17 +207,34 @@ const BlockModal: React.FunctionComponent<{
...
-                              onSelect={() => {
-                                setDetailBlock(block);
+                        <AutoSizer>
+                          {({ height, width }) => (
+                            <LazyList
+                              height={height}
+                              width={width}
+                              itemCount={searchResults.length}
+                              // The react-window library requires exact height
+                              itemSize={87}
```
Comment (twschiller) [inline src/components/fields/BlockModal.tsx:217]: NIT: in general it's better to extract out "magic constants" into named constants

**Review by twschiller — APPROVED** [review]
