### PR TITLE
#679: Disable unsupported API call in Firefox in dev tools

### LINKED ISSUE #679: Firefox lacks `port.onMessage.hasListeners()` API
Firefox is missing `onMessage.hasListeners()`, it only has `hasListener(fn)`

Used here: 
https://github.com/pixiebrix/pixiebrix-extension/blob/c34b29d67f09523d80c7ba1b68a5ebaa06c9293c/src/background/devtools/external.ts#L92
 
> What is this impacting?

The devtools panel won't load at all when this fails. I don't know exactly why it's used yet (I was just listing the Firefox limitations)

### PR DESCRIPTION
**Pull request by fregante**
Fixes #679 

It seems to work for me and it enables the PixieBrix tab in the devtools: (screenshot taken on pixiebrix.com)

Screen Shot

### CODE REVIEW

File: src/background/devtools/external.ts [hunk 1]
```diff
@@ -89,7 +89,9 @@ export async function callBackground(
     meta: { nonce, tabId: browser.devtools.inspectedWindow.tabId },
   };
 
-  if (!port.onMessage.hasListeners()) {
+  // Firefox does not support the API yet
+  // https://github.com/pixiebrix/pixiebrix-extension/issues/679
```
Comment (fregante) [inline src/background/devtools/external.ts:93]: Do you want full URLs or is the local issue number enough?

```suggestion
  // Firefox does not support the API yet #679
```

Comment (twschiller) [reply src/background/devtools/external.ts:93]: Full URL is more convenient for me right now, as I don't have issue patterns set up my IDE. But either way works, as GitHub automatically links the issue in the code

**Review by twschiller — APPROVED** [review]

File: src/background/devtools/external.ts (hunk 1 above)
Comment (fregante) [reply src/background/devtools/external.ts:93]: > GitHub automatically links the issue in the code

\* Refined GitHub 😃
