### PR TITLE
#3262: fix NPEs on `services`

### LINKED ISSUE #3262: Null pointer errors in 1.6.0-beta.4
Likely related to recent changes in state normalization behavior
- https://rollbar.com/pixiebrix/pixiebrix/items/4019/
- https://rollbar.com/pixiebrix/pixiebrix/items/4017/
- https://rollbar.com/pixiebrix/pixiebrix/items/4016/

### PR DESCRIPTION
**Pull request by twschiller**
What does this PR do?
---
- Fixes #3262 
- Handles cases where `IExtension.services` is not defined. (It's optional in the type, but in practice was always defined since we were normalizing values)
- PR implemented by searching for ".services" across the project and handling the cases of `IExtension.services`. For PageEditor FormState's services that will alsways be defined

### CODE REVIEW

File: src/validators/generic.ts [hunk 1]
```diff
@@ -410,19 +410,17 @@ async function validateExtension(
...
-        await services.locate(service.id, service.config);
-      } catch (error) {
-        if (error instanceof MissingConfigurationError) {
-          missingConfiguration.push(error);
-        } else if (error instanceof NotConfiguredError) {
-          notConfigured.push(error);
-        } else {
-          console.debug(error);
-        }
+  for (const service of extension.services ?? []) {
```
Comment (twschiller) [inline src/validators/generic.ts:413]: No changes, just simplifying control flow
