### PR TITLE
#4830 Re-enable page editor data persistence, and fix duplicate/deactivate bugs

### LINKED ISSUE #4830: Bug: Duplicate extensions in the page editor after re-activating a blueprint
Context: <https://pixiebrix.slack.com/archives/C0436P48QHY/p1670971251655569>

<p></p>

Request:  
Duplicate extensions in the page editor after re\-activating a blueprintFrom:  <span data-preserve-white-space></span>

Impact Details:  
This bug is caused by the Persist\-unsaved\-changes feature

Steps to Reproduce:  
1\. Activate a blueprint  
2\. Open the page editor and select an extension within the blueprint  
3\. Go to the extensions console and re\-activate the blueprint  
4\. Reload the page editor you'll see a duplicate of the selected extension listed under the blueprint.

This isn't a duplicate saved on the server or activated on your browser, it's just an artifact in the UI related to how the page editor handles installed \(unchanged\) versus dynamic \(changed\) extensions\.

### PR DESCRIPTION
**Pull request by BLoe**
## What does this PR do?

- Closes #4830

## Reviewer Tips

- `dynamicElementStorage.ts` provides functions to access the persisted editor state directly and remove dynamic elements from the page editor state; this logic is covered by tests
- `optionsStore` now also implements the session change tracking functionality in redux

## Demo

https://www.loom.com/share/961fa7037775475ca7ab3c6ea5280c64

## Checklist

- [x] Add tests
- [x] Designate a primary reviewer - @BALEHOK

### CODE REVIEW

File: src/store/dynamicElementStorage.ts [hunk 1]
```diff
@@ -0,0 +1,100 @@
...
+        (element) => element.uuid !== elementId
+      );
+    }
+  });
+}
+
+export async function removeDynamicElements(elementIds: UUID[]): Promise<void> {
+  const state = await getEditorState();
+  const newState = await removeElements(state, elementIds);
+  await saveEditorState(newState);
```
Comment (BALEHOK) [inline src/store/dynamicElementStorage.ts:75]: this removes elements directly from the storage, going around Redux state. how does this change get synced to the in-memory state?

File: src/options/pages/blueprints/useInstallableViewItemActions.ts [hunk 2]
```diff
@@ -192,9 +193,12 @@ function useInstallableViewItemActions(
   );
 
   const uninstall = useUserAction(
-    () => {
+    async () => {
+      await removeDynamicElements(
```
Comment (twschiller) [inline src/options/pages/blueprints/useInstallableViewItemActions.ts:197]: Is there a reason this needs to be awaited? If not, we should likely just lead as `void`

File: src/options/pages/blueprints/utils/useInstall.ts [hunk 3]
```diff
@@ -95,6 +96,8 @@ function useInstall(recipe: RecipeDefinition): InstallRecipe {
       }
 
       try {
+        await removeDynamicElementsForRecipe(recipe.metadata.id);
```
Comment (twschiller) [inline src/options/pages/blueprints/utils/useInstall.ts:99]: Same comment as https://github.com/pixiebrix/pixiebrix-extension/pull/4992/files#r1065867051

File: src/options/pages/blueprints/utils/useReinstall.ts [hunk 4]
```diff
@@ -47,6 +48,7 @@ function useReinstall(): Reinstall {
       });
 
       dispatch(removeRecipeById(recipe.metadata.id));
+      await removeDynamicElementsForRecipe(recipe.metadata.id);
```
Comment (twschiller) [inline src/options/pages/blueprints/utils/useReinstall.ts:51]: Same comment as https://github.com/pixiebrix/pixiebrix-extension/pull/4992/files#r1065867051

File: src/pageEditor/EditorLayout.tsx [hunk 5]
```diff
@@ -29,13 +29,14 @@ import useCurrentUrl from "./hooks/useCurrentUrl";
...
+import { selectIsStaleSession } from "@/store/sessionChanges/sessionChangesSelectors";
+import StaleSessionPane from "@/pageEditor/panes/StaleSessionPane";
 
 const EditorLayout: React.FunctionComponent = () => {
   const inserting = useSelector(selectInserting);
   const { restrict } = useFlags();
   const isRestricted = restrict("page-editor");
-  // TODO: Re-add this stale session check after redux persistence is fixed
-  // const isStaleSession = useSelector(selectIsStaleSession);
+  const isStaleSession = useSelector(selectIsStaleSession);
```
Comment (twschiller) [inline src/pageEditor/EditorLayout.tsx:39]: 👍

File: src/store/dynamicElementStorage.ts (hunk 1 above)
Comment (twschiller) [reply src/store/dynamicElementStorage.ts:75]: > how does this change get synced to the in-memory state?

The method that calls `removeDynamicElements` is expected to trigger the session change so that all open Page Editors show that a change was made in another tab

File: src/store/dynamicElementStorage.ts [hunk 6]
```diff
@@ -0,0 +1,100 @@
...
+      Object.entries(state).map(([key, value]) => [key, JSON.stringify(value)])
+    )
+  );
+}
+
+async function removeElements(
+  state: EditorState,
+  elementIds: UUID[]
+): Promise<EditorState> {
+  return produce(state, (draft) => {
```
Comment (twschiller) [inline src/store/dynamicElementStorage.ts:53]: Does this need to also take a recipe id so that you can clear out dirtyRecipeOptionsById, dirtyRecipeMetadataById, etc.?

When the user is remove a whole recipe,  I was expecting the cleanup to look like what's performed by the useRemoveRecipe hook in the Page Editor: https://github.com/pixiebrix/pixiebrix-extension/blob/a090b8f2e0f73e224680dec26bb0a4723d44d4a9/src/pageEditor/hooks/useRemoveRecipe.ts#L45-L45

File: src/store/dynamicElementStorage.ts [hunk 7]
```diff
@@ -0,0 +1,100 @@
...
+  });
+}
+
+export async function removeDynamicElements(elementIds: UUID[]): Promise<void> {
+  const state = await getEditorState();
+  const newState = await removeElements(state, elementIds);
+  await saveEditorState(newState);
+}
+
+export async function removeDynamicElementsForRecipe(
```
Comment (twschiller) [inline src/store/dynamicElementStorage.ts:78]: Add a comment here pointing the user to: https://github.com/pixiebrix/pixiebrix-extension/pull/4992/files#r1065879739

Also, add a comment in useRemoveRecipe pointing the user to this file.

The logic needs to roughly be kept in sync

File: src/store/dynamicElementStorage.ts [hunk 8]
```diff
@@ -0,0 +1,100 @@
...
+async function saveEditorState(state: EditorState): Promise<void> {
+  await setReduxStorage(
+    STORAGE_KEY,
+    Object.fromEntries(
+      Object.entries(state).map(([key, value]) => [key, JSON.stringify(value)])
+    )
+  );
+}
+
+async function removeElements(
```
Comment (twschiller) [inline src/store/dynamicElementStorage.ts:49]: Add a comment pointing the reader to editorSliceHelpers.ts:removeElement https://github.com/pixiebrix/pixiebrix-extension/blob/a090b8f2e0f73e224680dec26bb0a4723d44d4a9/src/pageEditor/slices/editorSliceHelpers.ts#L96-L96

And in editorSliceHelpers.ts:removeElement point the reader to this function

The logic in the methods need to be kept in sync

The differences I see:
- showV3UpgradeMessageByElement is not handled in editorSliceHelpers
- Available dynamic elements is checked via checkAvailableDynamicElements in the store?

In general, comments explaining the difference between how this works and how the Page Editor version works will be helpful in the future

File: src/store/dynamicElementStorage.ts [hunk 9]
```diff
@@ -0,0 +1,100 @@
...
+import { produce } from "immer";
+
+const STORAGE_KEY = "persist:editor" as ReduxStorageKey;
+
+/**
+ * Read dynamic elements from local storage (without going through redux-persist)
+ */
+async function getEditorState(): Promise<EditorState> {
+  const storage: Record<string, string> = await readReduxStorage(STORAGE_KEY);
+  return Object.fromEntries(
```
Comment (twschiller) [inline src/store/dynamicElementStorage.ts:35]: I think you just want to use lodash's mapValues here

File: src/store/dynamicElementStorage.ts [hunk 10]
```diff
@@ -0,0 +1,100 @@
...
+    Object.entries(storage).map(([key, value]) => [key, JSON.parse(value)])
+  ) as EditorState;
+}
+
+async function saveEditorState(state: EditorState): Promise<void> {
+  await setReduxStorage(
+    STORAGE_KEY,
+    Object.fromEntries(
+      Object.entries(state).map(([key, value]) => [key, JSON.stringify(value)])
```
Comment (twschiller) [inline src/store/dynamicElementStorage.ts:44]: I think you just want to use lodash's mapValues here

**Review by twschiller — APPROVED** [review]
Overall looking good. I called out places where we need to include comments to explain the differences in how this code works vs. the Page Editor store/slice code
