### PR TITLE
#6524: Fix redux persist extensions migrations

### LINKED ISSUE #6524: Fix NPE in Page Editor when getting mod label
Rainforest Test
---
https://app.rainforestqa.com/runs/1560664?result=failed&source=email&job=51844053

GitHub file reference
---
https://github.com/pixiebrix/pixiebrix-extension/blob/24b7daa18bccb22a4265fbeff359d1f141e38b22/src/pageEditor/sidebar/common.ts#L23-L25

Notes
---
- This bug is affecting the main branch but not the release (1.7.41-beta.2) branch
- The Rainforest test in question has the starter mods, but no other mods or starter bricks
- The `getLabel` function that threw the error is only ever used by the `DynamicEntry` component, which shouldn't be rendered during this workflow
- `DynamicEntry` is rendered instead of `InstalledEntry` when the mod component is missing an `extensionPointId`
- @mnholtz noticed that the Sidebar closed _after_ the devtools were opened
  - This behavior is not happening in the release branch
  - Something changed during the refactor may have slowed the performance of the Sidebar when mods are still loading
- Opening the Extension Console from within the Rainforest VM results in another NPE thrown here:  https://github.com/pixiebrix/pixiebrix-extension/blob/eaa2c4d528f58cc4244839de3b308b84fea75212/src/utils/modUtils.ts#L108-L110
- In the console within the Rainforest VM, there's a warning: `Error adding extension point: undefined`:
https://github.com/pixiebrix/pixiebrix-extension/blob/eaa2c4d528f58cc4244839de3b308b84fea75212/src/contentScript/lifecycle.ts#L470-L473
  -  which includes: `DoesNotExistError: Registry item does not exist: undefined` https://github.com/pixiebrix/pixiebrix-extension/blob/eaa2c4d528f58cc4244839de3b308b84fea75212/src/registry/memoryRegistry.ts#L38
- I added Storage Area Explorer in the VM:
    - When I cleared the storage
    - And relinked the Extension
    - And navigated to the welcome page again to get the starter mods
    - Then opened the Extension Console or Page Editor
    - Then everything rendered properly  
- I uploaded a local build to Rainforest to get better logging and sourcemaps
    -  The mods in `useModViewItems` looks like this:
    - image
    - Inspecting the redux logs shows that the mods are being rehydrated in the bad shape
    - image

Hypotheses
---
- ~There is something wrong with the starter mod installation, causing a mod component to not have an `extensionPointId`~
    - Could not replicate when navigating to the `welcome` page after installing the extension locally
  
- ~Something about the mods is getting into a weird state when the devtools are opened while the mods are still loading in the sidebar~
    - Waited for mods to load in the test before opening devtools and the error still presented

### PR DESCRIPTION
**Pull request by grahamlangford**
## What does this PR do?

- Fixes #6524

## Reviewer Tips

- The actual fix is in `src/store/extensionsMigrations.ts`

## Discussion

- It appears there was a very specific race condition going on
- Under normal circumstances, `getModComponentState` checks and migrates the state if necessary before redux-persist rehydrates the state
- This allows us to attach the `_persist` key if it's not already present, inferring the correct version
- In the failing Rainforest test, immediately after the extension is linked, the PageEditor was being opened
- The migration run by `readReduxStorage` had not completed, so redux-persist ran the full migrations
- This included `extensions: Object.values(state.extensions).flatMap((extension) =>
      Object.values(extension)`, which was why we were seeing the strange state

## Demo
image

## Future Work

- Based on https://redux-toolkit.js.org/rtk-query/usage/persistence-and-rehydration#redux-persist & https://redux-toolkit.js.org/usage/usage-guide#use-with-redux-persist, it would be nice to see if we can make the migrations run serially. Or at least infer the `_persist` key beforehand

## Checklist

- [x] Designate a primary reviewer @BLoe

### CODE REVIEW

File: src/store/extensionsMigrations.ts [hunk 1]
```diff
@@ -63,7 +78,7 @@ function migrateModComponentStateV1(
 }
 
 export function inferModComponentStateVersion(
-  state: ModComponentStateV0 | ModComponentStateV1 | ModComponentStateV2
+  state: ModComponentStateVersions
```
Comment (BLoe) [inline src/store/extensionsMigrations.ts:81]: Should we use the type guards for this instead of this infer function, in the PB manual migrate logic as well? Or maybe we can fix that in a follow-up?

File: src/extensionConsole/pages/onboarding/partner/PartnerSetupCard.stories.tsx [hunk 2]
```diff
@@ -72,8 +80,9 @@ const Template: Story<{
     middleware(getDefaultMiddleware) {
       return getDefaultMiddleware({
         // See https://github.com/rt2zz/redux-persist/issues/988#issuecomment-654875104
+        // See https://redux-toolkit.js.org/usage/usage-guide#use-with-redux-persist
         serializableCheck: {
-          ignoredActions: ["persist/PERSIST", "persist/FLUSH"],
+          ignoredActions: [FLUSH, REHYDRATE, PAUSE, PERSIST, PURGE, REGISTER],
```
Comment (BLoe) [inline src/extensionConsole/pages/onboarding/partner/PartnerSetupCard.stories.tsx:85]: Maybe we should extract this config/logic somewhere centralized? 🤷‍♂️  Not critical at the moment though.

File: src/store/extensionsMigrations.ts (hunk 1 above)
Comment (BLoe) [reply src/store/extensionsMigrations.ts:81]: Also, looks to me like we might have a mismatch here between the version numbers returned from this function versus the number keys in the `migrations` manifest above.

**Review by BLoe — COMMENTED** [review]
I think we need to figure out if there is a 1-indexed / 0-indexed version number mismatch here also. LGTM otherwise.

**Review by BLoe — APPROVED** [review]
