### PR TITLE
#7631: fix iframed modal form regression

### LINKED ISSUE #7631: Form not registered error in form modal when working with iframes
## Describe the bug

- Reported by 2 users
- https://pixiebrixcommunity.slack.com/archives/C02TS1K83EX/p1707805952753639

## To Reproduce

1. Activate `@pixies/7631-bug-repro`
2. Visit https://pbx.vercel.app/frames-builder.html
3. Click "Open Frame"

## Actual behavior

Modal shows in the iframe with `Form not registered: 4f2175d9-f272-40f1-b050-bcc8c9746b9b` message and the "Close" button doesn't work

## Expected behavior

For shows in the iframe

## Screenshots/Loom

Screenshot from `@pixies/7631-bug-repro` on https://pbx.vercel.app/frames-builder.html
image

Customer Screenshot
image

## Desktop (please complete the following information):

- Extension Version: 1.8.8, use reports it was working in 1.8.7

## Workaround

- A workaround it to change the form target to "Top-Level Frame"

### PR DESCRIPTION
**Pull request by twschiller**
## What does this PR do?

- Closes #7631 
- Fixes bug where createFrameSource for form running in iframe was passing the top-level frame as the opener
- Modifies the Show Form brick to throw a `BusinessError` if `location: sidebar` and brick is running in a frame

## Remaining Work

- [x] Write Jest tests
- [x] Add RainforestQA test for `@pixies/test/7631-bug-repro`: https://app.rainforestqa.com/tests/418113

## Discussion

- @fregante are there any other places we need to watch out for? It looks like Display Temporary information is working OK

## Demo

- https://www.loom.com/share/13a223ac82ef42d7a54104836a54216e

## Future Work

- This will be a good candidate for Playwright in the future

## Checklist

- [x] Add tests
- [x] New files added to `src/tsconfig.strictNullChecks.json` (if possible)
- [x] Designate a primary reviewer: @fregante 
- [ ] Post-merge: Update the RainforestQA test when this PR is merged to main. Currently it's asserting the error message is shown (so we're reminded to update it)

### CODE REVIEW

File: src/bricks/transformers/ephemeralForm/formTransformer.ts [hunk 1]
```diff
@@ -35,16 +35,21 @@ import { getConnectedTarget } from "@/sidebar/connectedTarget";
...
 type Mode = "modal" | "panel";
 
 export async function createFrameSource(
   nonce: string,
   mode: Mode,
 ): Promise<URL> {
-  const target = await getConnectedTarget();
+  // Match the frame where the form is being shown
+  const target =
+    mode === "modal" ? await getThisFrame() : await getConnectedTarget();
```
Comment (fregante) [inline src/bricks/transformers/ephemeralForm/formTransformer.ts:52]: Is this code to add compatibility with calling this *from* an iframe? getConnectedTarget already gets the top-level frame if it's outside the MV3 sidePanel

Comment (twschiller) [reply src/bricks/transformers/ephemeralForm/formTransformer.ts:52]: > Is this code to add compatibility with calling this from an iframe? 

Correct - see the Loom video for the use case. `getConnectedTarget` always returns the top-level frame, so there was a mismatch where the form modal iframe was trying to get the form definition from the top-level frame instead of the frame running the brick

**Review by grahamlangford — APPROVED** [review]

**Comment by twschiller** [comment]
Test has been update in RainforestQA
