### PR TITLE
#600: Make Google API key optional

### LINKED ISSUE #600: Gracefully degrade functionality if `GOOGLE_APP_ID` is not provided
Currently the user has to set the GOOGLE_APP_ID environment variable, otherwise the background page fails to load on Chrome

```
GOOGLE_APP_ID=
```

Related: `GOOGLE_API_KEY` and `GOOGLE_APP_ID` fail at time of use (though perhaps not elegantly): http://github.com/pixiebrix/pixiebrix-extension/blob/9acb556f36e5bf99d35daeb3dc1d77c0c9565287/src/contrib/google/sheets/FileField.tsx#L101-L101

This only impact developers working on local builds that don't want to have to connect all the integrations in order to have a working build. We don't need graceful degradation for end users

### PR DESCRIPTION
**Pull request by fregante**
Fixes #600 

Tested and it works, but `CHROME_MANIFEST_KEY` seems to still be required to go past the "Install the Chrome extension" since it's not recognizing the installed version. Since it's public I think we should include it in webpack.config.js. Thoughts?

### CODE REVIEW

File: src/contrib/google/initGoogle.ts [hunk 1]
```diff
@@ -27,30 +27,33 @@ declare global {
   }
 }
 
+// https://bumbu.me/gapi-in-chrome-extension
+async function onGAPILoad(): Promise<void> {
+  await gapi.client.init({
```
Comment (fregante) [inline src/contrib/google/initGoogle.ts:32]: I dropped the explicit catch -> console.error transform. I don't think every error needs to be explained, especially since this error will include `onGAPILoad` in its stack

File: src/contrib/google/initGoogle.ts [hunk 2]
```diff
@@ -27,30 +27,33 @@ declare global {
...
+  if (!isChrome || !API_KEY) {
+    console.info(
+      "Google API not enabled because",
+      isChrome
+        ? "the API key is not available"
+        : "it's not supported by this browser"
+    );
     return;
-  } else if (!API_KEY || API_KEY === "undefined") {
-    throw new Error("Google API_KEY not set");
```
Comment (fregante) [inline src/contrib/google/initGoogle.ts:35]: This error was blocking the rest of `background.ts` from being executed since it threw asynchronously.

File: src/contrib/google/initGoogle.ts [hunk 3]
```diff
@@ -27,30 +27,35 @@ declare global {
...
-        // Don't pass client nor scope as these will init auth2, which we don't want
-        // until the user actually uses a brick
-        apiKey: API_KEY,
-        discoveryDocs: [...BIGQUERY_DOCS, ...SHEETS_DOCS],
-      });
-      console.log("gapi initialized");
-    } catch (error) {
-      console.error("Error initializing gapi", error);
-    }
+  if (!API_KEY) {
```
Comment (fregante) [inline src/contrib/google/initGoogle.ts:49]: If undefined, this will be `null`, never `"undefined" as before.

**Review by twschiller — APPROVED** [review]
