### PR TITLE
#8781: fix the error using a hook during runtime instead of a migration

### LINKED ISSUE #8781: NPE in Page Editor when clicking into brick
## Describe the bug

- https://pixiebrix.slack.com/archives/C0436P48QHY/p1720535541845959
- See Datadog for stack trace: https://app.datadoghq.com/logs/error-tracking?issueId=c7396cb4-3dff-11ef-bf0b-da7ad0900002

## Actual behavior

A clear and concise description of what happened that shouldn't

## Screenshots/Loom

If applicable, add screenshots/looms to help explain your problem.

## Desktop (please complete the following information):

- OS: [e.g. OSX, Windows 10, Windows 11]
- Browser: [e.g. chrome, edge]
- Extension Version: [e.g. 22]

## Additional context

- What mod(s) were you running?
- What website(s) were you using?
- Do you need any special permissions to reproduce?
  - Access to a Control Room?
  - Membership on a specific team?

### PR DESCRIPTION
**Pull request by grahamlangford**
## What does this PR do?

- Fixes #8781

## Discussion

- Tried to run the `syncBrickConfigurationUIStates` function in a migration, but that pulled code into the `loadActivationEnhancements.js` bundle that is banned. Tried to work around but wasn't able, so I reverted to this solution.

## Demo

- In the process of debugging and fixing this issue, I fixed the only mod that I could reproduce the issue with
- This issue can only happen with mods installed before the previous state migration (and then only sometimes), so I can't get the editor back into a bad state to demo

For more information on our expectations for the PR process, see the
[code review principles doc](https://www.notion.so/pixiebrix/Code-Review-Principles-1ce7276b82a84d2a995d55ad85e1310d?pvs=4)

### CODE REVIEW

File: src/pageEditor/tabs/effect/BrickConfiguration.tsx [hunk 1]
```diff
@@ -76,23 +95,23 @@ const BrickConfiguration: React.FunctionComponent<{
 
     // Handle DOM bricks that were upgraded to be root-aware
     if ("isRootAware" in inputSchema) {
-      return Boolean(config.value.config.isRootAware);
+      return Boolean(config.value?.config.isRootAware);
```
Comment (BLoe) [inline src/pageEditor/tabs/effect/BrickConfiguration.tsx:98]: Don't you need another `.?` here after `config`?

Comment (grahamlangford) [reply src/pageEditor/tabs/effect/BrickConfiguration.tsx:98]: No. If `.config` exists then `.isRootAware` exists

**Review by BLoe — APPROVED** [review]
