### PR TITLE
#7822: await initial remote registry sync on packageRegistry read operations

### LINKED ISSUE #7822: "Registry Id not Found" race condition on mod activation on first run
## Describe the bug

- Extension Console/Sidebar fails with "Registry Id not Found" in some first run sequences
- https://pixiebrix.slack.com/archives/C06KXAGU0GK/p1709563459784479thread_ts=1709561584.196779&cid=C06KXAGU0GK
- Example failures: 
  - https://app.rainforestqa.com/tests/378553?envId=61914&job=54235824&run=1739534&jobGroup=19703560&step=37
  - https://app.rainforestqa.com/tests/378553/?run=1737492&jobGroup=19676520&job=54199526

## Discussion

- Fixing the delay in Extension Console/Sidebar startup times might have caused the race to occur more frequently: https://github.com/pixiebrix/pixiebrix-extension/pull/7790

### PR DESCRIPTION
**Pull request by twschiller**
## What does this PR do?

- Closes #7822 
- Awaits the initial remote registry population attempt

## Discussion

- Does not await any pending/in-flight `syncPackages` call. I think we'd have to be careful there about delaying requests that are OK with seeing slightly stale data.
- The `count` method does not await the registry being populated

## Checklist

- [x] Add tests
- [x] New files added to `src/tsconfig.strictNullChecks.json` (if possible): N/A
- [x] Designate a primary reviewer: @grahamlangford

### CODE REVIEW

File: src/registry/packageRegistry.ts [hunk 1]
```diff
@@ -182,6 +184,24 @@ export const syncPackages = memoizeUntilSettled(async () => {
   await replaceAll(packages);
 });
 
+/**
+ * Helper to ensure the IDB has synced packages. DOES NOT ensure the database has the latest package definitions --
+ * i.e., does not await any inflight syncPackages call if the database is already populated.
+ */
+async function ensurePopulated(): Promise<void> {
```
Comment (grahamlangford) [inline src/registry/packageRegistry.ts:191]: Should we `memoizeUntilSettled` this call as well to limit open db connections since there are so many potential callers of `find`?

Comment (grahamlangford) [reply src/registry/packageRegistry.ts:191]: I believe we had memory issues with the number of idb connections at one point.

Comment (grahamlangford) [reply src/registry/packageRegistry.ts:191]: Or maybe it was just a memory leak from not closing connections and we can afford to have multiple open connections.

Comment (twschiller) [reply src/registry/packageRegistry.ts:191]: > Or maybe it was just a memory leak from not closing connections and we can afford to have multiple open connections.

We definitely had memory leaks previously. Agree it wouldn't hurt to memoize

File: src/registry/packageRegistry.ts [hunk 2]
```diff
@@ -121,44 +121,6 @@ function latestVersion(
     : null;
 }
 
-/**
- * Return all packages for the given kinds
- * @param kinds kinds of bricks
- */
-export async function getByKinds(kinds: Kind[]): Promise<PackageVersion[]> {
```
Comment (twschiller) [inline src/registry/packageRegistry.ts:128]: Moved to satisfy linter

File: src/registry/packageRegistry.test.ts [hunk 3]
```diff
@@ -78,4 +80,40 @@ describe("localRegistry", () => {
...
+
+    const recipesPromise = getByKinds(["recipe"]);
+
+    await expect(count()).resolves.toBe(0);
+
+    deferred.resolve([200, [defaultModDefinitionFactory()]]);
+
+    // FIXME: test assertion failing
+    await expect(count()).resolves.toBe(1);
+    await expect(recipesPromise).resolves.toHaveLength(1);
```
Comment (grahamlangford) [inline src/registry/packageRegistry.test.ts:99]: Need the promise to resolve for the count to be 1

File: src/registry/packageRegistry.test.ts [hunk 4]
```diff
@@ -78,4 +80,40 @@ describe("localRegistry", () => {
...
+
+    const packagePromise = find("foo/bar");
+
+    await expect(count()).resolves.toBe(0);
+
+    deferred.resolve([200, []]);
+
+    // FIXME: test assertion failing
+    await expect(count()).resolves.toBe(1);
+    await expect(packagePromise).resolves.toBeNull();
```
Comment (grahamlangford) [inline src/registry/packageRegistry.test.ts:117]: Need to wait for the packagePromise. Also, if it's resolving to an empty array, shouldn't the count still be 0?

File: src/registry/packageRegistry.test.ts (hunk 3 above)
Comment (twschiller) [reply src/registry/packageRegistry.test.ts]: 👍 Just realized that - wish I had read your comment sooner

**Review by grahamlangford — APPROVED** [review]
