### PR TITLE
#7774: save host page element focus when clicking into MV2 sidebar

### LINKED ISSUE #7774: Insert at Cursor brick not working from MV2 sidebar on some sites
## Describe the bug

- https://pixiebrix.slack.com/archives/C0436P48QHY/p1709246784781219
- Insert at Cursor brick not working on:
  - Zendesk (in a ticket) — inserts only the first line. Zendesk uses CKEditor
  - GMail (in a composer) - doesn’t insert
    - It's working for Todd on MV3 using the `@pixies/ai/writer-assist-3` (v1.5.0) mod
- Mod: `@pixies/ai/writer-assist-3` (v1.5.0)
- Might be sidebar related

## Discussion

- See Slack discussion. The issue's @mthek10 is seeing are potentially MV2 sidebar focus related as it's working for Todd in MV3 sidebar and Mark when using trigger

### CKEditor inserting text on single line in MV3

1. Create a Trigger
2. Add the "Insert Text at Cursor" brick
3. Set target to "All Frames" (because CKEditor 6 editor runs in a frame)
4. Set text to be multiline, e.g., 
```
ABC

123
```
5. Click into the field and run the trigger

image

## Demo Video

- https://www.loom.com/share/c31f266f0e284fbbac4cb634578529df?sid=076f5ecf-a65a-44c7-8a7a-794b75cd21fd

## Desktop (please complete the following information):

- Extension Version: 1.8.10-beta1

### PR DESCRIPTION
**Pull request by twschiller**
## What does this PR do?

- Closes #7774
- Saves focused element when mouses into the MV2 sidebar, so we can use the element from actions the user clicks on in the sidebar

## Future Work

- Fix insertion position on DraftJS

## Checklist

- [x] Add tests: 🤷  can't test focus with JSDOM
- [x] New files added to `src/tsconfig.strictNullChecks.json` (if possible): N/A
- [x] Designate a primary reviewer: @fregante

### CODE REVIEW

File: src/contentScript/sidebarDomControllerLite.ts [hunk 1]
```diff
@@ -140,6 +145,36 @@ export function insertSidebarFrame(): boolean {
...
+      // when they re-enter the sidebar
+      if (document.activeElement !== wrapper) {
+        focusController.save();
+      }
+    },
+    { passive: true, signal: hideController.signal, capture: true },
+  );
+
+  wrapper.addEventListener(
+    "mouseeexit",
```
Comment (fregante) [inline src/contentScript/sidebarDomControllerLite.ts:162]:
```suggestion
    "mouseleave",
```

**Comment by twschiller** [comment]
> Hmm, there's 2 different controller instances:

@mnholtz I think you were seeing 2 formController instances? Seems like we're getting duplicate copies of modules

@fregante any ideas?

File: src/utils/focusController.ts [hunk 2]
```diff
@@ -23,20 +25,37 @@ const focusController = {
    * @note This doesn't behave as you'd expect across iframes
    */
   save(): void {
-    if (focusedElement) {
-      console.warn("The previously-saved focus is being overridden", {
-        focusedElement,
-      });
+    // Only HTMLElements can't have their focus restored, but we're currently ignoring this distinction
```
Comment (fregante) [inline src/utils/focusController.ts:28]:
```suggestion
    // Only HTMLElements can have their focus restored, but we're currently ignoring this distinction
```

File: src/contentScript/textEditorDom.ts [hunk 3]
```diff
@@ -64,9 +70,5 @@ export async function insertAtCursorWithCustomEditorSupport({
     return;
   }
 
-  // `textFieldEdit` handles focus required to insert the text. But, force focus to enable the user to keep typing
-  window.focus();
-  element.focus();
-
   textFieldEdit.insert(element, text);
```
Comment (fregante) [inline src/contentScript/textEditorDom.ts:73]: This should be an execCommand call so that we limit the amount of focus logic in this feature

**Comment by fregante** [comment]
> Hmm, there's 2 different controller instances:

Most likely related to frames. Filter by logging context to double check

File: src/contentScript/textEditorDom.ts (hunk 3 above)
Comment (twschiller) [reply src/contentScript/textEditorDom.ts:73]: > This should be an execCommand call so that we limit the amount of focus logic in this feature

We can deal with that later - focusing on figuring out why the focusController is broken

**Comment by twschiller** [comment]
@fregante appears to be happening in the top-level frame:

image

**Comment by fregante** [comment]
I was just looking into this issue. What I found is that the focused element does not matter (outside `input`, I suppose). What matters is the selection. The execCommand specification doesn't mention focus at all. 

What's happening here is that the JS editors are altering/losing the selection on `blur`. You can see that the selection is preserved in raw contentEditables, but this happens when clicking in the sidebar after selecting in Draft JS:

File: src/utils/focusController.ts [hunk 4]
```diff
@@ -15,39 +15,81 @@
  * along with this program.  If not, see <http://www.gnu.org/licenses/>.
  */
 
-let focusedElement: HTMLElement | undefined;
+import { isLoadedInIframe } from "@/utils/iframeUtils";
+import { uuidv4 } from "@/types/helpers";
+
+class FocusController {
```
Comment (twschiller) [inline src/utils/focusController.ts:21]: WIP: try using class so we can get an instance nonce to debug multiple controllers

**Comment by twschiller** [comment]
> I was just looking into this issue. What I found is that the focused element does not matter (outside input, I suppose). What matters is the selection. The execCommand specification doesn't mention focus at all.

I think you're digging into a different issue. I'm trying to solve for CKEditor which uses https://github.com/pixiebrix/pixiebrix-extension/blob/c31536c26cc3df4739ed8729c288bfe2684e82f0/src/contentScript/textEditorDom.ts#L62-L62 not execCommand. However, when using the MV2 sidebar I can't target that element

File: src/contentScript/sidebarDomControllerLite.ts [hunk 5]
```diff
@@ -140,6 +145,36 @@ export function insertSidebarFrame(): boolean {
...
+  );
+
+  // XXX: there's a corner case where the user has the Quick Bar open and hides the sidebar
+  hideController.signal.addEventListener(
+    "abort",
+    () => {
+      focusController.clear();
+    },
+    { passive: true, once: true },
+  );
```
Comment (fregante) [inline src/contentScript/sidebarDomControllerLite.ts:176]: Let's not add further logic to this file. The file has instructions in the header: no imports

Comment (twschiller) [reply src/contentScript/sidebarDomControllerLite.ts:176]: Correct, I'm removing logic and moving it to sidebarController

File: src/bricks/effects/InsertAtCursorEffect.ts [hunk 6]
```diff
@@ -62,12 +63,18 @@ class InsertAtCursorEffect extends EffectABC {
...
   ): Promise<void> {
+    expectContext("contentScript");
+
     if (isEmpty(text)) {
+      // Skip because inserting no text is a NOP
+      logger.debug("No text provided");
       return;
     }
 
+    console.debug("InsertAtCursorEffect", { text, root, focused: focus.get() });
```
Comment (grahamlangford) [inline src/bricks/effects/InsertAtCursorEffect.ts:76]: Was this intentionally left in?

File: src/contentScript/textEditorDom.ts [hunk 7]
```diff
@@ -53,6 +53,12 @@ export async function insertAtCursorWithCustomEditorSupport({
     "contentScript context required for editor JavaScript integrations",
   );
 
+  console.debug("insertAtCursorWithCustomEditorSupport", element);
```
Comment (grahamlangford) [inline src/contentScript/textEditorDom.ts:56]: Intentionally left in?

**Review by grahamlangford — APPROVED** [review]

File: src/contentScript/textEditorDom.ts (hunk 7 above)
Comment (twschiller) [reply src/contentScript/textEditorDom.ts:56]: No -- forgot to push changes before merging
