### PR TITLE
#3783 Adding custom form with database storage to document doesn't add PixieBrix service

### LINKED ISSUE #3783: Adding custom form with database storage to document doesn't add PixieBrix service
Steps to Reproduce
- Add a custom form to a document
- Set the storage to database and select a database
- Finish setting up the form (specifying a key)

Expected:
- It works

Actual:
- You get an input validation error when rendering the document because no PixieBrix service is defined for the call to the database

Workaround:
- Add a "Get data from PixieBrix database" brick it the root pipeline and then remove it

### PR DESCRIPTION
**Pull request by BALEHOK**
## What does this PR do?

- Fixes #3783 
- Fetches service vars from the nested pipelines
- Fixes the service field on Form database storage

## Checklist

- [x] Add tests
- [x] Designate a primary reviewer @BLoe

### CODE REVIEW

File: src/pageEditor/fields/FormRendererOptions.tsx [hunk 1]
```diff
@@ -76,53 +86,53 @@ const FormRendererOptions: React.FC<{
...
+      pruneDependencies();
     }
-    // eslint-disable-next-line react-hooks/exhaustive-deps -- setStorageValue reference changes on each render
-  }, [
-    pruneDependencies,
-    storageType,
-    previousStorageType,
-    setPreviousStorageType,
-  ]);
+  }, [storageType, pruneDependencies]);
```
Comment (BLoe) [inline src/pageEditor/fields/FormRendererOptions.tsx:111]: This `useEffect` is missing a dependency on `previousStorageType`. If that's intentional, then please suppress the lint warning and add a comment explaining why.

File: src/pageEditor/fields/FormRendererOptions.tsx [hunk 2]
```diff
@@ -76,53 +86,53 @@ const FormRendererOptions: React.FC<{
...
+    if (nextStorageType === "state") {
+      setStorageValue({ type: "state", namespace: "blueprint" } as Storage);
+    } else {
+      setStorageValue({ type: nextStorageType } as Storage);
+    }
+  };
 
+  // If the storage type changes from "database" to something else, ensure the service record at root is cleared
+  const [previousStorageType, setPreviousStorageType] = useState(storageType);
   useEffect(() => {
```
Comment (BLoe) [inline src/pageEditor/fields/FormRendererOptions.tsx:103]: Why does this need to be separate from the `changeStorageType` function and use an effect? Couldn't this all just be done inside the `changeStorageType` function?

**Review by BLoe — COMMENTED** [review]
Just want to make sure the missing dependency on the `useEffect` isn't a problem before I approve this.

File: src/pageEditor/fields/FormRendererOptions.tsx (hunk 1 above)
Comment (BALEHOK) [reply src/pageEditor/fields/FormRendererOptions.tsx:111]: `useEffect` is the only place that changes the `previousStorageType`. I think if it depended on this value it would run 2 times in a row.

File: src/pageEditor/fields/FormRendererOptions.tsx (hunk 2 above)
Comment (BALEHOK) [reply src/pageEditor/fields/FormRendererOptions.tsx:103]: This is because of data sources.
`changeStorageType` works with the next value for the type. It triggers the Formik state update with the next type and also clears the service reference if it was set.
`pruneDependencies` works with the current Formik state. It removes unused service references. To work properly the Formik state should be updated. This is why it runs in the "next" cycle after the `changeStorageType`.

Now as I'm writing this I realize how fragile and complex is our handling of Database property. I believe we should revisit this.

File: src/pageEditor/fields/FormRendererOptions.tsx (hunk 1 above)
Comment (BLoe) [reply src/pageEditor/fields/FormRendererOptions.tsx:112]: Ok, makes sense, do you mind adding a comment explaining this and suppressing the warning?

File: src/pageEditor/fields/FormRendererOptions.tsx (hunk 2 above)
Comment (BLoe) [reply src/pageEditor/fields/FormRendererOptions.tsx:103]: Yeah it's just a little bit complicated as it is, I agree. It's not a huge deal right now, but I think this could be simplified at some point.

**Review by BLoe — APPROVED** [review]

File: src/pageEditor/fields/FormRendererOptions.tsx (hunk 2 above)
Comment (BALEHOK) [reply src/pageEditor/fields/FormRendererOptions.tsx:103]: Created and issue #3798
