### PR TITLE
#8686: add additional type assertions to improve messaging if NPE reoccurs

### LINKED ISSUE #8686: NPE in Page Editor when trying to edit starter brick
## Describe the bug

- https://pixiebrix.slack.com/archives/C0436P48QHY/p1719250244784269
- Datadog error item: https://app.datadoghq.com/logs/error-tracking?issueId=c74269a8-0e44-11ef-a83c-da7ad0900002&source=all&view=spans

## Workaround

- Reactivate the problematic mod. The editor likely got into a bad state somehow

## Screenshots/Loom

- https://pixiebrix.slack.com/archives/C0436P48QHY/p1719250244784269

## Desktop (please complete the following information):

- Extension Version: 2.0.2

### PR DESCRIPTION
**Pull request by grahamlangford**
## What does this PR do?

- Closes #8686

## Discussion

- Spent some time tracing upstream from 3 different potential causes of the NPE
- Without more information, it's hard to determine which path to focus on
- Added additional type assertions to help determine the root cause if this NPE occurs again

For more information on our expectations for the PR process, see the
[code review principles doc](https://www.notion.so/pixiebrix/Code-Review-Principles-1ce7276b82a84d2a995d55ad85e1310d?pvs=4)

### CODE REVIEW

File: src/pageEditor/slices/editorSliceHelpers.ts
Comment (grahamlangford) [inline src/pageEditor/slices/editorSliceHelpers.ts:1]: Just some quick renaming while I was in the file

File: src/pageEditor/tabs/editTab/dataPanel/DataPanel.tsx [hunk 1]
```diff
@@ -212,7 +212,7 @@ const DataPanel: React.FC = () => {
 
   return (
     <Tab.Container activeKey={activeTabKey} onSelect={onSelectTab}>
-      <div className={dataPanelStyles.tabContainer}>
+      <div>
```
Comment (grahamlangford) [inline src/pageEditor/tabs/editTab/dataPanel/DataPanel.tsx:215]: Unrelated to the PR, but the `.tabContainer` class doesn't exist, so I removed it to cleanup

**Review by fungairino — APPROVED** [review]

File: src/pageEditor/tabs/editTab/dataPanel/DataPanel.tsx (hunk 1 above)
Comment (BLoe) [reply src/pageEditor/tabs/editTab/dataPanel/DataPanel.tsx:215]: Just a nit here, I know this is merged already, but I doubt we need this `<div>` anymore now
