### PR TITLE
#906: Use real links wherever possible

### LINKED ISSUE #906: "Open Extension" button does not work in Firefox
Gif shows that context menu works. The OPEN_OPTIONS message is not received by the background page.

Same hoes for the "View Templates" button

gif

### PR DESCRIPTION
**Pull request by fregante**
- Fixes #906 

Also tested in Chrome. Let's try to use real links wherever possible. 

We can use `chrome-extension://` in extension pages, they just aren't clickable only on the web (and even then we can inject a generic handler on `app.pixiebrix.com` to handle them as regular links, instead of creating a function for each)

Does this fit React’s logic?

gif

### CODE REVIEW

File: src/actionPanel/ActionPanelApp.tsx [hunk 1]
```diff
@@ -17,7 +17,6 @@
 
 import React, { useCallback, useEffect, useState } from "react";
 import { Button, Card, Nav, Tab } from "react-bootstrap";
-import { openExtensionOptions } from "@/messaging/external";
```
Comment (fregante) [inline src/actionPanel/ActionPanelApp.tsx:20]: I just realized that this was failing because it's an _external_ API, meaning it's not supposed to be used from within the extension. It broke in Firefox because the external part was only used there:

https://github.com/pixiebrix/pixiebrix-extension/blob/ede30e8e08065622ce659d1119fc296b8ac771b3/src/messaging/external.ts#L28

File: src/devTools/editor/sidebar/Sidebar.tsx [hunk 2]
```diff
@@ -123,10 +122,11 @@ const Sidebar: React.FunctionComponent<
     <div className="Sidebar d-flex flex-column vh-100">
       <div className="Sidebar__actions flex-grow-0">
         <div className="d-inline-flex flex-wrap">
-          <span
+          <a
             className="Sidebar__logo"
             dangerouslySetInnerHTML={{ __html: logo }}
-            onClick={async () => openExtensionOptions()}
+            href="/options.html"
+            target="_blank"
```
Comment (fregante) [inline src/devTools/editor/sidebar/Sidebar.tsx:129]: <table>
<tr>
	<td>😣✋ 
	<td>span[onClick]
<tr>
	<td>😌👉 
	<td>a[href]
</table>

This was also broken (Firefox)

Screen Shot 2

Tested in both Chrome and Firefox

File: src/actionPanel/ActionPanelApp.tsx (hunk 1 above)
Comment (fregante) [reply src/actionPanel/ActionPanelApp.tsx:20]: I think that `openExtensionOptions` is the only wrongly-used API here, I don't see anything else.

**Comment by twschiller** [comment]
There's an a11y eslint ruleset for react we should probably enable sooner than later: https://github.com/jsx-eslint/eslint-plugin-jsx-a11y/blob/master/docs/rules/no-static-element-interactions.md

This would catch cases like this

File: src/actionPanel/ActionPanelApp.tsx (hunk 1 above)
Comment (twschiller) [reply src/actionPanel/ActionPanelApp.tsx:20]: You're correct that it's the wrong method to call, and just happens to work on Chrome b/c of it's the same API that gets called under the hood

I think your approach of changing it to a link with href is the correct way to go

**Review by twschiller — CHANGES_REQUESTED** [review]
Look at passing `as="a"` to the Button component if it's not already rendering the elements as "a" tag

**Comment by fregante** [comment]
> we should probably enable sooner than later

🎉 



> Look at passing `as="a"` to the Button component if it's not already rendering the elements as "a" tag

It's implied by the `href`: https://react-bootstrap.github.io/components/buttons/#button-tags

> adding a `href` prop will automatically render an `<a />` element

File: src/actionPanel/ActionPanelApp.tsx (hunk 1 above)
Comment (fregante) [reply src/actionPanel/ActionPanelApp.tsx:20]: It works because `href` causes the button to turn into an `a`, as it's the only HTML element that supports it.

> adding a `href` prop will automatically render an `<a />` element

File: src/actionPanel/DefaultActionPanel.tsx [hunk 3]
```diff
@@ -39,7 +38,11 @@ const OnboardingContent: React.FunctionComponent = () => (
           </span>{" "}
           Activate a pre-made template from the Templates page.
         </p>
-        <Button onClick={async () => openExtensionOptions()} variant="info">
+        <Button
+          href="/options.html#/templates"
+          target="_blank"
```
Comment (twschiller) [inline src/actionPanel/DefaultActionPanel.tsx:43]: Codacy has a fix for the issue: [Functions that return promises must be async.](https://app.codacy.com/gh/pixiebrix/pixiebrix-extension/pullRequest?prid=7805688)
```suggestion
          <Button onClick={async () => openExtensionOptions()} variant="info">
```

File: src/actionPanel/DefaultActionPanel.tsx [hunk 4]
```diff
@@ -39,7 +38,11 @@
           </span>{" "}
           Activate a pre-made template from the Templates page.
         </p>
-        <Button onClick={async () => openExtensionOptions()} variant="info">
+        <Button
+          href="/options.html#/templates"
+          <Button onClick={async () => openExtensionOptions()} variant="info">
```
Comment (twschiller) [inline src/actionPanel/DefaultActionPanel.tsx:43]: Codacy has a fix for the issue: [Functions that return promises must be async.](https://app.codacy.com/gh/pixiebrix/pixiebrix-extension/pullRequest?prid=7805688)
```suggestion
          <Button onClick={async () => openExtensionOptions()} variant="info">
```

**Review by twschiller — APPROVED** [review]
