### PR TITLE
#4899: disable autosuggest in service configuration

### LINKED ISSUE #4899: Error inputting email address in ServiceEditorModal field
Context
---
- Seen on 1.7.16-beta.1, not seen on main? Reproduced on 1.7.16-beta.2
- https://www.loom.com/share/c00e74360e3343a79c60756ba6b048d7
- Likely due to a bug in the analysis visitor code

Steps to Reproduce
---
- Turn on variable analysis and variable suggestions in Advanced > Skunkworks
- Add the Automation Anywhere Control Room configuration
- Enter an email address for the username. The `@` is what triggers the error

image

Workaround
---
- Turn off variable assistance

Related Issues
---
- App change we had to make due to variable analysis. Potentially related: https://github.com/pixiebrix/pixiebrix-app/pull/2795

### PR DESCRIPTION
**Pull request by twschiller**
## What does this PR do?

- Closes #4899 
- Disables variable autosuggest in locations where analysis is available (because VarPopup errors out when the user types a `@`)

## Discussion

- This could have alternatively checked to see if the component was running in the dev tools context. The check for an analysis slice is conceptually cleaner

## Checklist

- Add tests: @BALEHOK will need to add tests in the future for triggering the var popup
- [x] Designate a primary reviewer: @BLoe

### CODE REVIEW

File: src/components/fields/schemaFields/widgets/TemplateToggleWidget.tsx [hunk 1]
```diff
@@ -64,7 +64,12 @@ const TemplateToggleWidget: React.VFC<TemplateToggleWidgetProps> = ({
   useEffect(() => {
     setFocusInput(false);
     setFieldDescription(selectedOption?.description);
-  }, [inputMode, inputModeOptions, setFieldDescription]);
+  }, [
+    inputMode,
+    inputModeOptions,
+    setFieldDescription,
+    selectedOption?.description,
```
Comment (twschiller) [inline src/components/fields/schemaFields/widgets/TemplateToggleWidget.tsx:71]: Fix unrelated lint

**Review by BLoe — APPROVED** [review]
