### PR TITLE
#2604: Fix ESC shortcut to close modal form

### LINKED ISSUE #2604: Pressing "ESC" will leave modal form in broken state
https://user-images.githubusercontent.com/1402241/152645868-29edd8b8-60f2-498f-ab32-d44b3b40dfb0.mov

### Steps

1. Open modal form
2. Press esc
3. Notice how it left the modal but the form is still visible

### Likely problem/solution 

We're not handling the native `<modal>` exit, so the content remains visible outside the modal.

### PR DESCRIPTION
**Pull request by fregante**
- Close #2604 

In the video:

1. Open modal
2. Press ESC

https://user-images.githubusercontent.com/1402241/152650211-d3941e5d-7d29-4c4b-9627-e52e6184d094.mov

### CODE REVIEW

File: src/blocks/transformers/ephemeralForm/modalUtils.tsx [hunk 1]
```diff
@@ -22,6 +22,13 @@ export function showModal(url: URL, signal: AbortSignal): void {
     <dialog
       ref={(dialog) => {
         dialog.showModal();
+        dialog.addEventListener(
```
Comment (fregante) [inline src/blocks/transformers/ephemeralForm/modalUtils.tsx:25]: The `onClose` attribute doesn't exist in the types. Adding it causes a type conflict with react-bootstrap’s alert. Revert the last commit to see it.

**Review by twschiller — APPROVED** [review]
