### PR TITLE
#4124: BrowserAction: notify failed clicks; debounce clicks

### LINKED ISSUE #4124: Inform user of failed sidebar injection
We used to display an alert when the sidebar would not open, but due to long delays, it caused confusion.

Now if the sidebar fails to load, absolutely nothing happens.

### Proposed solutions

- [ ] in background: show [alert](https://github.com/pixiebrix/pixiebrix-extension/pull/4079#event-7236762344) when content scripts doesn't respond, probably in `ensureContentScript`
- [ ] in content script: show notification error when sidebar doesn't respond

### Related

- https://github.com/pixiebrix/pixiebrix-extension/pull/517
- https://github.com/pixiebrix/pixiebrix-extension/pull/4079#event-7236762344
- https://github.com/pixiebrix/pixiebrix-extension/issues/4021
- https://github.com/fregante/webext-dynamic-content-scripts/issues/41
- #4125

### PR DESCRIPTION
**Pull request by fregante**
## What does this PR do?

- Avoids attempting multiple simultaneous injections in the same tab
- Shows an error when the sidebar was supposed to open, but failed
	- **Note:** this PR covers an actual failure to open the sidebar rather than "unable to edit special browser pages" like https://github.com/pixiebrix/pixiebrix-extension/pull/4188

Specifically:

- Closes #4124 
-  https://github.com/pixiebrix/pixiebrix-extension/issues/4125

## Discussion

- The "blank slate" design of the sidebar is being handled in other tickets. I think we can use the sidebar to display any _connection_ issues, rather than _injection_ (which at this point is unlikely)

## Future Work

- [ ] #4193

## Checklist

- [x] Designate a primary reviewer @twschiller

### CODE REVIEW

File: src/background/browserAction.ts [hunk 1]
```diff
@@ -40,27 +51,35 @@ async function handleBrowserAction(tab: Tabs.Tab): Promise<void> {
...
-    // https://github.com/pixiebrix/pixiebrix-extension/issues/4021
-    reportError(
-      new Error("Error opening sidebar via browser action", { cause: error })
-    );
+    webextAlert(ERR_UNABLE_TO_OPEN);
+    throw error;
   }
+
+  // NOTE: at this point, the sidebar should already be visible on the page, even if not ready.
+  // Avoid showing any alerts or notifications: further messaging can appear in the sidebar itself.
```
Comment (fregante) [inline src/background/browserAction.ts:74]: - #4193

File: src/background/browserAction.ts [hunk 2]
```diff
@@ -40,27 +51,35 @@ async function handleBrowserAction(tab: Tabs.Tab): Promise<void> {
...
+  await contentScriptPromise;
+  await rehydrateSidebar({
+    tabId,
+  });
```
Comment (fregante) [inline src/background/browserAction.ts:78]: These errors are automatically caught by our global handler

File: src/background/browserAction.ts [hunk 3]
```diff
@@ -15,18 +15,29 @@
...
-import reportError from "@/telemetry/reportError";
 import { ensureContentScript } from "@/background/util";
 import { Tabs } from "webextension-polyfill";
 import webextAlert from "./webextAlert";
 import { rehydrateSidebar } from "@/contentScript/messenger/api";
 import { executeScript, isScriptableUrl } from "webext-content-scripts";
+import pMemoize from "p-memoize";
+
+const ERR_UNABLE_TO_OPEN =
+  "PixieBrix was unable to open the sidebar. Try refreshing the page.";
```
Comment (twschiller) [inline src/background/browserAction.ts:26]: Wording: capitalize "Sidebar" because a named part of the interface

File: src/background/browserAction.ts (hunk 2 above)
Comment (twschiller) [reply src/background/browserAction.ts:78]: NIT: would be good to leave as reminder in the code?

File: src/background/browserAction.ts [hunk 4]
```diff
@@ -40,27 +51,35 @@ async function handleBrowserAction(tab: Tabs.Tab): Promise<void> {
...
+  // NOTE: at this point, the sidebar should already be visible on the page, even if not ready.
+  // Avoid showing any alerts or notifications: further messaging can appear in the sidebar itself.
+  await contentScriptPromise;
+  await rehydrateSidebar({
+    tabId,
+  });
+}
+
+async function handleBrowserAction(tab: Tabs.Tab): Promise<void> {
+  await toggleSidebar(tab.id, String(tab.url));
```
Comment (twschiller) [inline src/background/browserAction.ts:82]: What's the cast for?

**Review by twschiller — APPROVED** [review]

**Comment by twschiller** [comment]
@fregante Thanks for the PR. See small wording change. Had a question on the String cast

File: src/background/browserAction.ts (hunk 4 above)
Comment (fregante) [reply src/background/browserAction.ts:82]: I believe it was because the url property is potentially undefined for a number of reasons and ensuring it's a string avoids runtime errors. The cast was just brought over from older code

Comment (twschiller) [reply src/background/browserAction.ts:74]: Leave a comment in the code that url can sometimes come through as undefined?
