### PR TITLE
#5627 Fix one-click activation with built-in services

### LINKED ISSUE #5627: Bug: One-click activation for mods with built-in services
Mods with only built-in services aren't getting installed with service configurations via in-marketplace activation

### PR DESCRIPTION
**Pull request by mnholtz**
## What does this PR do?

- Fixes #5627

## Discussion

- Prevents auto-activation of mods before the useWizard form is initialized with default configuration values

## Demo

- https://www.loom.com/share/e8e0ab6228dd4b98aff66742aac46e21

## Checklist

- [x] Add tests - Rainforest tests in progress
    - [x] Test one-click activation with service configs https://app.rainforestqa.com/runs/1314443/tests/377988/browsers/windows10_chrome
    - [x] Test one-click activation with nothing to configure https://app.rainforestqa.com/runs/1314505/tests/374449/browsers/windows10_chrome
    - [x] Test one-click activation with personal/team configs (in addition to built-in) https://app.rainforestqa.com/runs/1314502
- [x] Designate a primary reviewer @BLoe

### CODE REVIEW

File: src/activation/useWizard.ts [hunk 1]
```diff
@@ -52,13 +54,14 @@ const STEPS: WizardStep[] = [
 ];
 
 function useWizard(
-  blueprint: RecipeDefinition
+  blueprint: RecipeDefinition,
+  defaultAuthOptions?: Record<RegistryId, UUID>
```
Comment (mnholtz) [inline src/activation/useWizard.ts:58]: I know this is gross; open to alternative suggestions here. https://www.loom.com/share/09534d0f7d0a4e1aabd26fc9ffc4bf18

File: src/sidebar/activateRecipe/ActivateRecipePanel.tsx [hunk 2]
```diff
@@ -185,14 +189,22 @@ const ActivateRecipePanelContent: React.FC<RecipeState> = ({
   ]);
 
   useEffect(() => {
-    if (!state.needsPermissions && canAutoActivate) {
+    const missingServiceConfigurations = initialValues.services.some(
+      ({ config }) => !config
+    );
```
Comment (mnholtz) [inline src/sidebar/activateRecipe/ActivateRecipePanel.tsx:194]: Probably don't need this check anymore... but want to keep it as a fail-safe.

**Review by BLoe — APPROVED** [review]
