### PR TITLE
#8687: fixes potential NPE in sidebarActivation

### LINKED ISSUE #8687: NPE in sidebar activation code
## Describe the bug

- Not user reported, but looks like the bug was introduced in 2.0.2
- https://app.datadoghq.com/logs/error-tracking?issueId=bfd59204-1db6-11ef-97c0-da7ad0900002&source=all&view=spans

## Desktop (please complete the following information):

- Extension Version: 2.0.2+

### PR DESCRIPTION
**Pull request by grahamlangford**
## What does this PR do?

- Fixes #8687

For more information on our expectations for the PR process, see the
[code review principles doc](https://www.notion.so/pixiebrix/Code-Review-Principles-1ce7276b82a84d2a995d55ad85e1310d?pvs=4)

### CODE REVIEW

File: src/background/messenger/external/_implementation.ts [hunk 1]
```diff
@@ -36,7 +36,7 @@ const HACK_EXTENSION_LINK_RELOAD_DELAY_MS = 100;
 /**
  * Chrome Storage key for tracking the mod id(s) that PixieBrix should start activation for.
  */
-const activationStorage = new StorageItem<ModActivationConfig[]>(
+const activationStorage = new StorageItem<ModActivationConfig[] | null>(
   // Keeping key for backwards compatibility
   "activatingBlueprintId",
   { defaultValue: [] },
```
Comment (grahamlangford) [inline src/background/messenger/external/_implementation.ts:42]: `defaultValue` only handles `undefined` return type. Need to handle case where the value for `activatingBlueprintId` is `null`

Comment (fungairino) [reply src/background/messenger/external/_implementation.ts:42]: Is there ever a case where the Storage Item won't have a `| null` type for its value? It might be a good idea to enforce this typing on all Storage Items. Doing a quick search I found 8 other instances of this class usage.

**Review by fungairino — APPROVED** [review]
