### PR TITLE
#4964: Permanently move JQ out of sandbox

### LINKED ISSUE #4964: Browser Extension crashes when passing large data to jq (1.7.16-beta.8)
Context
---
- Observed on 1.7.16-beta.8
- Information on customer site: https://www.notion.so/pixiebrix/Release-1-7-16-b539854bbfe74494b3be6e952b475e49
- Slack Thread: https://pixiebrix.slack.com/archives/C023KL47XV4/p1672966213033059

Steps to Reproduce
---
- Add this brick to a trigger: `@pixies/4964-repro-brick`
- Run the trigger
- Open the sidebar

Discussion
---
- Might be related to https://github.com/pixiebrix/pixiebrix-extension/issues/4968

Investigation
---
- Looks like a memory leak and/or absurd CPU utilization
- Might be related to M1. Federico is not able to product, and it didn't come up during 1.7.15 testing on my Intel Mac

### PR DESCRIPTION
**Pull request by fregante**
## What does this PR do?

JQ hasn't been run in the sandbox since https://github.com/pixiebrix/pixiebrix-extension/pull/4972. On Slack, Todd and I figured that maybe JQ doesn't actually need to run in the sandbox even in MV3, so I'm moving it out permanently.

I think this comment was the reason why it was added to the sandbox in the first place:

- https://github.com/pixiebrix/pixiebrix-extension/issues/105#issuecomment-1083084156

## Related

- Closes #4964
- Partially reverts https://github.com/pixiebrix/pixiebrix-extension/pull/4701

## Checklist

- [x] Designate a primary reviewer: @twschiller

### CODE REVIEW

File: src/utils/jq.ts [hunk 1]
```diff
@@ -0,0 +1,32 @@
...
+ */
+
+import { type JsonValue } from "type-fest";
+
+export type ApplyJqPayload = {
+  input: JsonValue;
+  filter: string;
+};
+
+export async function applyJq(payload: ApplyJqPayload) {
```
Comment (twschiller) [inline src/utils/jq.ts:25]: I think we can just move this back into the jq.ts brick module because that's the only place it's called now

**Review by twschiller — APPROVED** [review]
@fregante thanks - see comment about consolidating into the jq.ts file: https://github.com/pixiebrix/pixiebrix-extension/pull/6579/files#r1342959845
