### PR TITLE
#4552 Fix broken grant-permissions button

### LINKED ISSUE #4552: Grant Permissions button has no effect
Context
---
- Client observed on 1.7.12-alpha.3
- Intermittent
- Observed on https://impl.workday.com/
- Don't remember if we 
- Triaging as Week 44, because once you get permissions working, then it's not an issue anymore

Steps to Reproduce
---
- Open Page Editor
- Click Grant Permissions button
- Nothing happens, button is still showing and enabled 

Related Issues
---
- Potentially related to what we're seeing here: https://github.com/pixiebrix/pixiebrix-extension/issues/4551

### PR DESCRIPTION
**Pull request by BLoe**
## What does this PR do?

- Fixes #4552 
- Adds some logging to help diagnose #4551 

## Checklist

- [ ] Add tests
- [ ] Run Storybook and manually confirm that all stories are working
- [ ] Designate a primary reviewer

### CODE REVIEW

File: src/pageEditor/hooks/useCurrentUrl.ts [hunk 1]
```diff
@@ -47,16 +47,18 @@ async function onNavigation(
 
 const startWatching = once(async () => {
   browser.webNavigation.onCommitted.addListener(onNavigation);
-  urlChanges.emit(await getCurrentURL());
+  tabUrl = await getCurrentURL();
```
Comment (twschiller) [inline src/pageEditor/hooks/useCurrentUrl.ts:50]: 👍

File: src/pageEditor/hooks/useCurrentUrl.ts [hunk 2]
```diff
@@ -47,16 +47,18 @@ async function onNavigation(
...
 
 export default function useCurrentUrl(): string {
   expectContext("devTools");
 
   const [url, setUrl] = useState(tabUrl);
+
   useEffect(() => {
-    void startWatching();
     urlChanges.add(setUrl);
+    void startWatching();
```
Comment (twschiller) [inline src/pageEditor/hooks/useCurrentUrl.ts:61]: 👍

File: src/pageEditor/EditorContent.tsx [hunk 3]
```diff
@@ -62,6 +62,20 @@ const EditorContent: React.FC = () => {
 
   const url = useCurrentUrl();
 
+  useEffect(() => {
+    console.debug("EditorContent debug effect", {
```
Comment (twschiller) [inline src/pageEditor/EditorContent.tsx:66]: 👍

**Review by twschiller — APPROVED** [review]
