### PR TITLE
#2413: fixing stale config props

### LINKED ISSUE #2413: Error adding iframe in document builder
Found on 1.5.0-beta.2 (may not exist on 1.5.0, since we fixed some field toggling bugs in beta.3 etc. for 1.5.0)

Steps to reproduce:
- https://pixiebrix.slack.com/archives/C02CN01JXAA/p1642376400001200https://pixiebrix.slack.com/archives/C02CN01JXAA/p1642376400001200

image

### PR DESCRIPTION
**Pull request by BALEHOK**
Closes #2413

### CODE REVIEW

File: src/actionPanel/PanelBody.tsx [hunk 1]
```diff
@@ -36,9 +36,7 @@ const PanelBody: React.FunctionComponent<{ payload: PanelPayload }> = ({
 
     if ("error" in payload) {
       const { error } = payload;
-      return (
-        <div className="text-danger p-3">Error running panel: {error}</div>
-      );
+      throw error;
```
Comment (BALEHOK) [inline src/actionPanel/PanelBody.tsx:39]: This way `useAsyncState` will return the `error`. `PanelBody` already knows how to render an error received from the `useAsyncState`, no need to duplicate the markup.

**Review by twschiller — APPROVED** [review]
