### PR TITLE
#3326 Fix dupe sidebar panels with blueprint actions

### LINKED ISSUE #3326: When you move a sidebar panel into a blueprint, you'll get two panels
Context
- https://pixiebrix.slack.com/archives/C02CN01JXAA/p1651596855223719

Workaround
- Reload the page

Diagnosis
- When you move into a blueprint, we generate a new extension id for it
- We need to remove the panel that's associated with the old extension id

### PR DESCRIPTION
**Pull request by BLoe**
## What does this PR do?

- Fixes #3326 
- `removeRecipe()` now takes a config input similar to `removeExtension()` with a flag to bypass the confirmation modal

## Demo

[Panel is no longer duplicated after adding the extension to a blueprint](https://www.loom.com/share/79cb06cfff084d85ad7130fcd8c04ed6)

## Future Work

- other bug discovered: https://github.com/pixiebrix/pixiebrix-extension/issues/3337

### CODE REVIEW

File: src/pageEditor/hooks/useRemoveExtension.ts [hunk 1]
```diff
@@ -72,6 +72,7 @@ function useRemoveExtension(): (useRemoveConfig: Config) => Promise<void> {
         await Promise.allSettled([
           uninstallContextMenu({ extensionId }),
           removeSidebar(thisTab, extensionId),
+          traces.clear(extensionId),
```
Comment (BALEHOK) [inline src/pageEditor/hooks/useRemoveExtension.ts:75]: Nice! Should we also clear logs?
`logging.clearLog(...)`

File: src/pageEditor/sidebar/CreateRecipeModal.tsx [hunk 2]
```diff
@@ -272,11 +283,11 @@ const CreateRecipeModal: React.VFC = () => {
...
   // is open an extension element is active, then we're performing a "Save a New" on that recipe.
   const directlyActiveRecipeId = useSelector(selectActiveRecipeId);
-  const activeRecipeId = directlyActiveRecipeId ?? activeElement.recipe?.id;
+  const activeRecipeId = directlyActiveRecipeId ?? activeElement?.recipe?.id;
 
   const { data: recipes, isLoading: isRecipesLoading } = useGetRecipesQuery();
   const activeRecipe = recipes?.find(
-    (recipe) => recipe.metadata.id === activeRecipeId
+    (recipe) => activeRecipeId && recipe.metadata.id === activeRecipeId
   );
```
Comment (BALEHOK) [inline src/pageEditor/sidebar/CreateRecipeModal.tsx:291]:
```
const activeRecipe = activeRecipeId
? recipes?.find(
    (recipe) => recipe.metadata.id === activeRecipeId
  )
: undefined;
```

**Review by BALEHOK — APPROVED** [review]
Just a couple of minor suggestions.

File: src/pageEditor/hooks/useRemoveExtension.ts (hunk 1 above)
Comment (BLoe) [reply src/pageEditor/hooks/useRemoveExtension.ts:75]: I don't think we have a way to clear logs for one extension only, do we?

Comment (BALEHOK) [reply src/pageEditor/hooks/useRemoveExtension.ts:75]: we do.
`function clearLog(context: MessageContext = {})`

`clearLog` accepts [`MessageContext`](https://github.com/pixiebrix/pixiebrix-extension/blob/fbe61d434445e5afb0ccbdf0352cf21e7c651f9c/src/core.ts#L198), that is like a complex filter. If you set `extensionId` for the context it will clear only the logs related to the specified extension.
