### PR TITLE
#5134 Bug: Blueprint showing up multiple times in QuickBar

### LINKED ISSUE #5134: Bug: Blueprint showing up multiple times in QuickBar
This is Brittany's bug bash pick\.

<p></p>

Context: <https://pixiebrix.slack.com/archives/C0436P48QHY/p1674680686650869>

<span data-preserve-white-space></span>  
When you publish a blueprint and then reactive, it shows multiple times in the quick bar\. The workaround is to toggle the on and off, but most folks won't think to do that\.

<p></p>

### PR DESCRIPTION
**Pull request by BALEHOK**
## What does this PR do?

- Fixes #5134 

## Demo

https://www.loom.com/share/af0754a180734748a4b01c60377857bc

A demo with context menu item
https://www.loom.com/share/cb09feeadbe74ad68c47e4d2cd2af883

## Checklist

- [x] Add tests
- [x] Designate a primary reviewer @twschiller

### CODE REVIEW

File: src/background/activeTab.ts [hunk 1]
```diff
@@ -21,7 +22,7 @@ export default function initActiveTabTracking() {
 export async function getTabsWithAccess(): Promise<TabId[]> {
   const { origins } = await browser.permissions.getAll();
   const tabs = await browser.tabs.query({ url: origins });
-  return [...tabs.map((x) => x.id), ...possiblyActiveTabs.keys()];
+  return uniq([...tabs.map((x) => x.id), ...possiblyActiveTabs.keys()]);
```
Comment (BALEHOK) [inline src/background/activeTab.ts:25]: it can return the same tab several times making the `forEachTab` to invoke the callback for a tab multiple times

File: src/options/pages/blueprints/useInstallableViewItemActions.ts [hunk 2]
```diff
@@ -199,12 +197,15 @@ function useInstallableViewItemActions(
...
-        dispatch(removeExtension({ extensionId: extension.id }));
+        dispatch(
+          extensionActions.removeExtension({ extensionId: extension.id })
+        );
         // XXX: also remove sidebar panels that are already open?
         void uninstallContextMenu({ extensionId: extension.id });
-        reactivateEveryTab();
       }
 
+      reactivateEveryTab();
```
Comment (BALEHOK) [inline src/options/pages/blueprints/useInstallableViewItemActions.ts:207]: @twschiller  Is it ok to call `reactivateEveryTab` once we've uninstalled all the extensions, isn't it?

File: src/background/activeTab.ts (hunk 1 above)
Comment (twschiller) [reply src/background/activeTab.ts:25]: Can you add this add a code comment?

File: src/options/pages/blueprints/utils/uninstallRecipe.ts [hunk 3]
```diff
@@ -0,0 +1,41 @@
...
+  recipeExtensions: UnresolvedExtension[],
+  dispatch: Dispatch<unknown>
+): Promise<void> {
+  dispatch(extensionActions.removeRecipeById(recipeId));
+
+  const dynamicElementsToUninstall = await removeDynamicElementsForRecipe(
+    recipeId
+  );
+
+  for (const id of [
```
Comment (twschiller) [inline src/options/pages/blueprints/utils/uninstallRecipe.ts:35]: You can use uniq here to cut down on number of calls

File: src/options/pages/blueprints/utils/useReinstall.ts [hunk 4]
```diff
@@ -19,11 +19,9 @@ import { type RecipeDefinition } from "@/types/definitions";
 import { useDispatch, useSelector } from "react-redux";
 import { selectExtensions } from "@/store/extensionsSelectors";
 import { useCallback } from "react";
```
Comment (twschiller) [inline src/options/pages/blueprints/utils/useReinstall.ts:21]: Could we add a test case for this hook? Should just be a matter of mocking out the `contentScript/messenger/api` methods

File: src/store/dynamicElementStorage.ts [hunk 5]
```diff
@@ -73,16 +74,20 @@ export async function removeDynamicElements(elementIds: UUID[]): Promise<void> {
...
     for (const element of state.elements) {
       if (element.recipe?.id === recipeId) {
+        removedDynamicElements.push(element);
         removeElement(draft, element.uuid);
       }
     }
   });
   await saveEditorState(newState);
+
+  return removedDynamicElements;
```
Comment (twschiller) [inline src/store/dynamicElementStorage.ts:92]: 👍

File: src/store/dynamicElementStorage.ts [hunk 6]
```diff
@@ -73,16 +74,20 @@ export async function removeDynamicElements(elementIds: UUID[]): Promise<void> {
  */
 export async function removeDynamicElementsForRecipe(
   recipeId: RegistryId
-): Promise<void> {
+): Promise<FormState[]> {
```
Comment (twschiller) [inline src/store/dynamicElementStorage.ts:77]: Could you update the method documentation to indicate that it returns the removed elements. (Someone might assume it returns the new form state)

File: src/contentScript/messenger/registration.ts [hunk 7]
```diff
@@ -147,7 +149,8 @@ export default function registerMessenger(): void {
 
     QUEUE_REACTIVATE_TAB: queueReactivateTab,
     REACTIVATE_TAB: reactivateTab,
-    REMOVE_EXTENSION: removeExtension,
+    REMOVE_INSTALLED_EXTENSION: removeInstalledExtension,
```
Comment (twschiller) [inline src/contentScript/messenger/registration.ts:152]: 👍

**Review by twschiller — APPROVED** [review]
I think this looks good. If possible please add tests for the hooks. Historically, this part of the code has: 1) not had test coverage, 2) has been buggy

File: src/testUtils/testHelpers.tsx [hunk 8]
```diff
@@ -215,6 +221,55 @@ export function createRenderWithWrappers(configureStore: ConfigureStore) {
...
+> = RenderHookResult<TProps, TResult> & {
+  getReduxStore: () => EnhancedStore<S, A, M>;
+
+  /**
+   * The act function which should be used with the renderHook
+   */
+  act: (callback: () => Promise<void>) => Promise<undefined>;
+};
+
+export function createRenderHookWithWrappers(configureStore: ConfigureStore) {
```
Comment (BALEHOK) [inline src/testUtils/testHelpers.tsx:245]: Hey @BLoe
Here's the helper for the hooks testing.

File: src/background/activeTab.ts (hunk 1 above)
Comment (BALEHOK) [reply src/background/activeTab.ts:25]: It's not `browser.tabs.query` that returns duplicates, its a union of `browser.tabs.query` and `possiblyActiveTabs`
