### PR TITLE
#9511: fix error toast when starting new mod

### LINKED ISSUE #9511: "Error adding X, expected mod metadata" toast adding new mod
Context
---
- "Error adding X, expected mod metadata" toast adding new mod
- https://pixiebrix.slack.com/archives/C0436P48QHY/p1731445145239739

Investigation
---
- The bug occurs because the mod doesn't exist yet on this call: https://github.com/pixiebrix/pixiebrix-extension/blob/a01727785163e2693b46c0aa7996891b9bb93fec/applications/browser-extension/src/pageEditor/hooks/useAddNewModComponent.ts#L84-L84

### PR DESCRIPTION
**Pull request by twschiller**
## What does this PR do?

- Closes #9511 

## Remaining Work

- [x] Update Playwright test

For more information on our expectations for the PR process, see the
[code review principles doc](https://www.notion.so/pixiebrix/Code-Review-Principles-1ce7276b82a84d2a995d55ad85e1310d?pvs=4)

### CODE REVIEW

File: applications/browser-extension/src/pageEditor/hooks/useAddNewModComponent.ts [hunk 1]
```diff
@@ -71,10 +73,6 @@ function useFreshModNameGenerator(): () => string {
 function useAddNewModComponent(modMetadata?: ModMetadata): AddNewModComponent {
   const dispatch = useDispatch<AppDispatch>();
   const { setInsertingStarterBrickType } = useInsertPane();
-  // XXX: useFlags is async. The flag query might not be initialized by the time the callback is called. Ensure
-  // useFlags has already been used on the page, e.g., the AddStarterBrickButton, to ensure the flags have loaded by
-  // the time the returned callback is called.
-  const { flagOff } = useFlags();
```
Comment (twschiller) [inline applications/browser-extension/src/pageEditor/hooks/useAddNewModComponent.ts:77]: Unused code (only used in dependencies)

**Review by grahamlangford — APPROVED** [review]
