### PR TITLE
#987: fix useDependency nullness check; clean some lint

### LINKED ISSUE #987: Error loading options for @pixiebrix/automation-anywhere/run-bot in the page editor
#605 Cannot read property localConfig of undefined/null expression

Reference:
- https://rollbar.com/app179688180-heroku.com/pixiebrix/items/605/

### PR DESCRIPTION
**Pull request by twschiller**
Closes #987 

The UX still isn't great, because the Select widgets just show blanks while the values are loading (which can take awhile on a slow connection)

TODO:
- [x] Fix NPE when requesting permissions from the page editor for UiPath

### CODE REVIEW

File: src/contrib/uipath/LocalProcessOptions.tsx [hunk 1]
```diff
@@ -185,8 +188,8 @@ const LocalProcessOptions: React.FunctionComponent<BlockOptionProps> = ({
       <div>
         <span className="text-danger">
           UiPath Assistant not found. Don&apos;t have the UiPath Assistant?{" "}
-          <a
-            href="#"
+          <Button
+            variant="link"
             onClick={async () => {
               await openTab({
                 url: "https://robotjs.uipath.com/download",
```
Comment (fregante) [inline src/contrib/uipath/LocalProcessOptions.tsx:192]: Does this work?

```ts
<Button href="https://robotjs.uipath.com/download">
```

File: src/contrib/uipath/LocalProcessOptions.tsx [hunk 2]
```diff
@@ -218,7 +219,7 @@ const LocalProcessOptions: React.FunctionComponent<BlockOptionProps> = ({
         schema={UIPATH_PROPERTIES.releaseKey as Schema}
         isPending={processesPending}
         processes={processes}
-        fetchError={initError?.toString() ?? processesError?.toString()}
+        fetchError={initError?.toString() ?? getErrorMessage(processesError)}
```
Comment (fregante) [inline src/contrib/uipath/LocalProcessOptions.tsx:222]:
```suggestion
        fetchError={getErrorMessage (initError ?? processesError)}
```
