### PR TITLE
#4815: fix jq compile error annotation and status badge

### LINKED ISSUE #4815: InputValidationError thrown from brick shows success badge
Steps to Reproduce
---
image

### PR DESCRIPTION
**Pull request by twschiller**
## What does this PR do?

- Fixes #4815 
- Fixes a bug in the `instanceLocation` of jq compile errors translated to runtime InputValidationErrors
- Fixes bug in TraceAnalysis where if no matching instanceLocations were found, no annotations would be added

## Demo

image

## Checklist

- [x] Add tests
- [x] Designate a primary reviewer: @BALEHOK

### CODE REVIEW

File: src/analysis/analysisVisitors/traceAnalysis.ts [hunk 1]
```diff
@@ -56,27 +57,20 @@ class TraceAnalysis extends AnalysisVisitor {
...
-    if (errorRecord == null) {
-      return;
-    }
-
-    const { error: traceError } = errorRecord;
+    traceError: JsonObject
+  ): Annotation[] {
+    const annotations: Annotation[] = [];
 
     if (isInputValidationError(traceError)) {
```
Comment (twschiller) [inline src/analysis/analysisVisitors/traceAnalysis.ts:66]: Extracted into separate method to return boiler-plate

**Review by BALEHOK — APPROVED** [review]
